Feature/adapter update 3.5.0 release
googleads/googleads-mobile-android-mediation pull request #287
Opened 2020-09-03 22:18 UTC by richardh-unity3d

PR for early review of upcoming Unity Ads 3.5 Adapter.

2020-09-07 23:43 UTC, joshuajplagonera requested changes

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +        }
What if `initializeUnityAds` is called multiple times prior to the Unity Ads SDK finishing initialization? Would calling `UnityAds.initialize()` multiple times cause any issues?

That said, maybe an interface can be created here, as well as a list of listeneres, so that `UnityAds.initialize()` is only called once per session.
See `FacebookInitializer` for reference: https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookInitializer.java#L70

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    private String getPlacementId() { return mPlacementId; }
is `getPlacementId()` used anywhere else besides here? If not, then I think we can just use `mPlacementId` directly.

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                loadInterstitialAd(getPlacementId());
Can we call `UnityAds.load()` directly here?

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                                                       unityAdsInitializationError, String s) {
nit:
`String s` -> `String errorMessage`

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
>          }
Could be cleaned up:
```
if (activityReference == null) {
  // error.
  return;
}

if (!UnityAds.isReady()) {
  // error
  return;
}

UnityAds.show()
```

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +        // Unity Ads is ready to show ads for the given placementId.
Can you add a comment here saying that the adapter relies on `onUnityAdsAdLoaded()` to check if the ad has loaded to avoid confusion?

2020-09-07 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +                        loadRewardedAd(getPlacementId());
Same for rewarded, can we call `UnityAds.load()` directly here?

2020-09-11 19:51 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +        }
The UnityAds 3.5.0 SDK handles the cases where initialize is called during and after initialization is complete, so I don't think we need to modify this code path.  I can update the docstring to reflect this though.

2020-09-11 19:52 UTC, richardh-unity3d commented
@googlebot I fixed it.

2020-09-14 19:57 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +        }
Yes, if you can add a comment or update the docstring, then it would be helpful. Thanks !

2020-09-14 20:51 UTC, joshuajplagonera requested changes

2020-09-14 20:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +      mMediationBannerListener.onAdClicked(UnityBannerAd.this);
I think we should also forward `onAdOpened()` after `onAdClicked()`

2020-09-14 20:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +  public void onUnityAdsFinish(String placementId, UnityAds.FinishState finishState) {
I can't seem to get `onUnityAdsClick()` and `onUnityAdsFinish()` fire on my end, even though I see a log from the UnityAds SDK saying that a click went through:
`I/UnityAds: com.unity3d.services.core.api.Sdk.logInfo() (line:84) :: Unity Ads event: sending click event to https://impact.applifier.com/events/v2/click/3469578/000000000000000000000000?redirect=false`

This is also the same for Rewarded ads.

 Can you take a look?

2020-09-16 04:53 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +  public void onUnityAdsFinish(String placementId, UnityAds.FinishState finishState) {
Thanks for pointing this out, it looks like `UnityAds.addListener(...)`, was accidentally removed.  I will push an update once I finish testing a fix.

2020-09-16 17:50 UTC, richardh-unity3d commented
@googlebot I consent.

2020-09-17 14:52 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +      mMediationBannerListener.onAdClicked(UnityBannerAd.this);
I realized after adding the comment and call to `onAdOpened()`, that the comment isn't accurate as we have `onBannerLeftApplication`.

Do you think it would be better to add `onAdOpened` to the `onBannerLeftApplication` call instead?

2020-09-17 16:29 UTC, richardh-unity3d commented
@googlebot I fixed it.

2020-09-17 19:02 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +      mMediationBannerListener.onAdClicked(UnityBannerAd.this);
I think it would be better to rely on `onBannerClick` since that is the behavior of the previous adapter:
https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java#L230

2020-09-17 19:13 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +      UnityAds.removeListener(UnityAdapter.this);
Is removing the listener necessary? What would be the repercussions if the listener is not removed?

2020-09-17 21:49 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +      UnityAds.removeListener(UnityAdapter.this);
If the listeners are not removed then situations can arise where old listeners are called if they have not been cleaned up before showing the next ad.  This will result in multiple calls to things like `onUnityAdsClick` and `onUnityAdsFinish`.

2020-09-17 21:50 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +      mMediationBannerListener.onAdClicked(UnityBannerAd.this);
Ahh thanks.  I will just remove the comment I added then as I don't think it is necessary or correct.

2020-09-23 18:05 UTC, richardh-unity3d commented
@joshuajplagonera FYI, I am closing this PR in favor of a new one I created to resolve the CLA issues.  https://github.com/googleads/googleads-mobile-android-mediation/pull/292

2020-09-23 18:05 UTC, closed without merging