Update to InMobi SDK 909
googleads/googleads-mobile-android-mediation pull request #290
Opened 2020-09-18 06:22 UTC by SwagatoMondal

Update to InMobi SDK 909

2020-09-18 06:23 UTC, manoj897 commented
@googlebot I consent.

2020-09-18 06:23 UTC, SwagatoMondal commented
@googlebot I consent.

2020-09-23 22:42 UTC, brownEugene commented
Hello InMobi Team,
in InMobiUnifiedNativeAdMapper.java according to the reference doc: https://developers.google.com/admob/android/native/native-mediation#impression_and_click_events

There are two different approaches your adapter can use, depending on whether your ad network SDK supports tracking impressions and clicks on its own.

If your ad network SDK does not do its own impression and click tracking but provide methods to record clicks and impressions, the Google Mobile Ads SDK can track these events and notify the adapter. The UnifiedNativeAdMapper includes two methods, recordImpression() and handleClick(), which native mediation adapters can implement to call the corresponding method on your native ad object.

If your ad network SDK track clicks and impressions on its own, your adapter should override the default click and impression tracking by making the following two calls in the constructor of your UnifiedNativeAdMapper:

setOverrideClickHandling(true);
setOverrideImpressionRecording(true);

in InMobiUnifiedNativeAdMapper.java both of these approaches are used in the adapter. Do you want the Google SDK to track the events? or would you rather Inmobi SDK? I believe that the way it is coded now the override supercedes the call to recordImpression. I have linked screenshots as well for your review.

https://screenshot.googleplex.com/7fLmgFC2XY8QvJN
https://screenshot.googleplex.com/5uZ5waNUHiiUTUx.png

2020-09-29 06:18 UTC, manoj897 commented
@brownEugene  - Understood the differences, we will make the changes appropriately and update this PR.

2020-10-05 12:41 UTC, RajSuvariya-InMobi commented
@googlebot I fixed it.

2020-10-05 12:41 UTC, RajSuvariya-InMobi commented
@googlebot I fixed it.

2020-10-05 12:41 UTC, RajSuvariya-InMobi commented
@googlebot I consent.

2020-10-05 12:45 UTC, prabodhprakash commented
@googlebot I consent.

2020-10-06 05:58 UTC, RajSuvariya-InMobi commented
@googlebot I fixed it.

2020-10-14 21:55 UTC, joshuajplagonera requested changes
Please resolve merge conflicts. Otherwise the PR looks good.

2020-10-14 21:55 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/CHANGELOG.md
> +- Fix for InMobi Impression and click Handling
I believe this should be tagged under `#### Next Version` since 9.1.0.0 is already live.

2020-10-28 05:11 UTC, RajSuvariya-InMobi commented
@googlebot I fixed it.

2020-10-30 21:07 UTC, ericleich commented
Changing CLA to yes as authors consented above.

2020-11-05 18:34 UTC, ericleich commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +    setOverrideImpressionRecording(true);
This shouldn't be true. InMobi SDK doesn't have a callback to Google when InMobi records an impression. By overriding, it means Google will wait for a callback, and not track itself.

It's ok to leave overriding is false, let Google track, ignore Google's "recordImpresson" to InMobi adapter, and have InMobi track separately.

I prefer the way the code was in this regard, with an empty implementation of recordImpression() with the comment, so it was clear that the adapters are tracking separately.

2020-11-05 18:34 UTC, ericleich commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/ClickInterceptorRelativeLayout.java
> +    public boolean onInterceptTouchEvent(MotionEvent ev) {
While this view intercepts touch events from InMobi SDK, if this code ever gets reached, it will also intercept this touch event from Google, and no click event will happen.

Assuming the adapter doesn't override click events, Google's parent view should be intercepting the touch event, and calling recordClick on InMobi adapter, and the event should never propagate into this class. I don't see this fixing the underlying problem.

We are checking with our engineering team to validate this.

In your tests, were you seeing InMobi SDK take the click? Any chance that, in your test, the media view asset was not inside the UnifiedNativeAdView in your view hierarchy? Could be related to an app implementation issue.

2020-11-06 06:46 UTC, RajSuvariya-InMobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +    setOverrideImpressionRecording(true);
@ericleich InMobi has a callback for ad impression and we do report to Google. Check here https://github.com/googleads/googleads-mobile-android-mediation/blob/e62406bcd8c8926f58c3d0836eda22e91bfaf8f8/ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java#L527

2020-11-06 06:55 UTC, RajSuvariya-InMobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/ClickInterceptorRelativeLayout.java
> +    public boolean onInterceptTouchEvent(MotionEvent ev) {
The primary issue was that the InMobi view has an internal on click listener. So even when it was under the Google container the click was consumed by the InMobi view and hence Google was not reporting the recordClick() method on the adapter. Now we are wrapping the InMobi view in a container that consumes the click and passes it to the parent for handling and hence now Google container is able to report the click to the Adapter. Please test it at your end and let us know in case of any issues.

Also, yes the InMobi view is under the UnifiedNativeAdView. Check the view hierarchy. Here **"ej"** represents the InMobi view

<img width="411" alt="Screenshot 2020-11-06 at 12 19 20 PM" src="https://user-images.githubusercontent.com/63644548/98335466-0422bc80-202b-11eb-8267-11c984645ccb.png">

2020-11-17 05:52 UTC, RajSuvariya-InMobi commented
@ericleich I have replied to your review comments, please check them and help us fast-tracking this bugfix.

2020-11-21 01:09 UTC, ericleich commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +    setOverrideImpressionRecording(true);
Ah good catch. Thanks.

2020-11-21 01:12 UTC, ericleich commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/ClickInterceptorRelativeLayout.java
> +    public boolean onInterceptTouchEvent(MotionEvent ev) {
Got it, thanks for the explanation. To confirm my understanding, is the scope of the fix limited to:

`Fixed a bug where clicks on the media view asset were not being treated as clicks.`

That is, for other assets, Google should have been handling the click since InMobi was only intercepting clicks on the primary view?

2020-11-21 01:13 UTC, ericleich commented
@RajSuvariya-InMobi thanks for the clarifications. Code now looks clear and intent makes sense, we'll merge shortly after some final testing from the team.

2020-11-21 06:05 UTC, RajSuvariya-InMobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/ClickInterceptorRelativeLayout.java
> +    public boolean onInterceptTouchEvent(MotionEvent ev) {
Yes, that is more precise. Only the clicks on primary views were being intercepted by the InMobi. Other views clicks were properly detected by Google SDK.

2020-12-02 21:10 UTC, merged