Unity Adapter update to UnityAds SDK v3.5.0
googleads/googleads-mobile-android-mediation pull request #295
Opened 2020-10-02 22:24 UTC by jindoujiao

Unity Adapter updates for UnityAdsSDK v3.5.0.

- Leverage new IUnityAdsInitializationListener get UnityAds Initialization callbacks.
- 
- Leverage new IUnityAdsLoadListener to get UnityAds load() callbacks.
- 
- Limited the usage of original IUnityAdsExtendedListener for UnityAds show() callbacks only.
- 
- Created dedicate classes for RewardedAd and BannerAd. 
-
- Bug fixes.

2020-10-02 22:25 UTC, jindoujiao commented
@googlebot I consent.

2020-10-05 20:07 UTC, joshuajplagonera requested changes
First round of reviews.

2020-10-05 20:07 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +      }
We shouldn't return if `mMediationAdLoadCallback` is null, just not forward `onFailure()` if its null. We should still log the message.

```
if (!(context instanceof Activity)) {
  String adapterError = createAdapterError( ERROR_CONTEXT_NOT_ACTIVITY, "Unity Ads requires an Activity context to load ads.");
  Log.e(TAG, "Failed to load ad: " + adapterError);
  if (mMediationAdLoadCallback == null) {
   mMediationAdLoadCallback.onFailure(adapterError);
  }
  return;
}
```

Apply to the same below.

2020-10-06 17:30 UTC, joshuajplagonera requested changes

2020-10-06 17:30 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +            initializationListener.onInitializationComplete();
`return;` after this statement as well. This is causing the adapter to forward `onInitializationComplete()` twice.

2020-10-06 17:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +  private AdSize adSize;
I believe these 2 vars can be removed.

2020-10-08 21:36 UTC, ericleich commented
@richardh-unity3d Can you acknowledge `@googlebot I consent.` to unblock the CLA?

2020-10-09 18:33 UTC, AliceNoWonderland commented
@googlebot I consent.

2020-10-12 23:29 UTC, ericleich commented
Manually overriding CLA as @richardh-unity3d is on leave.

2020-10-13 01:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +            UnityBannerSize size = new UnityBannerSize(bannerWidth, bannerHeight);
We just implemented https://github.com/googleads/googleads-mobile-android-mediation/commit/f89acf12dd592dc5f8eae27bc0deb99e2a0ac896 to handle adaptive banner. This needs to be merged into this change.

2020-10-13 01:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +            if (adSize == null || size == null) {
how does Unity SDK validate the size? Our helper method in  https://github.com/googleads/googleads-mobile-android-mediation/commit/f89acf12dd592dc5f8eae27bc0deb99e2a0ac896 validates that any sizes you support are at least 50% width and 70% height of the requested size. Under what conditions would the UnityBannerSize constructor return null?

2020-10-13 01:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +            String errorMessage = "Unity Ads cannot be initialized: current device is not supported.";
Is this check part of Unity's init method? Can we just rely on Unity's SDK to check this for us and call back with a reasonable error message?

2020-10-13 01:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +        UnityAds.initialize(context, gameId, false, true, initializationListener);
If this gets called multiple times in quick succession, is Unity SDK holding onto an array of listeners to call back when init is complete?

2020-10-13 01:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +      mMediationRewardedAdCallback.onVideoStart();
Is this a more appropriate place to call mMediationRewardedAdCallback.reportAdImpression()?

2020-10-13 01:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
Does Unity SDK now guarantee 2 ad load calls for the sample placement produce 2 unique interstitial/rewarded ads? The adapter got rid of this placement -> adapter mapping and single adapter/placement at a time validation.

2020-10-13 20:23 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +            String errorMessage = "Unity Ads cannot be initialized: current device is not supported.";
Yes, this is actually being taken care in SDK, we can remove this part

2020-10-13 20:27 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityInitializer.java
> +        UnityAds.initialize(context, gameId, false, true, initializationListener);
Yes, each listener will be added into a linkedHashSet, once it finishes initialization, the callback will be triggered sequentially

2020-10-13 20:44 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +      mMediationRewardedAdCallback.onVideoStart();
Agree, our previous adapter code also had `reportAdImpression` under `onUnityAdsStart`, will change this back

2020-10-13 21:27 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
It is not guaranteed to have the same amount of unique ads as load call, but our load callback will be triggered each time and duplicated request is okay as the load callback will return its loaded or not

2020-10-14 00:35 UTC, AliceNoWonderland commented
@googlebot I consent.

2020-10-14 19:45 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +            if (adSize == null || size == null) {
Doesn't look like our UnityBannerSize constrictor will return null, I've removed that check and use admob's `getUnityBannerSize` function

2020-10-15 21:53 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
@AliceNoWonderland So that code was not just there based on the number of callbacks. Our concern is that if a publisher loads 2 ads using the the same Unity placement, unity will send 2 callbacks that 2 ads "loaded". The publisher may precache these 2 interstitials, but they are only backed by 1 unity ad. When it comes time to show the ad, the first call will work, but the second ad may fail to show since there was only 1 ad backing those 2 callbacks. This is then a lost impression opportunity that another mediated network could have taken, and also prevents the publisher from being able to cache multiple ads this way.

Our solution to this problem was to have this hashmap and to check that there wasn't another adapter instance loading/waitng to show for a particular placement. If there was, we would fail the unity adapter and give the opportunity to the next mediation line item to load an ad.

Can you bring this logic back?

2020-10-16 18:29 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
@ericleich yes, that is a fair scenario, will add the logic of tracking loaded placements back

2020-10-17 00:58 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
@ericleich we added a hashset in `UnityAdsAdapterUtils` to keep tracking requested placementIDs, it should take care of the old logic we had :)

2020-10-21 03:53 UTC, ericleich commented
Manually overriding CLA as @richardh-unity3d is on leave.

2020-10-21 04:41 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    public void onUnityAdsPlacementStateChanged(String s, UnityAds.PlacementState placementState,
is "s" the placement ID? Can you rename to placementId if that's the case? Same for other places in this file.

2020-10-21 04:41 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +      Log.w(TAG, "Unity Ads failed to load interstitial ad: " + ids + " cannot be empty.");
This method is used in places other than interstitials. Let's remove this log. Callers already log something.

2020-10-21 04:54 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    public void onUnityAdsPlacementStateChanged(String s, UnityAds.PlacementState placementState,
Yes, they are placement IDs, will change all of them

2020-10-21 04:58 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
@AliceNoWonderland This mostly works, but there's still some loss compared to the old approach.

1) Any adapter instance can simply get the set of placements and clear it, there's no object auditing that the adapter instance who "locked" that placement is the one clearing it. Holding the weak reference as part of a HashMap allows us to verify that.
2) The set is being checked before calling init, but the placement is only being locked after init. This means race conditions could allow for 2 adapters to claim the placement. And if 1 instance succeeds and the next one fails, it clears the placement id and lets a 3rd request try for that placement (losing state management) due to 1).
3) If a request times out and the adapter reference is dropped, that placement ID isn't locked forever --> if the weak reference is null, we consider that placement effectively cleared.

We can make a change after accepting this PR if you'd like, but one way or another I'd like to bring back UnitySingleton.java (or rename to UnityInstanceManager.java or something since we no longer need the other singleton functionality) to keep a `HashMap<String, WeakReference<Object>>` for placement ID -> adapter instance. I suggest `Object` since we no longer need the UnityAdapterDelegate, and unfortunately not every adapter instance extends our `Adapter` protocol.

2020-10-21 20:54 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
@ericleich we understand your concerns, however, after talking to our team, we would like to deal this scenario inside our SDK. By that we need to first understand how often this happens, and if we put `mPlacementInUse`, we will never know. And on top of this, our adapter with other mediation partners don't have this either, we would like to keep some consistent so these adapter code could be maintained a bit easier . 

Overall we think this should not be on the adapter layer and we are actively working on these situations

2020-10-24 01:33 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
@AliceNoWonderland ultimately, if Unity SDK loaded an ad per request, we wouldn't need to do check that. That might be a sizable refactor in the Unity SDK though.

I know in the past the adapter had metadata commits which I'm guessing tracked analytics like that. Would a metadata commit be a feasible approach for you to track how often that problem happens?

Are you pushing back against having mPlacementsInUse altogether, or just doing the adapter reference? We have these checks today, and I would like to keep some form of it. To move forward on this PR, I'd at least like to address issue #2. I guess I'm willing to accept the 1) behavior to allow sticking with the simplified check, and the possibility of 3) is more of a risk on your side.

Regarding other mediation platforms, IronSource SDK has a more caching-like approach which works more 1:1 with Unity's SDK. On MoPub, I think their API similar to ours and I'd guess the publisher may be hitting a "can't show ad" in some cases if this isn't being checked.

2020-10-27 17:51 UTC, AliceNoWonderland commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -  private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
Hi @ericleich we had a discussion internally and agreed that we will add this old logic back, thanks for pushing back and raise concerns.

2020-10-28 02:16 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    mPlacementsInUse.remove(mPlacementId);
@AliceNoWonderland thanks for doing HashMap again. Note that based on the usage here, we still aren't checking the value of the map to validate that the map has "this" UnityAdapter instance in the map before showing the interstitial and clearing the placements in use. In practice, that check should hopefully always pass though, and with Unity's plan to obsolete the need for this map in the medium-term future, I'm ok to accept as is.

We should be merging this soon after @joshuajplagonera also approves, and you can apply the similar approach to iOS.

2020-10-28 20:22 UTC, joshuajplagonera approved these changes

2020-10-30 00:36 UTC, merged