Feature/sdk 2521 collect signals
googleads/googleads-mobile-android-mediation pull request #308
Opened 2020-11-30 21:56 UTC by brittmullen

Included changes to support open bidding via collectSignals for interstitial and rewarded ads

2020-12-01 02:00 UTC, ericleich requested changes

2020-12-01 23:00 UTC, brittmullen commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyManager.java
> +    if (adConfiguration.getMediationExtras() != null) {
Makes sense, I'll jump on that change shortly.

2020-12-01 23:32 UTC, brittmullen commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedRenderer.java
> -    if (AdColonyRewardedEventForwarder.getInstance().isListenerAvailable(requestedZone)) {
Apologies if I'm missing something, as I wasn't in the call - but I'm a bit confused about the first point. I'll add that back for now and contact my team to see if they can provide some insight around why loading two ads from the same zone would be an issue.

Regarding the second point, makes sense. Since the AdColonyManager will essentially just set options and call success on the listener in the case we're already configured, I'll just add that logic back in for both cases to allow for a single code path there.

2020-12-03 22:42 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedRenderer.java
> -    if (AdColonyRewardedEventForwarder.getInstance().isListenerAvailable(requestedZone)) {
On the first point, a publisher using Google's SDK could in theory do:

```
final ArrayList<InterstitialAd> loadedAds = new ArrayList<>();
for (int i = 0; i < 5; i++) {
   final InterstitialAd ad = new InterstitialAd(this);
   ad.setAdUnitId(AD_UNIT_ID);
   ad.setAdListener(new AdListener() {
       @Override
       public void onAdLoaded() {
           loadedAds.add(ad);
       }

   });
   ad.loadAd(new AdRequest.Builder().build());
}
```

To load multiple ads for the same Google ad unit (meaning same adcolony zone). AdColony's load method is static and my understanding is you have a cache for that zone that might only be 1 deep. It would be bad if a publisher thought that they had 5 loaded interstitials linked to 5 different AdColony adapter instances, but only the first show() call worked because the cache size was only 1. To guard against this, the adapter quits early if there was another adapter instance that had a load in progress for the same AdColony zone, or a loaded ad that's waiting to be shown. We use weak references so that if the object is dropped by the publisher, it essentially frees up that zone again.

2020-12-03 23:50 UTC, brittmullen commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedRenderer.java
> -    if (AdColonyRewardedEventForwarder.getInstance().isListenerAvailable(requestedZone)) {
The use case makes sense, but without diving in to too many internal details, the queue for each zone is never more than "one ad ahead" - or not at all for RTB zones. For each ad request, we will request a new ad from our server.  Multiple ad requests from an AdColony zone wouldn't lead to the same instance of an ad being filled in response to them, though to my knowledge there's nothing stopping our server from responding to the request with a second instance of the same ad. If multiple requests are filled by us from a single zone, each ad instance represents its own independent ad object on our side. Although the request/load method is static the response returns a unique ad object. The only way a returned ad object can be invalidated on our side such that show() would fail is due to expiration or the ad itself already being shown.

2021-01-20 16:08 UTC, gi-adc commented
@googlebot I fixed it.

2021-01-20 16:09 UTC, gi-adc commented
@googlebot I consent.

2021-01-20 22:35 UTC, JillSong approved these changes

2021-01-22 19:22 UTC, merged