Feature/sdk 2448 banners advanced bidding
googleads/googleads-mobile-android-mediation pull request #321
Opened 2021-03-08 12:17 UTC by deamonik92

- Included changes to support advanced bidding for banners.
- Changes related to proper handling of AdError.

2021-04-14 01:22 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyMediationAdapter.java
> +  public void loadBannerAd(
Please update the dependency to 19.8.0 or higher, and use [loadRtbBannerAd](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/rtb/RtbAdapter#loadRtbBannerAd(com.google.android.gms.ads.mediation.MediationBannerAdConfiguration,%20com.google.android.gms.ads.mediation.MediationAdLoadCallback%3Ccom.google.android.gms.ads.mediation.MediationBannerAd,%20com.google.android.gms.ads.mediation.MediationBannerAdCallback%3E)) instead.



The loadRtbBannerAd is specific to RTB ads and it'll be good to implement this on day 1. one day, we'll eventually move the waterfall mediation to take advantage of the new banner API that will implement this loadBannerAd method, and it will be cleaner to separate the two implementations.

in version 19.8.0 or higher, Google's SDK prefers loadRtbBannerAd if implemented for RTB banner ads, and falls back to loadBannerAd if loadRtbBannerAd is not implemented. Same is true for all formats.

2021-04-14 01:25 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyBannerAdListener.java
> +  void destroy() {
Please do null checks everywhere else in this class on `adapter` and `mediationBannerListener` since they can now be null.

2021-04-14 01:26 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyMediationAdapter.java
> -  // TODO: Migrate all users to return an AdError instead.
Thanks for doing this TODO!

2021-04-14 14:56 UTC, deamonik92 commented
@ericleich updated and fixed

2021-04-16 01:09 UTC, ericleich requested changes

2021-04-16 01:09 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyAdapter.java
> +          @NonNull Bundle mediationExtras
I have an open bug out against the SDK, mediationExtras is incorrectly set as nonnull in the API. It is nullable and usually is unless the publisher writes extra code to provide the adapter extra params.

2021-04-16 01:09 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyAdapter.java
> +          @NonNull Bundle mediationExtras
I have an open bug out against the SDK, mediationExtras is incorrectly set as nonnull in the API. It is nullable and usually is unless the publisher writes extra code to provide the adapter extra params.

2021-04-16 01:09 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyBannerRenderer.java
> +      AdError error = createAdapterError(ERROR_BANNER_SIZE_MISMATCH,
Can you use ERROR_INVALID_SERVER_PARAMETERS here?

2021-04-16 01:09 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedEventForwarder.java
> +  void removeListener(@NonNull String zoneID) {
please make this private

2021-04-16 01:09 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedEventForwarder.java
> +  AdColonyRewardedRenderer getListener(@NonNull String zoneID) {
please make this private. Can also make return type @Nullable

2021-04-16 01:09 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedEventForwarder.java
> +    return getListener(zoneID) != null;
looks like isListenerAvailable can be removed now.

2021-04-16 01:09 UTC, ericleich commented
@deamonik92 back you you

2021-04-16 10:01 UTC, deamonik92 commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedEventForwarder.java
> +    return getListener(zoneID) != null;
Actually this is used by AdColonyRewardedRenderer.render() - line 51 
I could replace this with getListener() != null check, but I guess making that method private is recommended as you've pointed out. We don't need such exposure right now. 
So not removing this method for now...

2021-04-16 10:02 UTC, deamonik92 commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedEventForwarder.java
> +  void removeListener(@NonNull String zoneID) {
thanks! missed that...

2021-04-16 10:02 UTC, deamonik92 commented
@ericleich fixed

2021-04-16 16:36 UTC, ericleich commented on ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyRewardedEventForwarder.java
> +    return getListener(zoneID) != null;
Yep you're right, no action required here then.

2021-04-16 17:15 UTC, ericleich approved these changes

2021-04-16 22:21 UTC, merged

2024-03-21 08:58 UTC, Juntylpromicrochip1 reviewed
Backend.prototype.count