[UnityAds] Adapter updates for 3.7.1 release
googleads/googleads-mobile-android-mediation pull request #322
Opened 2021-03-31 21:19 UTC by richardh-unity3d

2021-04-28 00:00 UTC, joshuajplagonera requested changes

2021-04-28 00:00 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
> +   * @param UnityAds.UnityAdsShowError error object from Unity.
Are Show errors different than Load errors?
If so, then error codes here should be on a different range than getMediationErrorCode(UnityAdsError) which is 0-10 range.

We can probably use 300-307 range for these

2021-04-28 00:00 UTC, joshuajplagonera commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
> +        break;
Maybe we can make this cleaner by using:

```
case NOT_INITIALIZED:
  return 1;
```

and so on.

2021-05-04 21:18 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
> +   * @param UnityAds.UnityAdsShowError error object from Unity.
Yes, load errors are different than show errors.  I will update to use the new error range.

2021-05-07 20:14 UTC, ericleich requested changes

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/CHANGELOG.md
> +#### Version 3.7.1.0
BLOCKING: please set to:

#### Version 3.7.1.0 (In progress)

This way, during the time period after this is merged but before we create the release, users don't think this version is live and complain when the dependency doesn't resolve. we will update this text post-release.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +          "UnityAds failed to load for placement ID: " + placementId);
Now that UnityAds SDK gives a message, let's pass the message directly to createSDKError.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +            .onAdFailedToLoad(UnityAdapter.this, getMediationErrorCode(error));
Per my other comments createSDKError() should return an AdError object. Then you can pass return that AdError object here.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                  getMediationErrorCode(unityAdsInitializationError));
createSDKError() can return an adError, and the full AdError can go here.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    UnityAds.show(activityReference, mPlacementId, mUnityShowListener);
Please confirm UnityAds can handle a null placement ID here, ad will always invoke some callback as a result of this call (e.g. presentation failure).

If this is the case, can you add a comment saying UnityAds can handle null here?

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +      if (mMediationInterstitialListener != null && error == UnityAdsShowError.NOT_READY) {
We'll always want to invoke the onAdClosed() callback, even if onUnityAdsShowFailure() is not of UnityAdsShowError.NOT_READY type. I'm assuming that if this callback is invoked, onUnityAdsShowComplete() never gets invoked. So this is the only chance we'll have to call onAdClosed()

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
> +  static String createSDKError(@NonNull UnityAds.UnityAdsInitializationError unityAdsError, @NonNull String description) {
Our onAdFailedToLoad() callbacks now have an API to pass back an AdError object ([example](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationInterstitialListener#onAdFailedToLoad(com.google.android.gms.ads.mediation.MediationInterstitialAdapter,%20com.google.android.gms.ads.AdError))) instead of a string. Since this is new code, please make this return an AdError and pass the full AdError object back to Google.

https://github.com/googleads/googleads-mobile-android-mediation/blob/171b4aece0e3779d56a63f341886f96603ce2dc0/ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyMediationAdapter.java#L110-L123 is an example of using the helper methods to return an AdError. For the domain field, we define a constant that represents your SDK package, e.g. "com.unity3d.ads"

We'd be happy to fix the other methods later (to reduce scope of this change and get out support for 3.7.1 faster), but I'd like the new code to use the preferred format.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
> +  static String createSDKError(@NonNull UnityAds.UnityAdsLoadError unityAdsError, @NonNull String description) {
Same comment, since this is new code, please make this return an AdError.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
> +        return 300;
The reason we avoided using default is to hopefully get compiler warnings when you add another enum value that our switch is incomplete, so we'll know to add it. By adding default here, we're unlikely to catch any new ones you add in the future.

Can you move "return 300" to outside the switch statement and remove the default case? Same comment for other enums below.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
> +                      getMediationErrorCode(unityAdsInitializationError));
Pass the AdError returned by createSDKError() as I mentioned in other comments.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +          "UnityAds failed to load for placement ID: " + placementId);
pass the message param directly to createSDKError now that UnityAds provides one.

2021-05-07 20:14 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +                    unityAdsInitializationError, "UnityAds initialization failed.");
Pass the errorMessage instead

2021-05-07 20:15 UTC, ericleich commented
@richardh-unity3d Please take a look.

2021-05-07 21:08 UTC, richardh-unity3d commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    UnityAds.show(activityReference, mPlacementId, mUnityShowListener);
Yes, if a null placement ID is passed `onUnityAdsShowFailure` will be called with an INVALID_ARGUMENT error and the message "[UnityAds] Placement ID cannot be null".

2021-05-12 21:05 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +    UnityAds.show(activityReference, mPlacementId, mUnityShowListener);
Thanks for confirming!

2021-05-12 21:06 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +      if (mMediationInterstitialListener != null && error == UnityAdsShowError.NOT_READY) {
@richardh-unity3d can you address this comment?

2021-05-12 21:11 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +                    unityAdsInitializationError, "UnityAds initialization failed.");
Looks like the error message is still not being passed.

2021-05-12 21:12 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +          "UnityAds failed to load for placement ID: " + placementId);
Still losing UnityAds's message here, and it's a generic "UnityAds failed to load". Would prefer forwarding the unity message here.

2021-05-12 21:15 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
> +                    unityAdsInitializationError, "UnityAds initialization failed.");
Nevermind, this one looks done.

2021-05-12 21:16 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityMediationAdapter.java
> +                "Missing or Invalid Game ID.");
Let's forward error message here too.

2021-05-18 23:20 UTC, ericleich commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +      if (mMediationInterstitialListener != null && error == UnityAdsShowError.NOT_READY) {
@richardh-unity3d This is the last remaining comment from me. PTAL.

2021-05-24 17:44 UTC, ericleich commented
LGTM. Should be merging soon after team runs a couple of sanity tests.

2021-05-24 19:46 UTC, richardh-unity3d commented
> LGTM. Should be merging soon after team runs a couple of sanity tests.

Thanks Eric!

2021-05-24 20:56 UTC, merged