Zucks Mediation Adapter v4.8.6.2
googleads/googleads-mobile-android-mediation pull request #337
Opened 2021-06-02 09:49 UTC by S64

Hello, I'm Shuma from [Zucks, Inc.](https://zucks.co.jp/)

This pull request is a copy of our (internal) mediation adapter v4.8.6.1 with tiny tweaks for OS&V.
Please review this!

2021-06-17 02:10 UTC, joshuajplagonera requested changes
First round of reviews.

Additionally, can you reformat all of the files according to https://github.com/googleads/googleads-mobile-android-mediation/blob/master/CONTRIBUTING.md#best-practices ?

2021-06-17 02:10 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  AdError configureBannerAd(
If we remove the legacy API , then this should not be needed anymore and we can inline this in `loadBannerAd()` method.
Same for interstitial ads.

2021-06-17 02:10 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +        || adSize.equals(AdSize.MEDIUM_RECTANGLE);
We should use `MediationUtils.findClosestSize()` method to support adaptive banner sizes.
Please use this as reference: /googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NendAdapter.java#L477

2021-06-17 02:10 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  }
Can this be removed?

2021-06-17 02:10 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +            ZucksMediationAdapter.MediationExtrasBundleBuilder.KEY_FULLSCREEN_FOR_INTERSTITIAL);
I believe `containsKey()` could be removed since `getBoolean()` returns `false` if the value for key doesn't exist.

2021-06-18 00:56 UTC, S64 commented
Thanks @joshuajplagonera, I'll check the comments next week.

2021-06-22 06:00 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +            ZucksMediationAdapter.MediationExtrasBundleBuilder.KEY_FULLSCREEN_FOR_INTERSTITIAL);
@joshuajplagonera I just updated on 01e9d6c. Clearly commented that behavior if values not defined are assumed patterns.

2021-06-22 07:31 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  }
Hmm, Why did think so? I may not be aware of the ideal code.

`ZucksBannerAdapter#isValidAdSize` is internal (non-static) method for asserts  AdMob's banner (adapter) size and Zucks's pre-defined ad unit size are equals. It's fired as an instance's self state validation in the adapter lifecycle.

Implement this method, require knowing the internal property of ZucksBannerAdapter. and need to return an error if size is invalid. therefore method creation is suitable I think.

`ZucksBannerAdapter::isValidAdSize` is it's actual implementation. This is split for unit testing. Considering how its used, the former (non-static) method is suitable. But considering how to testing logics, this  ​(static) method is more suitable

2021-06-22 08:55 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +        || adSize.equals(AdSize.MEDIUM_RECTANGLE);
Just updated! Can you review this? 01e9d6c...2fc948c

2021-06-22 08:57 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/UniversalInterstitialListener.java
> +    void onLoadFailure(Exception e);
fixed 🙇 d19d30f1

2021-06-22 09:47 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/BaseMediationAdapter.java
> +    initializationCompleteCallback.onInitializationSucceeded();
just commented! Please review this. 40bc5f0

2021-06-22 09:53 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +    adBanner.setPlatform(
Right, It's a simple code.
However, banner and interstitial are different classes (files). so I think it will be easier to maintain in the future  if similar codes are written in the same file. What do you think?

2021-06-22 09:55 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +    } else {
just edited! 6b39367

2021-06-22 10:06 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +  private static String getGooglePlayServicesVersionCode() {
Yes, This code is used only in this class 2 times. But this method knows of AdMob SDK's version location and its usages.
If this method should be removed, Maybe also should be removed `AdMobUtil::getAdapterVersionName`. What do you think?

2021-06-22 10:17 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +package net.zucks.admob;
Thanks! classes in `net.zucks.admob` has moved to `com.google.ads.mediation.zucks`.
9dacba8c

2021-06-22 10:18 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/build.gradle
>  }
OK, I think this definitions was provided by your team. I'll check the new format.

2021-06-22 10:31 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/build.gradle
> +import com.google.googlejavaformat.java.JavaFormatterOptions
This import is used in `:zucks:format` gradle task to format java files with [Google Java Style](https://github.com/google/google-java-format). (not dependents by adapter artifact.)

This repository's `All adapters should be formatted using Google Style.` means `Must to use intellij-java-google-style.xml`?
It's indicated on https://github.com/googleads/googleads-mobile-android-mediation/pull/337#pullrequestreview-685678225 as well, I'll update the formatter to according your comment.

2021-06-22 10:34 UTC, S64 commented on ThirdPartyAdapters/zucks/build.gradle
> +            }
> Is this part required?

No, It's doesn't matter. Remove it to avoid confusion.

2021-06-22 10:36 UTC, S64 commented on ThirdPartyAdapters/zucks/build.gradle
> +            }
removed🙇 b8693dd0

2021-06-22 12:55 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  /** NOTE: This method will be removed. */
Yes, We're ready to remove legacy interfaces. But if remove these, AdMob SDK raises this error.

```
W/Ads: com.google.android.gms.ads.mediation.MediationBannerAdapter #009 Class mismatch: com.google.android.gms.ads.mediation.ZucksAdapter
```

2021-06-22 13:34 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/ErrorMapper.java
> +  public static final int ERROR_INTERNAL_ERROR = AdRequest.ERROR_CODE_INTERNAL_ERROR;
> Instead of using the `AdRequest` error codes, we would want to define our own error codes starting from code `100` from each ADAPTER specific errors.

Thanks! I've just fixed `@AdapterError` definitions in 3eb4c0f7.

> Additionally, if Zucks SDK provides its own error codes, then we would want to use those error codes, if any.

[Your presented method](https://github.com/googleads/googleads-mobile-android-mediation/blob/9897cb854c39f97e240b5627c6fd49e463d40105/ThirdPartyAdapters/mopub/mopub/src/main/java/com/google/ads/mediation/mopub/MoPubMediationAdapter.java#L163-L238) is used with [deprecated error interface](https://github.com/googleads/googleads-mobile-android-mediation/blob/9897cb854c39f97e240b5627c6fd49e463d40105/ThirdPartyAdapters/mopub/mopub/src/main/java/com/google/ads/mediation/mopub/MoPubMediationAdapter.java#L454).

Other adapter's "SDK Error" is [defined with prefix greater than `@AdapterError`](https://github.com/googleads/googleads-mobile-android-mediation/blob/5758c708a7874fa097b0bb56debc67ec88e9cc4f/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java#L94-L117) or [shared with `@AdapterError`](https://github.com/googleads/googleads-mobile-android-mediation/blob/ebd5f5969d4276e3b1e99421ad5edabbfc65edf8/ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyMediationAdapter.java#L110-L123).
Which is best way? Please API References if exists.

2021-06-22 13:35 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  AdError configureBannerAd(
NOTE: This issue will resolved by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r656192207 .

2021-06-22 13:37 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/package-info.java
> +/** Zucks Ad Network SDK for Android AdMob Mediation Adapter */
removed 🙆 f7c1589

2021-06-22 13:45 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/build.gradle
>  }
Just updated! Please review this. 5e47ba5

2021-06-24 22:07 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  /** NOTE: This method will be removed. */
I confirmed on my end that banner should be safe to be completely moved to the new API. For interstitials, it seems that there is an issue with showing/presenting interstitial ads, and I have raised this to the team for investigation.

That said, please proceed to remove the legacy interface for Banners, and continue to use the legacy implementation for Interstitials in the meantime.

2021-06-24 22:15 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +  private static String getGooglePlayServicesVersionCode() {
I believe both `getNetworkSdkVersionName()` and `getAdapterVersionName` can be safely removed and inlined since they do not contain any other logic aside from returning a static value.

2021-06-24 22:16 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +    adBanner.setPlatform(
That makes sense. Thank you for further explaining.

2021-06-24 22:18 UTC, joshuajplagonera commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  AdError configureBannerAd(
Replied to the previous comment.

2021-06-29 02:07 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/net/zucks/admob/AdMobUtil.java
> +  private static String getGooglePlayServicesVersionCode() {
ok, I've edited! d7461b7f

2021-06-29 08:41 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  /** NOTE: This method will be removed. */
I just removed (only of) the legacy banner apis and published it to local maven repository. This is my diffs from [current HEAD](https://github.com/googleads/googleads-mobile-android-mediation/pull/337/commits/d7461b7f59d091ddfd5dd439f4e721618f03413b):

- https://gist.github.com/S64/66909da1e1780d66377f952b98feff60

But error was not solved. It's looks like https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r656192207 to me.

<details>
<summary>Logcat</summary>

```
I/ucks.test.admo: The ClassLoaderContext is a special shared library.
I/ucks.test.admo: The ClassLoaderContext is a special shared library.
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:211512000
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 211512000
D/DynamitePackage: Instantiated singleton DynamitePackage.
    Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads: This request is sent from a test device.
W/ConnectionStatusConfig: Dynamic lookup for intent failed for action: com.google.android.gms.leibniz.events.service.START
E/GmsClient: unable to connect to service: com.google.android.gms.leibniz.events.service.START on com.google.android.gms
I/WebViewFactory: Loading com.google.android.webview version 83.0.4103.106 (code 410410686)
I/ucks.test.admo: The ClassLoaderContext is a special shared library.
D/nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86_64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86_64:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86_64:/product/lib64:/system/product/lib64
I/ucks.test.admo: The ClassLoaderContext is a special shared library.
D/nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86_64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86_64:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86_64:/product/lib64:/system/product/lib64
I/cr_LibraryLoader: Loaded native library version number "83.0.4103.106"
I/cr_CachingUmaRecorder: Flushed 3 samples from 3 histograms.
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:211512000
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 211512000
W/Parcel: **** enforceInterface() expected 'com.google.android.gms.ads.clearcut.IClearcut' but read 'com.google.android.gms.gass.internal.clearcut.IClearcut'
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:211512000
I/DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 211512000
I/Choreographer: Skipped 421 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=7142ms; Flags=0, IntendedVsync=8307565873131, Vsync=8314582539517, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=8314587088283, AnimationStart=8314587227283, PerformTraversalsStart=8314596793283, DrawStart=8314682630283, SyncQueued=8314702497283, SyncStart=8314703722283, IssueDrawCommandsStart=8314703852283, SwapBuffers=8314706133283, FrameCompleted=8314709457283, DequeueBufferDuration=1199000, QueueBufferDuration=1354000, GpuCompleted=0, 
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:211512000
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 211512000
W/Parcel: **** enforceInterface() expected 'com.google.android.gms.ads.clearcut.IClearcut' but read 'com.google.android.gms.gass.internal.clearcut.IClearcut'
W/ucks.test.admo: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
D/HostConnection: HostConnection::get() New Host Connection established 0x7f9a9bed3890, tid 11232
W/cr_media: Requires BLUETOOTH permission
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: eglCreateContext: 0x7f9a8bf67900: maj 3 min 0 rcv 3
    eglMakeCurrent: 0x7f9a8bf67900: ver 3 0 (tinfo 0x7f9a2c62a9b0) (first time)
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
D/EGL_emulation: eglCreateContext: 0x7f9a8bf65330: maj 3 min 0 rcv 3
I/ucks.test.admo: Waiting for a blocking GC Instrumentation
I/ucks.test.admo: Background young concurrent copying GC freed 44079(3332KB) AllocSpace objects, 10(384KB) LOS objects, 37% free, 6798KB/10MB, paused 685us total 103.507ms
I/ucks.test.admo: WaitForGcToComplete blocked Instrumentation on Instrumentation for 65.773ms
W/ucks.test.admo: Verification of void com.google.android.gms.ads.mediation.ZucksAdapter.<init>() took 129.542ms (69.48 bytecodes/s) (1656B approximate peak alloc)
W/Ads: com.google.android.gms.ads.mediation.MediationBannerAdapter #009 Class mismatch: com.google.android.gms.ads.mediation.ZucksAdapter
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:211512000
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 211512000
D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10156; state: ENABLED
D/MyBannerActivity: onAdLoaded
D/MyBannerActivity: onAdImpression
I/ucks.test.admo: Background concurrent copying GC freed 43924(2631KB) AllocSpace objects, 19(1436KB) LOS objects, 49% free, 7096KB/13MB, paused 530us total 237.738ms
```

</details>

Is this problem the same as [Interstitials Ads issue](https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r658314547)?

2021-07-07 11:08 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  /** NOTE: This method will be removed. */
NOTE: I've sent an email about a problem that might be related to this to mediation-support team.

2021-07-13 04:30 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  /** NOTE: This method will be removed. */
Hi @joshuajplagonera, Thanks to your team to fix the production issue last week.
I just checked today this thread's issue, seems not resolved. This thread's issue seems not related to the last week's production issue.

2021-07-30 06:57 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +public abstract class BaseMediationAdapter extends Adapter {
We don't really need this `BaseMediationAdapter` abstract class, as we can just extend the `ZucksMediationAdapter` class from `Adapter` and implement all the `initialize`, `getVersionInfo` and `getSDKVersionInfo` methods there. In addition, those methods should only need to be implemented one time (in `ZucksMediationAdapter` class).

After the legacy code is removed, `ZucksAdapter`, `ZucksBannerAdapter` and `ZucksInterstitialAdapter` classes should not need to extend from `BaseMediationAdapter`.

2021-07-30 07:01 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +    return AdMobUtil.getAdapterVersionInfo();
We don't really need a util for this. All the implementations can be done within the method itself.

2021-07-30 07:01 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +    return AdMobUtil.getNetworkSdkVersionInfo();
Same as above, we don't really need a util for this. All the implementations can be done here.

2021-07-30 07:04 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
We don't need these two utils `getNetworkSdkVersionInfo` and `getAdapterVersionInfo`, since `getVersionInfo` and `getSDKVersionInfo` will be the only places that call them.

2021-07-30 07:13 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +  }
I think this should be placed in `ZucksInterstitialAdapter` instead.

2021-07-30 07:15 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +public class ZucksMediationAdapter {
This class should extend from `Adapter` class instead.

2021-07-30 07:59 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +    }
Same as above, this should be implemented in `ZucksInterstitialAdapter` instead.

2021-07-30 08:00 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> + * If you want to integrate Rewarded Ad, see the new mediation adapter implementation.
Should mention Rewarded Ad is not ready yet

2021-08-03 01:32 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> + * If you want to integrate Rewarded Ad, see the new mediation adapter implementation.
You're right. Updated in ef06a02a65477cfb6992abab6f95c76c50248aea!

2021-08-03 06:55 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +public abstract class BaseMediationAdapter extends Adapter {
@joshh-devrel 
For historical reasons, Zucks Mediation Adapter's banner/interstitial implementation is using `com.google.android.gms.ads.mediation.ZucksAdapter` as its entrypoint FQCN.

Rewarded ad support is a new feature, the mediation support team asks me to use `com.google.ads.mediation.zucks.ZucksMediationAdapter` as its entrypoint FQCN.

Adapters with a similar history are i-mobile:

- https://github.com/googleads/googleads-mobile-android-mediation/blob/a27e2884992af4ce1c11564d63332a3fc601b6a1/ThirdPartyAdapters/imobile/imobile/src/main/java/com/google/ads/mediation/imobile/IMobileAdapter.java#L28-L31
- https://github.com/googleads/googleads-mobile-android-mediation/blob/a27e2884992af4ce1c11564d63332a3fc601b6a1/ThirdPartyAdapters/imobile/imobile/src/main/java/com/google/ads/mediation/imobile/IMobileMediationAdapter.java#L27-L30

`com.google.android.gms.ads.mediation.ZucksAdapter` and `com.google.ads.mediation.zucks.ZucksMediationAdapter` are different FQCN, I think that each classes should work as an separated and independent adapter.

Please tell me, Does your comment means my understanding is wrong?

If both were implemented to use the latest API (`com.google.android.gms.ads.mediation.Adapter`) and could be used as separated/independent adapters, I think it would be better to use the abstract class than to write same code twice.

2021-08-03 08:16 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +    }
In `SampleAdapter`, MediationExtrasBundleBuilder is seems implemented as format-wide class.
Does this mean that implementation in SampleAdapter is not appropriate? Or does it mean that pattern we want to do and in SampleAdapter are not the same?

- https://github.com/googleads/googleads-mobile-android-mediation/blob/8a7226710a20f1737718e30b721101ae13200e06/Example/adapter/src/main/java/com/google/ads/mediation/sample/adapter/SampleAdapter.java#L428-L433

2021-08-03 08:18 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +  }
NOTE: This issue may be affected by the following comment.
https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r681539028

2021-08-03 08:25 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
NOTE: This issue may be affected by the following comment.
https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r681484842

2021-08-16 04:36 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Google Mobile Ads SDK version 19.7.0.
Recommend to build and test with the [newest version of Google Mobile Ads SDK](https://developers.google.com/admob/android/sdk).

2021-08-18 05:04 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- **NOT** supports rewarded ads. This feature will be supports in next release.
Recommended edits:

**DOES NOT** support rewarded ads. This feature will be supported in the next release.

2021-08-18 05:04 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Supports banner and interstitial.
Nit: 

Supports banner and interstitial ads.

2021-08-18 05:04 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/build.gradle
>          jcenter()
We probably don't need `jcenter()` anymore.

2021-08-18 05:05 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/build.gradle
>          jcenter()
Ditto: `jcenter()` might not be needed.

2021-08-18 05:10 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
Actually it is fine to have the utils for `getSDKVersionInfo` and `getVersionInfo`, but eventually we only need to call it from one place.

2021-08-18 05:11 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +    return AdMobUtil.getAdapterVersionInfo();
Mark as resolved since this is non-blocking.

2021-08-18 05:11 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +    return AdMobUtil.getNetworkSdkVersionInfo();
Mark as resolved since this is non-blocking.

2021-08-18 06:34 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +public abstract class BaseMediationAdapter extends Adapter {
Based on the mediation configurations for Zucks that I have looked at, `com.google.ads.mediation.zucks.ZucksMediationAdapter` will be the initializer class, so the [`initialize()`](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/Adapter#public-abstract-void-initialize-context-context,-initializationcompletecallback-callback,-listmediationconfiguration-configurations) method will be called in the `ZucksMediationAdapter` class.

As a result, `ZucksMediationAdapter` can just extend from the `Adapter` class and implement the `initialize()` method. Since Zucks is not participating in (real-time bidding)[https://support.google.com/authorizedbuyers/answer/6136272?hl=en] at the moment, `getVersionInfo` and `getSDKVersionInfo` are not needed but there's no harm to include them anyway.

2021-08-18 06:38 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +public class ZucksMediationAdapter {
See the above (comment)[https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r690941341].

2021-08-18 06:44 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +public class ZucksAdapter extends BaseMediationAdapter
We don't need to extend from the `BaseMediationAdapter` class, see this (comment)[https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r690941341].

2021-08-18 06:56 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +        MediationInterstitialAdapter,
Please be aware that [MediationBannerAdapter](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationBannerAdapter) and [MediationInterstitialAdapter](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationInterstitialAdapter?hl=en) are deprecated.

2021-08-18 07:38 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +class ZucksBannerAdapter extends BaseMediationAdapter
If I understand correctly, I think the main reason why you extend from the `BaseMediationAdapter` class is because there is the `loadBannerAd` method in this class.

But if you look at `ZucksAdapter` class, it already extends from the `BaseMediationAdapter`, so perhaps we can just add these two properties:
```
  private MediationBannerAdConfiguration adConfiguration;
  private MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback;
```
in this `ZucksBannerAdapter` class, then we just create the instance in `ZucksAdapter` by passing those two parameters.

In this case we need to have this constructor in `ZucksBannerAdapter` class:
```
  public ZucksBannerAdapter(MediationBannerAdConfiguration adConfiguration,
      MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
    this.adConfiguration = adConfiguration;
    this.callback = callback;
  }
```

Please note that if we are going to deprecate `ZucksAdapter` class (i.e. remove all the implementations and extend it from `ZucksMediationAdapter`), `ZucksMediationAdapter` class will then be responsible to do the `loadBannerAd`.

2021-08-18 07:40 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  static class ZucksMediationBannerAd implements MediationBannerAd {
Why do we need to have a static nested classes for the new implementation?

2021-08-18 08:50 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +class ZucksInterstitialAdapter extends BaseMediationAdapter
Same as this [comment](https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r690982469), we don't really need to extend from `BaseMediationAdapter` (or `Adapter`.

2021-08-18 08:55 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
Non-blocking, mark this as resolved.

2021-08-25 07:02 UTC, S64 commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Supports banner and interstitial.
Updated in 04a3cde7 🙇

2021-08-25 07:58 UTC, S64 commented on ThirdPartyAdapters/zucks/build.gradle
>          jcenter()
OK. This line was in the original template project, so this can remove if AdMob doesn't need it.

Zucks SDK depends on ExoPlayer and its (preferred) dependent version is hosted only on JCenter, so I edited to update the dependent ExoPlayer version by adapter.
Can you review 035281586fbd953a19dbafc34a6b63779560b72d ?

2021-08-25 07:59 UTC, S64 commented on ThirdPartyAdapters/zucks/build.gradle
>          jcenter()
Removed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r695501603.

2021-08-31 04:05 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +public abstract class BaseMediationAdapter extends Adapter {
@joshh-devrel So that's it. It's a very convincing comment.
I just updated in 10669041...3502de1c. can you review this?

2021-08-31 04:06 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +    return AdMobUtil.getAdapterVersionInfo();
fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r698966251.

2021-08-31 04:06 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/BaseMediationAdapter.java
> +    return AdMobUtil.getNetworkSdkVersionInfo();
fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r698966251.

2021-08-31 04:07 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r698966251.

2021-08-31 04:08 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ZucksMediationAdapter.java
> +public class ZucksMediationAdapter {
fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r698966251.

2021-08-31 04:08 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +public class ZucksAdapter extends BaseMediationAdapter
fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r698966251.

2021-08-31 07:42 UTC, S64 commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Google Mobile Ads SDK version 19.7.0.
Thank you @joshh-devrel! I've noticed that the issue (https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r660405918) with removing a deprecated I/F can be solved by updating the AdMob SDK to `19.8.0` or later. Change to use the latest AdMob SDK.

2021-08-31 10:56 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  /** NOTE: This method will be removed. */
This issue is solved by update AdMob SDK (see https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r699067773).

I just deleted deprecated I/Fs and flatten adapter in 3502de1c...3ed104a5. Can you review this? @joshuajplagonera @joshh-devrel

2021-08-31 10:57 UTC, S64 commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Google Mobile Ads SDK version 19.7.0.
Updated in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r699211338. Please review this.

2021-08-31 10:58 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +        MediationInterstitialAdapter,
Fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r699211338.

2021-08-31 10:58 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  static class ZucksMediationBannerAd implements MediationBannerAd {
Fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r699211338.

2021-08-31 10:58 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +class ZucksInterstitialAdapter extends BaseMediationAdapter
Fixed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r699211338.

2021-08-31 11:03 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +class ZucksBannerAdapter extends BaseMediationAdapter
Thanks @joshh-devrel, I was able to remove the unneeded codes. Suggestions you commented on were included at https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r699211338 . Can you review this?

2021-09-21 02:06 UTC, S64 commented
Hi @joshh-devrel @joshuajplagonera,
If any omissions in the work I should do, please tell me to know.

2021-10-05 18:22 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> + *   - Rewarded Ad
Nit: `Ad` can be removed.

2021-10-11 19:14 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +        MediationInterstitialAd {
The `ZucksBannerAdapter` and `ZucksInterstitialAdapter` should implement MediationBannerAd` and `MediationInterstitialAd` respectively instead.

2021-10-11 19:18 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  @Nullable private ZucksInterstitialAdapter interstitialAdapter = null;
If the `ZucksBannerAdapter` and `ZucksInterstitialAdapter` implement `MediationBannerAd` and `MediationInterstitialAd` respectively instead, we don't need these two variables anymore.

2021-10-11 19:29 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final MediationBannerAd root;
Prefer a better variable name.

2021-10-11 19:41 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +    interstitialAdapter = new ZucksInterstitialAdapter(this, mediationInterstitialAdConfiguration, mediationAdLoadCallback);
Same as above, we can just do:

`interstitialAdapter = new ZucksInterstitialAdapter(mediationInterstitialAdConfiguration, mediationAdLoadCallback)`

2021-10-11 19:44 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +          @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> mediationAdLoadCallback
If we do:
`bannerAdapter = new ZucksBannerAdapter(mediationBannerAdConfiguration, mediationAdLoadCallback);` in `ZucksAdapter`

We don't need the first parameter.

2021-10-11 19:44 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +          @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> loadCallback
Question: Is this for testing only?

2021-10-11 19:45 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +  @NonNull private final ZucksAdapter root;
Question: Why do we need this variable?

2021-10-12 08:51 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final MediationBannerAd root;
@joshh-devrel Updated in a2603ea. Can you review this?

2021-10-12 08:53 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +  @NonNull private final ZucksAdapter root;
Fixed by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r726897580 reason.

2021-10-12 08:54 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +  @Nullable private ZucksInterstitialAdapter interstitialAdapter = null;
Fixed by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r726897580 reason.

2021-10-12 09:06 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> + */
You're right. Updated in abdf6979, Can you review this?

2021-10-13 02:27 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> + */
OK, I just removed in c2ffcc4a.

2021-12-08 07:36 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private AdBanner zucksBanner = null;
I don't think we need the `@NonNull` or `@Nullable` annotations.

2021-12-08 07:44 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private final AdSize adSize;
We don't need to declare these variables for `Context` and `AdSize` explicitly, please see below for recommended code change.

2021-12-08 07:44 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  }
This can be removed.

2021-12-08 07:47 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final Bundle serverParams;
`serverParams` can be removed either. And we can have: `private MediationBannerAdConfiguration adConfiguration;` instead.

2021-12-08 07:48 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +          @NonNull MediationBannerAdConfiguration configuration,
Nit: `@NonNull MediationBannerAdConfiguration adConfiguration`

2021-12-08 07:49 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  private final MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> loadCallback;
Nit: Rename `loadCallback` to `callback`.

2021-12-08 07:49 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private MediationBannerAdCallback adCallback = null;
Nit: Rename `adCallback` to `bannerAdCallback`.

2021-12-08 07:49 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +    );
Recommended code change:
```
this.adConfiguration = adConfiguration;
this.callback = mediationAdLoadCallback;
```

2021-12-08 07:54 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  public void loadBannerAd() {
We can get the `context` and `adSize` here instead, using `adConfiguration.getContext()` and `adConfiguration.getAdSize()`respectively.

2021-12-08 08:20 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  public void loadBannerAd() {
Can get the server parameters using the following as well:
`Bundle serverParameters = adConfiguration.getServerParameters();`

2021-12-08 08:23 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
`@NonNull` and `@Nullable` annotations shouldn't be needed.

2021-12-08 08:27 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +
Should add a tag for logging in this class
```
  private static final String TAG = ZucksBannerAdapter.class.getSimpleName();
```

2021-12-08 08:27 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +class ZucksBannerAdapter implements MediationBannerAd {
Nit:`public class`

2021-12-08 08:31 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +      loadCallback.onFailure(
Prefer adding a log message:
`Log.w(TAG, <message string here>);` 

The same applies to the other places that invoke `onFailure` callback.

2021-12-08 08:36 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +    return MediationUtils.findClosestSize(context, adSize, supported) != null;
Should we check is the ad size valid or not in addition to checking if it is null?

2021-12-08 08:39 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +              }
Nit - Prefer if/return:

```
              if (error != null) {
                loadCallback.onFailure(error);
                return;
              }

              adCallback = loadCallback.onSuccess(ZucksBannerAdapter.this);
              adCallback.reportAdImpression();
              }

2021-12-08 08:41 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  }
I don't think this is invoked anywhere? If that's the case we can remove it.

2021-12-08 08:42 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +    if (adSize == null || adSize.getWidth() != banner.getWidthInDp()
Nit - prefer if/return:
```
      if (adSize == null ...) {
         return ErrorMapper...
      }
      return null;
```

2021-12-08 08:52 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +
Please apply this change in interstitial adapter as well.

2021-12-08 08:52 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private final AdSize adSize;
Please apply this change in interstitial adapter as well.

2021-12-08 08:52 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final Bundle serverParams;
Please apply this change in interstitial adapter as well.

2021-12-08 08:53 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +class ZucksInterstitialAdapter implements MediationInterstitialAd {
The comments in `ZucksBannerAdapter` also apply to the `ZucksInterstitialAdapter` class. Please take a look.

2021-12-08 08:54 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +              loadCallback.onFailure(ErrorMapper.convertSdkError(exception));
Prefer adding a log message:
`Log.w(TAG, <message string here>);`

The same applies to the other places that invoke onFailure callback.

2021-12-15 07:20 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  }
Here!
https://github.com/googleads/googleads-mobile-android-mediation/blob/b5a10682697201b99e289a31ba5048ee6be1afaa/ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java#L40-L53

2021-12-15 07:35 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +class ZucksBannerAdapter implements MediationBannerAd {
Can you tell me why better to change to the public class? This class is referenced only from the `ZucksAdapter`, I can't think any advantage of make public.

2021-12-15 07:45 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  }
As you say, annotations set on constants may be unneeded. (Returning value will be the same always.)

In the case of the method (`getFrameId`), I think nullability information is useful. Can you tell me any reason why it should be removed?

2021-12-15 08:17 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +      loadCallback.onFailure(
Changed in 822945790a38243af0b3c947b32b9b12b628a0ae, a451de27df5df8d987f70de8ebf8ab45c868e23a. Can you review these?

2021-12-15 08:17 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +              loadCallback.onFailure(ErrorMapper.convertSdkError(exception));
Changed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769363215.

2021-12-15 08:18 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +    if (adSize == null || adSize.getWidth() != banner.getWidthInDp()
Updated in c0b34bb5797e37bb3c1bfa78387d10de53c163fd!

2021-12-15 08:19 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +              }
Updated in c0423e7c3bd090487cce5ecdfe1a4056b5c37e3e 👍

2021-12-15 08:23 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  }
Changed in df750a00e66eb41dbb0a0f9bfbccfc98939f29bb. Surely, there are fewer items for unit tests than when I first submitted this PR.

2021-12-15 08:24 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private final AdSize adSize;
Changed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769367551.

2021-12-15 08:24 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final Bundle serverParams;
Changed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769367551.

2021-12-15 08:24 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +    );
Changed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769367551.

2021-12-15 08:24 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  public void loadBannerAd() {
Changed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769367551.

2021-12-15 08:29 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +          @NonNull MediationBannerAdConfiguration configuration,
Changed in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769367551.

2021-12-15 08:32 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  private final MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> loadCallback;
Changed to `adLoadCallback` in 940d4259b0bb6d7b318797a47d937b19938ac536.
`ZucksBannerAdapter` has `MediationAdLoadCallback` and `MediationBannerAdCallback`. I think it would be desirable to have distinguishable name.

2021-12-15 08:32 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private MediationBannerAdCallback adCallback = null;
Changed in 940d4259b0bb6d7b318797a47d937b19938ac536.

2021-12-15 08:47 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +
Added in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769363215. Instead of the suggested code, I wrote string constants.

- `Log.*` is not acceptable >23 tag length. In `ZucksInterstitialAdapter`, Tag length will be over to this limitation if use `getSimpleName`.
- Due to R8/ProGuard, the `getSimpleName` returning value is a little hard to predict.
  - However, these adapters will be excluded from obfuscation normally.

2021-12-15 08:50 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @Nullable private AdBanner zucksBanner = null;
Same as https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r769340877. I think it is useful if other than constants.

2021-12-15 09:03 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +    return MediationUtils.findClosestSize(context, adSize, supported) != null;
Certainly, this code is likely to be a mistake. 
Zucks's supported ad size is limited, but `MediationUtils::indClosestSize` may not fit in this limitation.

> Finds the closest supported AdSize from the list of potentials to the provided size. Returns null if none are within given threshold size range.
> 
> https://developers.google.com/android/reference/com/google/android/gms/ads/MediationUtils#findClosestSize(android.content.Context,%20com.google.android.gms.ads.AdSize,%20java.util.List%3Ccom.google.android.gms.ads.AdSize%3E)

Should I revert https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r653172841 ?

2022-03-07 20:40 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/gradlew.bat
> +@rem
Question: Why this file needs to be changed?

2022-03-07 20:41 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/gradlew
> +#!/usr/bin/env sh
Question: Why this file needs to be changed?

2022-03-07 20:41 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- **DOES NOT** supports rewarded ads. This feature will be supports in next release.
Can remove this, we just mention what we support.

2022-03-07 20:42 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Google Mobile Ads SDK version 20.3.0.
The newest version is 20.6.0, can you update the adapter to use that version?

2022-03-07 20:43 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${externalVersions.kotlin}"
The automated tests shouldn't be included in the adapter code, so the Kotlin dependencies can be removed.

2022-03-07 20:45 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/ads/mediation/zucks/ErrorMapperTest.kt
> +class ErrorMapperTest {
Would not recommend adding tests in the adapter code.

2022-03-07 20:45 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/ads/mediation/zucks/UniversalInterstitialListenerTest.kt
> +class UniversalInterstitialListenerTest {
Ditto, would not recommend adding tests in the adapter code.

2022-03-07 20:45 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/android/gms/ads/mediation/ZucksBannerAdapterTest.kt
> +class ZucksBannerAdapterTest {
Ditto, would not recommend adding tests in the adapter code.

2022-03-07 21:12 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +      com.google.ads.mediation.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
Question: Why do we need to get it from `BuildConfig`? We can just set this to `com.google.ads.mediation.zucks`.

2022-03-07 21:14 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  @NonNull public static final String SDK_DOMAIN = net.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
Question: Why do we need to get it from `BuildConfig`? We can just set this to `net.zucks.sdk`.

2022-03-07 21:21 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +      com.google.ads.mediation.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
Also, we can probably move this to `ErrorMapper.java`.

2022-03-07 21:22 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  @NonNull public static final String SDK_DOMAIN = net.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
Also, we can probably move this to `ErrorMapper.java`.

2022-03-07 21:23 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  private static final String ERROR_SDK_DOMAIN = AdMobUtil.SDK_DOMAIN;
We can just do:

```
  private static final String ERROR_ADAPTER_DOMAIN = "com.google.ads.mediation.zucks";
  private static final String ERROR_SDK_DOMAIN = "net.zucks.sdk";
```

2022-03-07 21:23 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  private static final int ADAPTER_ERROR_BASE = 100;
This can be removed. We don't need the `ADAPTER_ERROR_BASE`.

2022-03-07 21:26 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  public static final int ADAPTER_ERROR_ILLEGAL_STATE = ADAPTER_ERROR_BASE + 2;
It should be:
```
  /**
   * Server parameters, such as Frame ID, are invalid.
   */
  public static final int ERROR_INVALID_SERVER_PARAMETERS = 101;

  /**
   * The requested ad size does not match a Zucks supported banner size.
   */
  public static final int ERROR_BANNER_SIZE_MISMATCH = 102;
```

2022-03-07 21:26 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +        ADAPTER_ERROR_ILLEGAL_STATE,
This needs to be updated as per above.

2022-03-07 21:27 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  public static AdError createAdapterError(@AdapterError int code, @NonNull String msg) {
Update `code` to `errorCode`, `msg` to `errorMessage`.

2022-03-07 21:29 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/lib-proguard-rules.pro
> +# endregion
Update this to below:

```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
```

2022-03-07 21:30 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/build.gradle
> +    testImplementation "org.robolectric:robolectric:${rootProject.ext.externalVersions.robolectric}"
We shouldn't add any test in the adapter code.

2022-03-08 08:18 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/ads/mediation/zucks/ErrorMapperTest.kt
> +class ErrorMapperTest {
Removed at 736200c6. Can you tell me why not recommended?

2022-03-08 08:20 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/ads/mediation/zucks/UniversalInterstitialListenerTest.kt
> +class UniversalInterstitialListenerTest {
Resolved by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821421040.

2022-03-08 08:20 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/android/gms/ads/mediation/ZucksBannerAdapterTest.kt
> +class ZucksBannerAdapterTest {
Resolved by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821421040.

2022-03-08 08:20 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/build.gradle
> +    testImplementation "org.robolectric:robolectric:${rootProject.ext.externalVersions.robolectric}"
Resolved by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821421040.

2022-03-08 08:22 UTC, S64 commented on ThirdPartyAdapters/zucks/build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${externalVersions.kotlin}"
Resolved by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821421040. Kotlin plugin and kotlin-stdlib (it only in test builds) are removed.

2022-03-08 08:32 UTC, S64 commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- **DOES NOT** supports rewarded ads. This feature will be supports in next release.
090252e2 Removed. This line was modified in the past by your review:

- https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r690903771

Has the documentation policy changed?

2022-03-08 08:33 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/test/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapterTest.kt
> +class ZucksInterstitialAdapterTest_Robolectric {
Resolved by https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821421040.

2022-03-08 08:38 UTC, S64 commented on ThirdPartyAdapters/zucks/gradlew.bat
> +@rem
See commit message. This change occurs when updating the Gradle version.

- 67129d9a83bc0bd972b75943c4df26874c5a5f33
- 6e719546ea891497ba728db187c7df083be650e8

2022-03-08 08:38 UTC, S64 commented on ThirdPartyAdapters/zucks/gradlew
> +#!/usr/bin/env sh
Answered on https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821435477.

2022-03-08 08:54 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +      com.google.ads.mediation.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
> Why do we need to get it from `BuildConfig`?

Can you tell me why shouldn't get it from `BuildConfig`? `LIBRARY_PACKAGE_NAME` are generated by Android Gradle Plugin and it sync with `AndroidManifest.xml`. I don't think there is much benefit in spreading the definition across multiple locations.

2022-03-08 08:55 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  @NonNull public static final String SDK_DOMAIN = net.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
> Why do we need to get it from `BuildConfig`?

Commented on https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821448572.

2022-03-08 09:11 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +      com.google.ads.mediation.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
> Also, we can probably move this to `ErrorMapper.java`.

Fixed in 132503c1! This seems loose ends :bow:

- https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r658318094

2022-03-08 09:11 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  @NonNull public static final String SDK_DOMAIN = net.zucks.BuildConfig.LIBRARY_PACKAGE_NAME;
> Also, we can probably move this to `ErrorMapper.java`.

Fixed on https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821462569.

2022-03-08 09:12 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  private static final String ERROR_SDK_DOMAIN = AdMobUtil.SDK_DOMAIN;
Commented on https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821448572.

2022-03-08 09:20 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  public static AdError createAdapterError(@AdapterError int code, @NonNull String msg) {
Updated in fbcf04c8.

2022-03-08 09:58 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  public static final int ADAPTER_ERROR_ILLEGAL_STATE = ADAPTER_ERROR_BASE + 2;
Updated at 047adb0, 559100e!

2022-03-08 09:58 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  private static final int ADAPTER_ERROR_BASE = 100;
Removed https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821503453.

2022-03-08 09:59 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +        ADAPTER_ERROR_ILLEGAL_STATE,
Updated https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821503453

2022-03-08 10:09 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/lib-proguard-rules.pro
> +# endregion
`consumerProguardFiles` is useful to prevent obfuscation by the application developer side. It is necessary when the class is used by reflection.
Is it designed to be unnecessary with the AdMob SDK? This is not written yet in AdMob docs I think.

2022-03-08 10:09 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +    }
Updated https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r821503453

2022-03-08 10:12 UTC, S64 commented on ThirdPartyAdapters/zucks/CHANGELOG.md
> +- Google Mobile Ads SDK version 20.3.0.
Updated bd8fb806

2022-03-23 23:23 UTC, chrisgiglio commented
Please rebase this PR against the new `main` branch

2022-03-30 17:50 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   *     #337</a>
Can remove this.

2022-03-30 17:50 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   * Other internal errors.
Question what are the other internal errors that you are referring to?

2022-03-30 17:51 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   *     #337</a>
Can remove this.

2022-03-30 17:56 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  /** Get (this) adapter's package name. */
"Zucks adapter error domain."

2022-03-30 19:23 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +    }
Nit - Prefer below for better readability:
```
    if (e instanceof FrameIdNotFoundException) {
      return ERROR_INVALID_SERVER_PARAMETERS;
    }
    return ERROR_INTERNAL;
```

2022-03-30 19:26 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/UniversalInterstitialListener.java
> +   * For (non-fullscreen) Interstitial format.
Interstitial should be full screen?

2022-03-30 19:34 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +      extends ZucksMediationAdapter.MediationExtrasBundleBuilder {}
Question, are there existing publishers using these?

2022-03-30 19:37 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +          AdError error = isValidAdSize(banner);
We already check is the requested banner ad size valid or not in `loadBannerAd`, do we need to do it again here?

2022-03-30 19:40 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  /** Configure mediation platform flags for Banner. */
Question: Would you mind providing more clarifications on the platform flag?

2022-03-30 19:52 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +  private static boolean isFullscreenInterstitial(@Nullable Bundle mediationExtras) {
Question: In what scenario will there be non-fullscreen interstitial?

2022-03-30 20:44 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +  }
I doubt that we really need these helper methods for the success/failure callbacks.

We can just do something similar to below in the corresponding places:
```
      AdError error =
          ErrorMapper.ErrorMapper(
              ERROR_INVALID_SERVER_PARAMETERS,
              "Failed to load banner ad from Zucks. Missing or invalid Frame ID.");
      Log.w(TAG, error.toString());
      adLoadCallback.onFailure(error);
```

2022-03-30 20:47 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +    if (isFullscreenInterstitial(adConfiguration.getMediationExtras())) {
Does it mean pubs can set whether it is a full screen interstitial or not?

2022-03-30 21:03 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  private static final String TAG = "ZucksBannerAdapter";
We should only use the `ZucksMediationAdapter` tag in all places.

2022-03-30 21:04 UTC, joshh-devrel commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final MediationBannerAdConfiguration adConfiguration;
We don't really need `@NonNull` here.

2022-04-05 02:08 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  @NonNull private final MediationBannerAdConfiguration adConfiguration;
Removed e02bc834.

2022-04-05 02:13 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +  private static final String TAG = "ZucksBannerAdapter";
Replaced [25f77fa](https://github.com/googleads/googleads-mobile-android-mediation/pull/337/commits/25f77fa1efb03a86305d3ee0612bd613aee686a7).

2022-04-05 02:37 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksBannerAdapter.java
> +          AdError error = isValidAdSize(banner);
`isSizeSupported` is a method to check if the configurated size (on AdMob) is supported by the Zucks SDK.
On the other hand, `isValidAdSize` is a method to check if the size of the ad-unit acquired by the Zucks SDK matches the configured value (on AdMob).

2022-04-05 02:47 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksAdapter.java
> +      extends ZucksMediationAdapter.MediationExtrasBundleBuilder {}
Yes. Currently available adapters can only switch flags using this interface.

2022-04-05 02:50 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +    }
Updated edc8cfc9

2022-04-05 06:36 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   *     #337</a>
OK. Are these specs shown somewhere in the documentation? If not, I think it should be left as it is for future developers.

2022-04-05 06:45 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   * Other internal errors.
Here is our document:
https://ms.zucksadnetwork.com/media/sdk/manual/android/#adBanner

More specifically,

- `NetworkNotFoundException`
- `DisplaySizeTooSmallException` 
- `ParentNotFoundException`
- `AdIllegalStateException`
- `AdNetworkApiException`

will be returned as `ERROR_INTERNAL = 104`.

2022-04-05 06:46 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   *     #337</a>
commented https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r842407225

2022-04-05 06:46 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   *     #337</a>
commented https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r842407225

2022-04-05 06:46 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +   *     #337</a>
commented https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r842407225

2022-04-05 10:05 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/AdMobUtil.java
> +  /** Configure mediation platform flags for Banner. */
I just pushed 09439bce for explain this. Can you review it?

2022-04-05 10:27 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/UniversalInterstitialListener.java
> +   * For (non-fullscreen) Interstitial format.
Both of these have in common that they cover the screen. In other words, it's functionally comparable to general interstitial ads (from the user's perspective).

For historical reasons, these have separated APIs. Internally, the size of the ad creative will be different.

You can see the screenshots in the docs we provide:

- https://ms.zucksadnetwork.com/media/sdk/manual/android/#adInterstitial
- https://ms.zucksadnetwork.com/media/sdk/manual/android/#adFullscreenInterstitial

2022-04-05 10:31 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +  private static boolean isFullscreenInterstitial(@Nullable Bundle mediationExtras) {
commented in https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r842624441

This API may need to be used depending on the ad-unit type provided by Zucks.

2022-04-05 10:31 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +    if (isFullscreenInterstitial(adConfiguration.getMediationExtras())) {
commented on https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r842626955

2022-04-05 10:34 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  /** Get (this) adapter's package name. */
Updated 3449f814

2022-04-05 10:35 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/ads/mediation/zucks/ErrorMapper.java
> +  /** Get Zucks Ad Network SDK's package name (from its module). */
Updated https://github.com/googleads/googleads-mobile-android-mediation/pull/337#discussion_r842629698

2022-04-05 10:44 UTC, S64 commented on ThirdPartyAdapters/zucks/zucks/src/main/java/com/google/android/gms/ads/mediation/ZucksInterstitialAdapter.java
> +  }
Updated 22036031.

Since `notifyAdapterLoadFailure` is used from multiple places, I left it. Can you review it?

2022-04-13 10:17 UTC, S64 commented
@chrisgiglio

> Please rebase this PR against the new main branch

Is it enough to change the `base branch` of this pull request and merge the commits of the `main`?

2022-05-17 01:24 UTC, S64 commented
Hi @joshh-devrel, If you have any questions please let me know.

2022-06-14 02:06 UTC, S64 commented
Hi @joshh-devrel @chrisgiglio, If you have any questions please let me know.

2022-07-20 02:33 UTC, S64 commented
Hi @joshh-devrel @chrisgiglio, If you have any questions please let me know.

2023-09-13 05:21 UTC, joshh-devrel commented
Closed this PR since it's obsolete.

2023-09-13 05:21 UTC, closed without merging