[WIP] snap adapter
googleads/googleads-mobile-android-mediation pull request #364
Opened 2021-10-11 22:33 UTC by changlileo

2021-11-17 22:07 UTC, changlileo commented
@googlebot I signed it!

2021-11-29 23:43 UTC, joshuajplagonera requested changes

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/build.gradle
>  /**
I believe this can be removed since its already included in the project level `build.gradle` file.

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                               MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
Add nullability. Please apply to the other classes as well.

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        String bid = adConfiguration.getBidResponse();
We should add error handling just in case these are nil and/or empty?

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        mBannerView.setAdSize(SnapAdSize.BANNER);
Does snap support other Banner ad sizes?

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                        new AdError(0, "ad load fail", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Does snap provide some sort of error code/message in case of failures? I noticed that the `onEvent` does include a `String` parameter.

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>      // TODO: Initialize the ad-network's SDK and forward the success callback:
Remove TODO;

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +        appId = appIdConfig;
Does Snap only require one App ID to initialize the SDK? Can Snap initialize the SDK using multiple app IDs?

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    String versionString = BuildConfig.ADAPTER_VERSION;
This is the Adapter version, not the Snap SDK version. Does Snap have an API to fetch the current SDK version? Maybe we can leverage Snap SDK's `BuildConfig` ?

2021-11-29 23:43 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +  private SnapInterstitialAd interstitial;
nit: `interstitialAd`, to be consistent with the other ad format var names.

2021-11-30 19:25 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +    private static final String SLOT_ID_KEY = "adSlotId";
Prefer putting this constant in a centralized place, for example in `SnapMediationAdapter`.

2021-11-30 19:32 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +        }
We can probably do a null check on `mMediationAdLoadCallback` first and prefer if/return over nested ifs for better readability.

For example:
```
if (mMediationAdLoadCallback == null) {
  return;
}

if (snapAdKitEvent instanceof SnapAdLoadSucceeded) {
  mInterstitialAdCallback = mMediationAdLoadCallback.onSuccess(this);
  return;
}

if (snapAdKitEvent instanceof SnapAdLoadFailed) {
  mMediationAdLoadCallback.onFailure(
      new AdError(0, "ad load fail", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
   return;
}

...
```

2021-11-30 19:46 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +            if (mBannerView != null) {
Do we need to do the null check for the callback too?

`if (callback != null)`

2021-11-30 19:52 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        }
Prefer if/return over nested ifs for better readability:

```
        if (snapAdKitEvent instanceof SnapAdLoadSucceeded) {
            if (callback != null) {
                mBannerAdCallback = callback.onSuccess(this);
                return;
            }
        

         if (snapAdKitEvent instanceof SnapAdLoadFailed) {
            ...
            return;
         }

        ......
```

2021-11-30 19:57 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +    private final AudienceNetworkAdsApi adsNetworkApi = AdKitAudienceAdsNetwork.getAdsNetwork();
Question: Is `adsNetworkApi` only needed in interstitial and rewarded ads? I did not see it in banner ad.

2021-11-30 20:05 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +              "Initialization failed. Snap Audience AdNetwork init fail.");
Nit: "Snap Audience Network"?

2021-11-30 20:11 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +    private void handleEvent(SnapAdKitEvent snapAdKitEvent) {
Ditto. Prefer if/return over nested ifs.

2021-11-30 20:20 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                mBannerAdCallback.onAdLeftApplication();
Looking at: https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationAdCallback

Is Snap going to support these callbacks as well?
- `onAdClosed ()`
- `reportAdClicked ()`
- `reportAdImpression ()`

More on banner ad events (implemented by publishers):
https://developers.google.com/admob/android/banner#ad_events

2021-11-30 22:37 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        String bid = adConfiguration.getBidResponse();
snap ad kit handles null / empty case internally

2021-11-30 22:37 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        mBannerView.setAdSize(SnapAdSize.BANNER);
no

2021-11-30 22:40 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +        appId = appIdConfig;
no, only one app id

2021-11-30 22:40 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    String versionString = BuildConfig.ADAPTER_VERSION;
haven't expose buildconfig with version yet, will do hardcode for now

2021-11-30 22:48 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +    private final AudienceNetworkAdsApi adsNetworkApi = AdKitAudienceAdsNetwork.getAdsNetwork();
yea

2021-11-30 23:25 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                mBannerAdCallback.onAdLeftApplication();
for banner we have ad clicked, but don't have AdImpression nor AdClosed

2021-12-01 20:27 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        mBannerView.setAdSize(SnapAdSize.BANNER);
We should check is the ad size from `adConfiguration` valid or not, using the `getAdSize` method.

See: https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationBannerAdConfiguration

2021-12-02 00:52 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        mBannerView.setAdSize(SnapAdSize.BANNER);
+1
If the publisher requests for a different ad size (aka 300x250), we should return an error saying they are requesting for an unsupported ad size.

2021-12-02 00:55 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +        appId = appIdConfig;
Adapter should handle this case and log a warning saying multiple app Ids were found.

See IronSource adapter for reference: https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java#L160

2021-12-02 00:55 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    String versionString = BuildConfig.ADAPTER_VERSION;
Thank you.
Can you also add a TODO here just in case, for future reference.

2021-12-02 00:57 UTC, joshuajplagonera commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>    }
I believe `loadRtbNativeAd()` can be removed since the default implementation already throws an error if the format is not supported by the adapter.

2021-12-02 01:06 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                .withPublisherSlotId(mSlotId).withBid(bid).build();
Should the `mSlotId` be verified before passing into the method?

2021-12-02 01:08 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        String bid = adConfiguration.getBidResponse();
I would still prefer we add error handling here just in case there are changes in snap ad kit.

2021-12-02 01:12 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                                "ad load fail " + ((SnapAdLoadFailed) snapAdKitEvent).getThrowable().getMessage(),
Prefer a more descriptive message so the publisher will know it's the Snap adapter that fails to load ad: "Failed to load ad from Snap. <Reason here>."

2021-12-02 01:30 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +    public void loadAd() {
On Snap's end, would there be specific logics need to be applied if it's a refreshing banner?

2021-12-02 02:05 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +            callback.onFailure(new AdError(0, "fail to load banner ad, bid empty", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Nit, prefer the error message to be: "Failed to load banner ad from Snap due to invalid bid response."

2021-12-02 02:16 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +              "Initialization failed. Snap Audience Network init fail.");
Nit: "Snap Audience Network failed to initialize."

2021-12-02 02:24 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>    }
I believe native ad will be supported eventually and it's already configured on Google's end.

Question for Chang, is native ad not currently supported in Snap Audience Network?

2021-12-02 02:40 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +                mBannerAdCallback.onAdLeftApplication();
Looking at "Step 7.3: Listen For Events" in https://kit.snapchat.com/docs/ad-kit-android:
Banner events are: `SnapAdLoadSucceeded`, `SnapAdLoadFailed`, `SnapAdVisible`, `SnapAdClicked`, `SnapBannerAdImpressionRecorded` (this event is unique to the banner as impression).

Seems like there is one for AdImpression?

2021-12-02 02:42 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +        mSlotId = serverParameters.getString(SLOT_ID_KEY);
Ditto, we should probably add error handling for invalid `SLOT_ID_KEY`.

2021-12-02 02:43 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "fail to load interstitial ad, bid empty", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Ditto, preferred message: "Failed to load interstitial ad from Snap due to invalid bid response."

or something like "Failed to load interstitial ad from Snap. Invalid bid response."

2021-12-02 02:45 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +      signalCallbacks.onFailure(new AdError(0, "bid token generation fail", SNAP_AD_SDK_ERROR_DOMAIN));
Nit: "Failed to generate bid token."

2021-12-02 02:48 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    String versionString = "2.3.0.0";
This shouldn't be hardcoded. If this is the only option at the moment, please add a `TODO`.

2021-12-02 02:52 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +        mSlotId = serverParameters.getString(SLOT_ID_KEY);
Ditto, please add error handling for `SLOT_ID_KEY`.

2021-12-02 02:53 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "fail to load reward ad, bid empty", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Ditto, nit: "Failed to load rewarded ad from Snap due to bid response."

2021-12-02 02:54 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +                        new AdError(0, "ad load fail", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Nit: "Failed to load rewarded ad from Snap."

2021-12-02 03:02 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "snap ad network not properly initialized", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Nit: "Failed to initialize Snap Audience Network."

2021-12-02 03:03 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "snap ad network not properly initialized", SnapMediationAdapter.SNAP_AD_SDK_ERROR_DOMAIN));
Nit: "Failed to initialize Snap Audience Network."

2021-12-02 03:14 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +                                "ad load fail " + ((SnapAdLoadFailed) snapAdKitEvent).getThrowable().getMessage(),
Nit: "Failed to load interstitial ad from Snap" + ...

2021-12-02 18:36 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>    }
We don't support in snap ad kit

2021-12-02 18:36 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +    public void loadAd() {
no

2021-12-06 18:49 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        mBannerView.setAdSize(SnapAdSize.BANNER);
@changlileo Gentle bump on this.

2021-12-06 21:36 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    String versionString = BuildConfig.ADAPTER_VERSION;
Gentle bump on this.

2021-12-06 23:48 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +        appId = appIdConfig;
Gentle bump on this.

It is possible that under the same app in AdMob account, the publisher might (accidentally) use different Snap App IDs for two different AdMob ad units. We should handle this edge case as well.

2021-12-06 23:51 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load Interstitial Ad from Snap due to invalid slot id",
Nit: Lower case "interstitial ad" for consistency.

2021-12-06 23:51 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load Interstitial Ad from Snap due to invalid bid respnse",
Nit: Lower case "interstitial ad" for consistency.

2021-12-06 23:52 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load Rewarded Ad from Snap due to invalid slot id",
Nit: lower. case "rewarded ad" for consistency.

2021-12-06 23:53 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +            callback.onFailure(new AdError(0, "Failed to load banner ad from Snap due to invalid bid respnse",
Nit: "Failed to load banner ad from Snap. Invalid bid response"

2021-12-07 00:38 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load banner ad from Snap due to invalid bid respnse",
Nit: "Failed to load banner ad from Snap. Invalid bid response"

2021-12-07 00:40 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +        adsNetworkApi.playAd(new SnapAdKitSlot(mSlotId, AdKitSlotType.INTERSTITIAL));
Prefer adding validation check for context.

2021-12-07 00:40 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +    public void showAd(Context context) {
Prefer adding validation check for context.

2021-12-07 01:27 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +        adsNetworkApi.playAd(new SnapAdKitSlot(mSlotId, AdKitSlotType.INTERSTITIAL));
@joshh-devrel what validation? check null? The context is not used in this method

2021-12-07 17:36 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load interstitial Ad from Snap. Invalid Ad Slot ID",
Nit: Missing period "." at the end.

2021-12-07 17:36 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapInterstitialAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load interstitial Ad from Snap. Invalid bid response",
Nit: Missing period "." at the end.

2021-12-07 17:37 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load rewarded Ad from Snap. Invalid Ad Slot ID",
Nit: Missing period "." at the end.

2021-12-07 17:37 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +            mMediationAdLoadCallback.onFailure(new AdError(0, "Failed to load rewarded ad from Snap. Invalid bid response",
Nit: Missing period "." at the end.

2021-12-07 17:38 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    }
Looking at the iOS PR, it will come back with an error instead if there are more than one app IDs.

https://github.com/googleads/googleads-mobile-ios-mediation/pull/343/files#diff-91a67a8215fd8d93fcffdf185424953c52f3b2b5131c874b8f8b8d53d01f29a4R75-R78

2021-12-07 17:42 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>      for (MediationConfiguration adConfiguration : configurations) {
Nit: Prefer changing from `adConfiguration` to`mediationConfiguration` or `configuration`.

2021-12-07 17:43 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>                "Initialization Failed. Context is null.");
Nit: "Failed to initialize. Context is null."

2021-12-07 17:45 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
>      final NetworkInitSettings initSettings =
Discourage marking local variables as final.

2021-12-07 17:47 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +  private SnapBannerAd bannerAd;
nit: 
Better in alphabetic order so that we can easily see what ad formats are supported in this adapter:
```
  private SnapBannerAd bannerAd;
  private SnapInterstitialAd interstitialAd;
  private SnapRewardedAd rewardedAd;
```

2021-12-07 19:20 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapBannerAd.java
> +        return SnapAdSize.INVALID;
This might be blocking.
All other adapters support adaptive banner ad sizes through the use of `MediationUtils.findClosestSize()`. I believe Snap should also use this API.

A sample is here for Nend:
https://github.com/googleads/googleads-mobile-android-mediation/blob/89380f58a5cd6904d0d67a4c704ab1d50a0cc560/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NendAdapter.java#L476

2021-12-07 19:21 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    ArrayList<String> appIds = new ArrayList<>();
This should be a HashSet to avoid duplicates.

2021-12-07 19:23 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    }
We should not fail initialization if multiple App IDs are found. Rather we should just log a warning saying that multiple app IDs are found, with the list of found App IDs, as well as the App ID that will be used in initialization (the `appId` var declared above)

See:
https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java#L221-L228

2021-12-07 19:37 UTC, changlileo commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    }
@joshh-devrel doesn't your previous comment suggest to align with ios which is to fail request?

2021-12-07 19:41 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapMediationAdapter.java
> +    }
My apology. Originally I found out that it was not aligned with iOS but I realized it should log a warning instead.

2021-12-07 19:52 UTC, changlileo commented
@joshh-devrel updated for multi app ids handle and updated to use `MediationUtils.findClosestSize` to get ad size

2021-12-07 21:10 UTC, joshh-devrel commented on ThirdPartyAdapters/snap/snap/src/main/java/com/google/ads/mediation/snap/SnapRewardedAd.java
> +        if (mSlotId == null || mSlotId.isEmpty()) {
Nit: This can be simplified to `TextUtils.isEmpty(mSlotId)`

2021-12-07 23:27 UTC, merged