Adding Yahoo adapter for 1.0.1
googleads/googleads-mobile-android-mediation pull request #377
Opened 2021-12-08 20:39 UTC by nimrich

2021-12-22 20:28 UTC, joshuajplagonera requested changes

2021-12-22 20:28 UTC, joshuajplagonera commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +        Log.e(TAG, "StandardEdition.initialize must be explicitly called with an Activity" +
Should `StandardEdition.initialize` be renamed?

2021-12-22 20:28 UTC, joshuajplagonera commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +      }
If `YASAds` requires an `Activity` context to initialize the SDK, is there any reason why we are casting it to an `Application` context here?

2021-12-27 16:09 UTC, nimrich commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +      }
The actual initialize call here needs an application context.  However, this call further down:
`YASAds.getActivityStateManager().setState((Activity) context,
        ActivityStateManager.ActivityState.RESUMED);`
requires an Activity and is also needed for initialization.  

Hopefully, that makes sense!

2021-12-27 16:09 UTC, nimrich commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +        Log.e(TAG, "StandardEdition.initialize must be explicitly called with an Activity" +
Yes, good catch!

2021-12-27 16:10 UTC, nimrich commented
Addressed feedback.  Thanks!

2021-12-30 01:13 UTC, joshuajplagonera commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +  protected static boolean initializeSDK(final Context context, final String siteId) {
We might refactor this method so we may better catch the errors in this method (Context, missing Site ID, etc).

2021-12-30 01:14 UTC, joshuajplagonera commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +      }
Thank you for the explanation.
Can you add a comment here stating this behavior for future reference?

2021-12-30 01:15 UTC, joshuajplagonera commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapterUtils.java
> +  private static final String MEDIATOR_ID = "AdMobVAS-" + BuildConfig.VERSION_NAME;
Just to confirm, this `VERSION_NAME` is the Yahoo Ads version name, or the adapter version name?

2021-12-30 01:18 UTC, joshuajplagonera commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooBannerRenderer.java
> +        bannerListener.onAdFailedToLoad(adapter, AdRequest.ERROR_CODE_INVALID_REQUEST);
Adding onto the previous comment, we will update this to support the new `AdError` API.

2022-01-03 16:21 UTC, nimrich commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +      }
Added a comment regarding this.

2022-01-03 16:22 UTC, nimrich commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapterUtils.java
> +  private static final String MEDIATOR_ID = "AdMobVAS-" + BuildConfig.VERSION_NAME;
This should be the adapter version name.  I did need to correct this to, "AdMobYAS."

2022-01-03 16:23 UTC, nimrich commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooBannerRenderer.java
> +        bannerListener.onAdFailedToLoad(adapter, AdRequest.ERROR_CODE_INVALID_REQUEST);
Updated the onAdFailedToLoad calls to pass an AdError.

2022-01-03 18:00 UTC, nimrich commented on ThirdPartyAdapters/yahoo/yahoo/src/main/java/com/google/ads/mediation/yahoo/YahooAdapter.java
> +  protected static boolean initializeSDK(final Context context, final String siteId) {
We do have checks for the Context and Site ID.  Could you provide a little more detail on what you had in mind.  Much thanks!

2022-03-23 23:22 UTC, chrisgiglio commented
Please rebase this PR against the new `main` branch

2022-03-25 14:19 UTC, nimrich commented
@chrisgiglio we are actually about to release the SDK rebranded as the Yahoo Mobile SDK.  I'll reopen this PR (or create a new one) once we have completed the release.  Thanks for the help!

2022-03-25 14:19 UTC, closed without merging