Updating Vungle to 6.10.3
googleads/googleads-mobile-android-mediation pull request #380
Opened 2021-12-14 00:08 UTC by jiancchen

#### Version 6.10.3.0
- Verified compatibility with Vungle SDK 6.10.3.
- Added support for Child-Directed setting (COPPA) to be pass to the Vungle SDK via new API

Built and tested with:
- Google Mobile Ads SDK version 20.5.0.
- Vungle SDK version 6.10.3.

2021-12-16 18:57 UTC, joshuajplagonera requested changes

2021-12-16 18:57 UTC, joshuajplagonera commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +## Changelog
Please revert this file. I believe these are Vungle SDK specific changelog notes and not necessarily for the adapter.

2021-12-16 18:57 UTC, joshuajplagonera commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +    }
Please add a `default` case for readability.

2021-12-16 23:44 UTC, jiancchen commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +## Changelog
@joshuajplagonera We are trying to have a consistent release notes w/ each version. Yes, there are Vungle specific behavior changes in the logs but they apply to the adapters as well. Is there any part you guys want removed from the changelog and if there are, do you have suggestions as to what you to replace it?

2021-12-20 19:46 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +    }
Gentle bump on this.

2021-12-20 19:52 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +- SDK now supports Android [Target API 31](https://developer.android.com/sdk/api_diff/31/changes).
+1 on Joshua's previous comment to remove those that are non-adapter changes.

This changelog should only contain changes in the adapter but not the SDK. Publishers should not refer this changelog for changes in the SDK.

2021-12-22 19:11 UTC, jiancchen commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +- SDK now supports Android [Target API 31](https://developer.android.com/sdk/api_diff/31/changes).
@joshh-devrel
What would look acceptable in this case?
i.e.?
#### Version 6.10.3.0
- Verified compatibility with Vungle SDK 6.10.3.

Built and tested with:
- Google Mobile Ads SDK version 20.5.0.
- Vungle SDK version 6.10.3.

2021-12-22 20:52 UTC, joshuajplagonera commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +- SDK now supports Android [Target API 31](https://developer.android.com/sdk/api_diff/31/changes).
This looks fine to me.

2021-12-22 23:22 UTC, jiancchen commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +    }
@joshuajplagonera @joshh-devrel 

Gotcha, quick question on the behavior for COPPA:

Couldn't find guidelines, but from what I read it looks like we should:

TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED: treat as COPPA false?
default: treat as COPPA true?

Does that look correct?

2021-12-22 23:27 UTC, preethi-sannathi commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +    }
@joshuajplagonera  Please specify how Google treats TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED users. Are these users treated as Non-COPPA?

2021-12-28 17:49 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +    }
@jiancchen @preethi-sannathi 

As illustrated in [this dev doc](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationAdConfiguration#constants):
- `TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE`: indicates that the app should not be treated as child-directed for purposes of the Children’s Online Privacy Protection Act (COPPA).
- `TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE`: indicates that the app should be treated as child-directed for purposes of the Children’s Online Privacy Protection Act (COPPA).
- `TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED`: indicates that the publisher has not specified whether the app should be treated as child-directed for purposes of the Children’s Online Privacy Protection Act (COPPA).

2022-01-04 21:58 UTC, jiancchen commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +    }
@joshh-devrel 
@joshuajplagonera updated behavior thanks

2022-01-05 22:00 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +      case RequestConfiguration.TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE :
Question: Do we need to do `Vungle.updateUserCoppaStatus(false);` in this case well?

2022-01-05 22:02 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +      dismiss on their own after the specified number of seconds.
Nit: Please fix the indentation.

2022-01-05 22:09 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
> +      case RequestConfiguration.TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE :
Never-mind, it's a fall-through.

2022-01-05 22:09 UTC, joshh-devrel commented on ThirdPartyAdapters/vungle/CHANGELOG.md
> +      dismiss on their own after the specified number of seconds.
We can fix it internally.

2022-01-05 22:15 UTC, merged