New IronSource Adapter To Support Banner
googleads/googleads-mobile-android-mediation pull request #418
Opened 2022-08-09 06:45 UTC by alon357

New IronSource Adapter:
* Contains new Adapter to support IronSource Banner.
* Update IronSource Interstitial and Rewarded API that was deprecated.

2022-08-13 04:45 UTC, joshh-devrel commented
@alon357 Can you rebase your pull request and resolve the conflicts? Thanks!

2022-08-17 18:45 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/libs/PLACE_IRONSOURCE_SDK_JAR_HERE.txt
> +The jar file for the IronSource Android SDK should be placed in this directory and called 'ironsource' .
This isn't needed as publishers can define where to put the IronSouce Android SDK file.

2022-08-17 18:47 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private MediationInterstitialListener mInterstitialListener;
Can you remove the `m` prefix?

2022-08-17 18:49 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private MediationBannerListener mediationBannerListener;
Can update the variable name to `bannerListener` to be consistent to the one for interstitial?

2022-08-17 18:55 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private ISDemandOnlyBannerLayout mIronSourceBannerLayout;
Can you also remove `m` prefixes for these variables?

2022-08-17 18:57 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    }
Can you remind me again when will these callbacks be invoked?

2022-08-18 12:11 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private MediationBannerListener mediationBannerListener;
Done Thanks

2022-08-18 12:11 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private ISDemandOnlyBannerLayout mIronSourceBannerLayout;
Done Thanks

2022-08-18 12:12 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private MediationInterstitialListener mInterstitialListener;
Done Thanks

2022-09-01 18:50 UTC, joshh-devrel commented
@alon357 
Can you rebase your branch? I am still seeing `FacebookAdapter.java` in the diff.
Also, please sign the CLA.

2022-09-01 18:51 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/build.gradle
> +
Nit, remove extra lines.

2022-09-01 18:51 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/build.gradle
> +
Nit, remove extra lines.

2022-09-01 18:51 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +
Nit, remove extra lines.

2022-09-01 18:53 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  static final AdError createAdError(int errorCode, @NonNull String description) {
I don't see this method is used anywhere.

2022-09-01 18:54 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +  public static final int ERROR_INVALID_SERVER_PARAMETERS = 110;
Revert back to `101`.

2022-09-01 18:54 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    public static final int ERROR_BANNER_SIZE_MISMATCH = 101;
Update to `105`.

2022-09-01 18:58 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  public static ISBannerSize getISBannerSize(@NonNull Context context,
This is also not used anywhere, this should be called before loading the banner ad.

2022-09-04 06:32 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  static final AdError createAdError(int errorCode, @NonNull String description) {
Removed the function as it is not in use

2022-09-04 06:32 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +  public static final int ERROR_INVALID_SERVER_PARAMETERS = 110;
Fixed thanks

2022-09-04 06:32 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    public static final int ERROR_BANNER_SIZE_MISMATCH = 101;
Fixed thanks

2022-09-04 06:34 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  public static ISBannerSize getISBannerSize(@NonNull Context context,
This is used in our IronSourceAdapter class in the function requestBannerAd (line 328)
Once we create the banner layout(line 359) we set the size

2022-09-04 06:38 UTC, alon357 commented
Hey @joshh-devrel 
I have removed Facebook and the CLA says I already signed it (Are you referring to the organization CLA?)
Thanks

2022-09-07 04:46 UTC, alon357 commented
Hey @joshh-devrel 
Any update regarding the PR?

2022-09-22 23:06 UTC, joshuajplagonera requested changes
Added comments.

2022-09-22 23:06 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +              .format(ERROR_REQUIRES_ACTIVITY_CONTEXT + "IronSource requires an Activity context to load ads.");
Is this formatted properly?
I feel like this should be something like `("[%d] errorMessage", ERROR_REQUIRES_ACTIVITY_CONTEXT)`, or just without the ERROR CODE and ot should just be a string literal

2022-09-22 23:06 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +    registerISBannerAdapter(instanceId, new WeakReference(adapter));
Can you confirm if it is possible to load 2 IronSource banner ads simultaneously using the same Instance ID?

2022-10-13 06:02 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private MediationInterstitialListener InterstitialListener;
Fixed and rebased

2022-10-13 06:02 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +    IronSource.initISDemandOnly(context, appKey, IronSource.AD_UNIT.INTERSTITIAL,
IronSource require Activity Context and wont work with application Context

2022-10-13 06:03 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +              .format(ERROR_REQUIRES_ACTIVITY_CONTEXT + "IronSource requires an Activity context to load ads.");
Fixed

2022-10-13 06:04 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +    registerISBannerAdapter(instanceId, new WeakReference(adapter));
Loading the same instance twice will create a scenario of the second load will override the first load

2022-10-13 06:05 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +                    "adSize",
no as IronSource require context of activity and fail if passing application context

2022-10-13 06:51 UTC, joshh-devrel commented
@alon357 It doesn't seem like you have rebased successfully,  there are still 69 commits and 83 files changed.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/86074166/195522764-3fb4d333-4804-4513-953a-d6b251afd6b9.png">

2022-10-13 11:44 UTC, alon357 commented
Hey @joshh-devrel 
There is something weird with the rebase.
It tells me there is nothing to rebase and if I check the files that show as different from the main branch it is identical.(Although it shows diff in git)
Any advise here?

2022-10-14 05:41 UTC, closed without merging