add mintegral adapter
googleads/googleads-mobile-android-mediation pull request #420
Opened 2022-08-18 05:09 UTC by junjunsong

2022-08-19 04:36 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/.gitignore
> +/captures
This file isn't needed, can remove. We have a `.gitignore` file internally.

2022-08-19 04:36 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/build.gradle
> +        }
Can remove this.

2022-08-19 04:39 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    }
Can you revert the indentation to 2 spaces?

2022-08-19 04:39 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +     * The requested ad size does not match a mintegral supported banner size.
Nit, capitalize `Mintegral`.

2022-08-19 04:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +     * Mintegral sdk inter error
Nit, Missing "." at the end.

And what does inter mean?

2022-08-19 04:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    public static final int ERROR_SDK_INTER_ERROR = 100;
Why is this error code `100`?

2022-08-19 04:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    public static final int ERROR_CODE_NO_FILL = 104;
Can you add a java doc for this as well?

2022-08-19 04:41 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +     * Mintegral sdk load error
Nit, missing "." at the end.

2022-08-19 04:42 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    public static AdError createSdkError(int errorCode, @NonNull String errorMessage) {
Does the Mintegral SDK error has an error code as well? I only see the error message in http://cdn-adn.rayjump.com/cdn-adn/v2/markdown_v2/index.html?file=sdk-m_sdk-android&lang=en.

2022-08-19 04:43 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private MintegralRtbBannerAd mMintegralRtbBannerAd;
Remove `m` prefix.

2022-08-19 04:44 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private MintegralRtbBannerAd mMintegralRtbBannerAd;
Also add variables for interstitial, rewarded and native.

2022-08-19 04:45 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    String versionString = MBConfiguration.SDK_VERSION;
Can you give an example of how does this string look like?

2022-08-19 04:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    MintegralRtbRewardAd rtbRewardAd = new MintegralRtbRewardAd(adConfiguration, callback);
Rename the class to `MintegralRtbRewardedAd`.

2022-08-19 04:48 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +public class MintegralMediationAdapter extends RtbAdapter implements MediationAdapter {
Remove `implements MediationAdapter`, we don't need that.

2022-08-19 04:49 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +
These are from `MediationAdapter`, remove. We don't need to use that interface.

2022-08-19 04:50 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
How about the case of `TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE` and not specified? We should include them here.

2022-08-19 04:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the COPPA setting in MIntegral SDK.
Nit, `Mintegral`.

2022-08-19 04:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the GDPR setting in MIntegral SDK.
Nit, `Mintegral`.

2022-08-19 04:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the CCPA setting in MIntegral SDK.
Nit, `Mintegral`.

2022-08-19 04:53 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
Isn't that this GDPR value should be passed **before** Mintegral SDK initializes?

2022-08-19 04:53 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
Isn't that this CCPA value should be passed **before** Mintegral SDK initializes?

2022-08-19 04:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> + */
Remove this.

2022-08-19 04:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +    }
Can you explain what does this do? Why do we need this?

2022-08-19 04:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +            method.invoke(a, "Y+H6DFttYrPQYcIBicKwJQKQYrN=");
What is the `"Y+H6DFttYrPQYcIBicKwJQKQYrN="` string?

2022-08-19 06:38 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private BannerSize mBannerSize;
Nit, remove `m` prefix.

2022-08-19 06:39 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private MBBannerView mBBannerView;
Nit, prefer `mbBannerView`.

2022-08-19 06:39 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private MediationBannerAdCallback mBannerAdCallback;
Remove `m` prefix.

2022-08-19 06:42 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private static final int VALUE_0 = 0;
Do we need to declare these constants? We can just have them inline below.

For example, instead of:
`        supportedSizes.add(new AdSize(VALUE_320, VALUE_50));`
we can do:
`        supportedSizes.add(new AdSize(320, 50));`

2022-08-19 06:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +            mBannerSize = new BannerSize(BannerSize.DEV_SET_TYPE, VALUE_800, VALUE_600);
Can you clarify why if we will set these banner sizes if `mBannerSize == null`?

2022-08-19 06:47 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +            mBannerSize = new BannerSize(BannerSize.DEV_SET_TYPE, VALUE_800, VALUE_600);
We already do this check at line 82.

2022-08-19 06:48 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +        initBannerAd();
Shouldn't this be in the `load()` method?

2022-08-19 06:49 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +        if (mBBannerView == null) {
How will this be `null`?

2022-08-19 06:50 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    public void onLoadFailed(MBridgeIds mBridgeIds, String s) {
Update `s` to `errorMessage`?

2022-08-19 06:50 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +        callBackFail(ERROR_SDK_INTER_ERROR, "Failed to load Banner ad from MIntegral.");
We should use the error message provided from the callback.

2022-08-19 06:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Are these no-op? If they are, please add a `no-op` comment including the reason(s).

2022-08-19 06:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private static int dip2px(Context context, float dpValue) {
Add a comment about what this method does, and update the method name to be more descriptive.

2022-08-19 06:55 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private void callBackFail(int errorCode, String failMsg) {
Update this to: `callFailureCallback(int errorCode, String errorMessage)`. The same applies to all the `callBackFail` in the other ad formats.

2022-08-19 06:59 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    private static final String TAG = MintegralRtbInterstitialAd.class.getSimpleName();
Use the `TAG` from `MintegralMediationAdapter`.

2022-08-19 06:59 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    private  MediationAdLoadCallback<MediationInterstitialAd, MediationInterstitialAdCallback> callback;
Rename to `adLoadCallback`.

2022-08-19 07:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +        mbBidNewInterstitialHandler.setInterstitialVideoListener(this);
This should be done within `loadAd` method rather than in the constructor.

2022-08-19 07:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    public void load(){
Rename it to `loadAd`.

2022-08-19 07:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    }
Are these no-ops? If they are, please add a `no-op` comment with the reason(s).

2022-08-19 07:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +
If this is no-op, please add a `no-op` comment with reason.

For example, `// No-op, will be deprecated in the next version.`

2022-08-19 07:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    private static final String TAG = MintegralRtbRewardAd.class.getSimpleName();
Use `TAG` from `MintegralMediationAdapter`.

2022-08-19 07:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private String TAG = this.getClass().getName();
Use `TAG` from `MintegralMediationAdapter`.

2022-08-19 07:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private final MediationAdLoadCallback<UnifiedNativeAdMapper, MediationNativeAdCallback> callback;
Rename to `adLoadCallback`.

2022-08-19 07:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private Campaign mSampleAd;
Why is this sample ad? Also, remove `m` prefix.

2022-08-19 07:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +        mbBidNativeHandler = new MBBidNativeHandler(properties, mediationNativeAdConfiguration.getContext());
These should be done within `loadAd()` method instead of the constructor.

2022-08-19 07:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    public void load(){
Rename to `loadAd`.

2022-08-19 07:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +//        setStore(mSampleAd.getPackageName());
Why are these commented?

2022-08-19 07:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +        setCallToAction(mSampleAd.getAdCall());
Do we need to do `null` check or any other verifications?

2022-08-19 07:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +                1000));
Can you clarify why is this `1000`?

2022-08-19 07:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +
Nit, remove extra line.

2022-08-19 07:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +        mbBidRewardVideoHandler.setRewardVideoListener(this);
These should be done within `loadAd()` method rather than in the constructor.

2022-08-19 07:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    public void load(){
Rename to `loadAd`.

2022-08-19 07:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    }
Are these no-op? If they are, please add a no-op comment, e.g.
`// No-op, will be deprecated in the next version.`

2022-08-19 07:06 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    }
Is this no-op? If it is, please add a no-op comment, for example:
`// No-op, will be deprecated in the next version.`

2022-08-19 07:06 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +
Remove extra line.

2022-08-19 07:07 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    }
Add no-op comment, for instance:
`// No-op, will be deprecated in the next version.`

2022-08-19 07:13 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private List traversalView(View view){
Can you briefly explain what does this method do?

2022-08-24 06:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/.gitignore
> +/captures
OK. I will remove it

2022-08-24 07:06 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/build.gradle
> +        }
OK. I will remove it

2022-08-24 07:31 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +     * The requested ad size does not match a mintegral supported banner size.
ok

2022-08-24 07:51 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +     * Mintegral sdk inter error
it means the error is thrown inside the SDK

2022-08-24 07:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    public static final int ERROR_SDK_INTER_ERROR = 100;
Does 100 have any special meaning for you?  The meaning you give is similar to our meaning, so we use this

2022-08-24 07:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    public static final int ERROR_CODE_NO_FILL = 104;
yes ，I will do it

2022-08-24 07:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +     * Mintegral sdk load error
done

2022-08-24 07:59 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    public static AdError createSdkError(int errorCode, @NonNull String errorMessage) {
We have no error codes. This is the way we refer to Pangle

2022-08-24 08:05 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private MintegralRtbBannerAd mMintegralRtbBannerAd;
done

2022-08-24 08:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    String versionString = MBConfiguration.SDK_VERSION;
it like this MAL_16.2.11

2022-08-24 08:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    MintegralRtbRewardAd rtbRewardAd = new MintegralRtbRewardAd(adConfiguration, callback);
done

2022-08-24 08:18 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +public class MintegralMediationAdapter extends RtbAdapter implements MediationAdapter {
We want to destroy the banner ad when the page exits. What should we do if we do not use the mediationadapter?

2022-08-24 08:20 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +
We want to destroy the banner ad when the page exits. What should we do if we do not use the mediationadapter?

2022-08-24 08:33 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
RequestConfiguration.TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE means we will don't track user info;
TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE and not specified mean we will track user info

2022-08-24 08:34 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the COPPA setting in MIntegral SDK.
done

2022-08-24 08:35 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the GDPR setting in MIntegral SDK.
done

2022-08-24 08:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the CCPA setting in MIntegral SDK.
done

2022-08-24 08:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> + */
done

2022-08-24 08:38 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +    }
This method is mainly used to mark the request brought by the three-party parter

2022-08-24 08:38 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +            method.invoke(a, "Y+H6DFttYrPQYcIBicKwJQKQYrN=");
Partner's tag

2022-08-24 08:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +            method.invoke(a, "Y+H6DFttYrPQYcIBicKwJQKQYrN=");
String that marks the partner

2022-08-24 08:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private MBBannerView mBBannerView;
rename var name

2022-08-24 09:24 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    private static final String TAG = MintegralRtbInterstitialAd.class.getSimpleName();
done

2022-08-24 09:25 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    private  MediationAdLoadCallback<MediationInterstitialAd, MediationInterstitialAdCallback> callback;
done

2022-08-24 09:28 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +        mbBidNewInterstitialHandler.setInterstitialVideoListener(this);
done

2022-08-24 09:28 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    public void load(){
done

2022-08-24 09:33 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    }
done

2022-08-24 09:33 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +
done

2022-08-24 09:35 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    private static final String TAG = MintegralRtbRewardAd.class.getSimpleName();
done

2022-08-24 09:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +        mbBidRewardVideoHandler.setRewardVideoListener(this);
done

2022-08-24 09:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    public void load(){
done

2022-08-24 09:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    }
done

2022-08-24 09:37 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardAd.java
> +    }
done

2022-08-24 09:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private String TAG = this.getClass().getName();
done

2022-08-24 09:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private final MediationAdLoadCallback<UnifiedNativeAdMapper, MediationNativeAdCallback> callback;
done

2022-08-24 09:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private Campaign mSampleAd;
done

2022-08-24 09:57 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +        mbBidNativeHandler = new MBBidNativeHandler(properties, mediationNativeAdConfiguration.getContext());
done

2022-08-24 09:57 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    public void load(){
done

2022-08-24 10:29 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +        setCallToAction(mSampleAd.getAdCall());
The list has been checked in the onadloaded method. If there is data in the list, the campaign will not be null

2022-08-24 10:30 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +                1000));
I will change it to 1.0

2022-08-24 10:33 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +
done

2022-08-29 21:57 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final String PANGLE_SDK_ERROR_DOMAIN = "com.mintegral.ads";
Should be `MINTEGRAL_SDK_ERROR_DOMAIN`.

2022-08-29 22:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final int ERROR_SDK_INTER_ERROR = 100;
Update this to below and move it above error `101`.

```
  /**
   * The Mintegral SDK returned a failure callback.
   */
  public static final int ERROR_MINTEGRAL_SDK = 100;
```

2022-08-29 22:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final int ERROR_SDK_ADAPTER_ERROR = 105;
Can remove this, we can just use the `createAdapterError` method below for adapter error.

2022-08-29 22:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static AdError createSdkError(int errorCode, @NonNull String errorMessage) {
Revert, the input is just the string message.

2022-08-29 22:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    return new AdError(errorCode, errorMessage, PANGLE_SDK_ERROR_DOMAIN);
Instead of using `errorCode`, it can just be `ERROR_MINTEGRAL_SDK` instead.

2022-08-29 22:13 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +public class MintegralMediationAdapter extends RtbAdapter implements MediationAdapter {
We currently do not support `onDestroyed()` callback in the mediation adapter interface and there isn't any substitute option at the moment.

There is `onDestroy` method in the deprecated `MediationAdapter` class, but we should use the latest classes like `RtbAdapter` and `MediationBannerAd` for bidding.

To help prevent memory leak issue, we would recommend Mintegral SDK not to keep any strong static reference with the adapter. We can also implement additional logics in the adapter to handle the garbage collection but it will certainly increase the complexity of the code.

Adding the `onDestroy` or equivalent method is still under consideration. It won't be in production anytime soon even if the request is approved.

2022-08-29 22:14 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean allowGDPR = true;
Why are these `false` and `true` by default?

2022-08-29 22:18 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    String versionString = MBConfiguration.SDK_VERSION;
Can you add this comment?
```
// Example of SDK_VERSION string: MAL_16.2.11.
```

2022-08-29 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      });
The implementation here isn't correct, and this should be outside the for-loop.

See Pangle's implementation as an example: https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/PangleMediationAdapter.java#L66-L107.

2022-08-29 22:31 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      }
We should do the validations after going through the for-loop that add all the app ID and app keys into the hash sets. (There should be two because we have two keys here)

Let's say the publishers enter multiple App IDs and App Keys in the AdMob UI for different ad units, how should the Mintegral SDK handle it? Can we just randomly pick a pair?
(Note: The app key is account level and app ID is app level)

2022-08-29 22:32 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  public void load() {
Rename this to `loadAd()`.

2022-08-29 22:34 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean noTrackUser = false;
What does `noTrackUser` here mean? Is this for CCPA or COPPA?

2022-08-29 22:34 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    mintegralRtbBannerAd.load();
Rename the method to `loadAd()`.

2022-08-29 22:35 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
Remove these as we should no longer implement `MediationAdapter`.

2022-08-29 22:43 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param coppa Whether the user is allowed to track user information, {@link RequestConfiguration#TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE } does not track, other is to track
--- BLOCKING ---

If publisher does not set the `setTagForChildDirectedTreatment ` method or set it to `TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED`, it means there is no indication of how publishers would like their app treated with respect to COPPA. **We SHOULD NOT assume the app should be treated as child-directed for purposes of COPPA or not.**

See: https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration.Builder#public-requestconfiguration.builder-settagforchilddirectedtreatment-int-tagforchilddirectedtreatment

2022-08-29 22:45 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param coppa Whether the user is allowed to track user information, {@link RequestConfiguration#TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE } does not track, other is to track
Can you clarify why this is for "track user information"? COPPA is different from CCPA.

2022-08-29 22:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setCcpa(boolean ccpa) {
We should follow what's in the Mintegral SDK:

```
  /**
   * Set the CCPA setting in Mintegral SDK.
   *
   * @param status a {@code boolean} value that indicates whether the user has opted-out of the 
   *     "sale" of the "personal information" under CCPA. See <a
   *     href="https://dev.mintegral.com/doc/index.html?file=sdk-m_sdk-android&lang=en">Mintegral's
   *     documentation</a> for more information about what values may be provided.
   */
  public static void setDoNotTrackStatus(boolean status) {
  ...
  }
```

2022-08-29 23:01 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
We should follow what's in the Mintegral SDK, for example:

```
  /**
   * Set the GDPR setting in Mintegral SDK.
   *
   * @param context the context object
   * @param gdpr an {@code Integer} value that.... See <a
   *     href="https://dev.mintegral.com/doc/index.html?file=sdk-m_sdk-android&lang=en">Mintegral's
   *     documentation</a> for more information about what values may be provided.
   */
  public static setConsentStatus(Context context, int status) {
    ...
  }

```

Note that the above code doesn't contain all the information in the java doc comment.

2022-08-29 23:06 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
I don't think we should make an assumption that "not specified" = track.

This is COPPA not CCPA, I think the terms "track user info" is confusing. We should say "indicates whether the app should be treated as child-directed for purposes of the COPPA" instead.

Also can you clarify why the COPPA and CCPA are using the same API?

Reference: https://dev.mintegral.com/doc/index.html?file=sdk-m_sdk-android&lang=en

2022-08-29 23:07 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +  public static void addChannel() {
Can you add a Javadoc for this method?

2022-08-29 23:08 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +      method.invoke(a, "Y+H6DFttYrPQYcIBicKwJQKQYrN=");
Add a comment of what this does.

2022-08-30 04:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralUtils.java
> +}
We shouldn't need this class, can add the corresponding method in the extras builder class.

2022-08-30 04:10 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralExtras.java
> +}
Can you rename this class to `MintegralExtrasBuilder`? We can have an implementation like below:
```
public final class MintegralExtrasBuilder {
  public static final String MUTE_AUDIO = "mute_audio";
  private String muteAudio;

  @NonNull
  public MintegralExtrasBuilder setMuteAudio(boolean muteAudio) {
    this.muteAudio = muteAudio;
    return this;
  }

  @NonNull
  public Bundle build() {
    Bundle bundle = new Bundle();
    bundle.putString(MUTE_AUDIO, muteAudio);
    return bundle;
  }
}
```

Sample publisher's implementation:
```
        Bundle mintegralExtras = new MintegralExtrasBuilder()
            .setMuteAudio(true))
            .build();
        AdRequest adRequest = new AdRequest.Builder().addNetworkExtrasBundle(MintegralMediationAdapter.class, mintegralExtras).build();
```

2022-08-30 04:11 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  private static int dipToPixels(Context context, float dpValue) {
Shouldn't the method name be `convertDpToPixels`?

2022-08-30 04:21 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Remove these checks, they aren't needed since `adConfiguration`, `adConfiguration.getServerParameters()` and `adConfiguration.getContext()` are all `NonNull`.

2022-08-30 04:22 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    String unitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
Rename to `adUnitId`.

2022-08-30 04:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
This can be a local variable below, also rename it to `layoutParams`.

2022-08-30 04:25 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    private BannerSize mBannerSize;
Makes sense, please keep it for `mbBannerView`.

2022-08-30 04:27 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.setLayoutParams(params);
We don't need this `initBannerAd` method, can just move all these lines to the `loadAd()` method below.

2022-08-30 04:27 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Remove this check, `adConfiguration` is `NonNull`.

2022-08-30 04:33 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    String unitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
Nit, rename this to `adUnitId`.

2022-08-30 04:36 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +  private static final String TAG = MintegralMediationAdapter.class.getSimpleName();
You can import it instead:
```
import static com.google.ads.mediation.mintegral.MintegralMediationAdapter.TAG;
```

2022-08-30 04:36 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  private final String TAG = MintegralMediationAdapter.class.getSimpleName();
You should import it above instead:
```
import static com.google.ads.mediation.mintegral.MintegralMediationAdapter.TAG;
```

2022-08-30 04:37 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +  private static final String TAG = MintegralMediationAdapter.class.getSimpleName();
You should import it instead:
```
import static com.google.ads.mediation.mintegral.MintegralMediationAdapter.TAG;
```

2022-08-30 04:37 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +
```
import static com.google.ads.mediation.mintegral.MintegralMediationAdapter.TAG;
```

And add loggings before failure callbacks.

2022-08-30 04:39 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private final double mScale;
Remove `m` prefix.

2022-08-30 07:17 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +   */
Can you update the Javadoc comment as in https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinUtils.java#L64-L70?

2022-08-30 07:20 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Can you add a comment about why we set to `BannerSize.DEV_SET_TYPE` if `closestSize` doesn't match any of the above `AdSize`s?

2022-08-30 07:22 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    params.width = dipToPixels(adConfiguration.getContext(), bannerSize.getWidth());
Rename to `layoutParams`, as in another comment. Also this can be a local variable, unless there is a reason to have it as a class variable.

2022-08-30 07:26 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Does Mintegral SDK check whether the token is valid or not? If Mintegral SDK checks it and returns a failure callback, we can remove this check.

2022-08-30 07:29 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    callFailureCallback(MintegralConstants.ERROR_SDK_INTER_ERROR, errorMessage);
Update to:
```
    if (adLoadCallback != null) {
      AdError error = MintegralConstants. createSdkError(errorMessage);
      adLoadCallback.onFailure(error);
    }
```

2022-08-30 17:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +public class AdapterTools {
We don't need to create a new class for the `addChannel` method, can just include it in `MintegralMediationAdapter` since it's the only place using it.

2022-08-30 17:42 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Shouldn't we just return a failure callback if the closest size doesn't match `BANNER`, `MEDIUM_RECTANGLE` and `LEADERBOARD`?

2022-08-30 17:44 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    updateSupportBannerSize();
We can just move the implementation in `updateSupportBannerSize()` to here so we don't need an additional method for it, this is the only place that does that check.

Then we don't need the `bannerSize` class variable, unless we need to keep a reference to it.

2022-08-30 17:45 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    initBannerAd();
Move all implementation of `initBannerAd()` and `updateSupportBannerSize` to here.

2022-08-30 17:47 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  private BannerSize bannerSize;
This can be a local variable after we move all the implementation of `updateSupportBannerSize()` and `initBannerAd()` to `loadAd()`.

2022-08-30 17:50 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +      bannerSize = new BannerSize(BannerSize.STANDARD_TYPE, 0, 0);
Just want to confirm if the `0, 0` for the last two inputs are correct.

Reference from Mintegral developer documentation:
```
public BannerSize(int sizeType,int showWidth,int showHeight);
```

2022-08-30 19:56 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
Can do a `switch` statement instead.

2022-08-30 20:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
I would assume we can invoke `bannerAdCallback.onAdOpened();` here.

2022-08-30 20:01 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
I would assume we can invoke `bannerAdCallback.onAdClosed();` here.

2022-08-30 20:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  public void onCloseBanner(MBridgeIds mBridgeIds) {
When will this be invoked?

2022-08-30 20:17 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +      callFailureCallback(MintegralConstants.ERROR_BANNER_SIZE_MISMATCH, "Failed to request banner ad from Mintegral. Invalid banner size.");
This is a publisher's implementation issue, update to:

```
      AdError error =
          MintegralConstants.createAdapterError(
              ERROR_BANNER_SIZE_MISMATCH,
              "Failed to request banner ad from Mintegral. Invalid banner size.");
      Log.w(TAG, error.toString());
      adLoadCallback.onFailure(error);
```

2022-08-30 20:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  }
We don't need this method as `adLoadCallback` is `NonNull`.

2022-08-30 20:33 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +   */
Nit, can remove this comment.

2022-08-30 20:38 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +   */
Nit, can remove this comment.

2022-08-30 20:39 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +   */
Nit, can remove this comment.

2022-08-30 20:41 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    boolean muted = MintegralUtils.shouldMuteAudio(adConfiguration.getMediationExtras());
After updating the `MintegralExtrasBuilder` class (see above), can do the below:
```
    boolean muteAudio = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
```

2022-08-30 20:42 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    boolean muted = MintegralUtils.shouldMuteAudio(adConfiguration.getMediationExtras());
After updating the `MintegralExtrasBuilder` class (see above), can do the below:
```
    boolean muteAudio = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
```

2022-08-30 20:50 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    setStore(campaign.getPackageName());
To confirm, will any of these assets be `null`?

2022-08-30 20:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +            1.0));
Can you remind me again what does `1.0` here mean?

2022-08-30 20:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    setOverrideImpressionRecording(false);
Can remove this.

2022-08-30 20:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  }
Can remove this.

2022-08-30 20:53 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  }
Can remove these two.

2022-08-30 20:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    super.untrackView(view);
Does Mintegral have a method to untrack view?

2022-08-30 20:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  private List traversalView(View view) {
Can you add a javadoc about what this does?

2022-08-30 20:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    //No-op, the method is deprecated
Nit, `// No-op, this method is deprecated.`

2022-08-30 21:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +          amount = Integer.getInteger(rewardInfo.getRewardAmount());
In what condition this will fail? Doesn't Mintegral SDK handle it internally?

2022-08-30 21:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +  public void onShowFail(MBridgeIds mBridgeIds, String s) {
Is `s` the error message? Can rename it to `errorMessage`.

2022-08-30 21:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +  public void onVideoLoadFail(MBridgeIds mBridgeIds, String s) {
Rename `s` to `errorMessage`.

2022-09-01 06:27 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +   */
ok

2022-09-01 06:27 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +   */
ok

2022-09-01 06:27 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    String unitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
ok

2022-09-01 06:27 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +   */
ok

2022-09-01 06:27 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +   */
ok

2022-09-01 06:38 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final int ERROR_SDK_INTER_ERROR = 100;
ok

2022-09-01 06:54 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final int ERROR_SDK_ADAPTER_ERROR = 105;
ok

2022-09-01 06:54 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static AdError createSdkError(int errorCode, @NonNull String errorMessage) {
ok

2022-09-01 06:55 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +    return new AdError(errorCode, errorMessage, PANGLE_SDK_ERROR_DOMAIN);
ok

2022-09-01 08:22 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean allowGDPR = true;
I'll modify it

2022-09-01 08:23 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    String versionString = MBConfiguration.SDK_VERSION;
ok

2022-09-01 10:21 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      });
ok

2022-09-01 10:27 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      }
we will only pick the first pair

2022-09-01 10:28 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean noTrackUser = false;
it means CCPA

2022-09-01 11:33 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    String unitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
done

2022-09-01 11:33 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +  private static final String TAG = MintegralMediationAdapter.class.getSimpleName();
done

2022-09-01 11:34 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  private final String TAG = MintegralMediationAdapter.class.getSimpleName();
done

2022-09-01 11:34 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +  private static final String TAG = MintegralMediationAdapter.class.getSimpleName();
done

2022-09-01 11:36 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    private final double mScale;
done

2022-09-01 11:36 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +public class AdapterTools {
done

2022-09-01 11:37 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +   */
done

2022-09-01 11:37 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    String unitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
done

2022-09-01 11:40 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +  public void onVideoLoadFail(MBridgeIds mBridgeIds, String s) {
done

2022-09-01 11:40 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +  public void onShowFail(MBridgeIds mBridgeIds, String s) {
done

2022-09-01 11:43 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +          amount = Integer.getInteger(rewardInfo.getRewardAmount());
It is mainly to avoid cast exceptions. It is a string in the mintegral SDK

2022-09-01 11:44 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    //No-op, the method is deprecated
done

2022-09-01 11:53 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  private List traversalView(View view) {
done

2022-09-01 11:54 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    super.untrackView(view);
I had add a method to untrack

2022-09-01 11:55 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  }
done

2022-09-01 11:56 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    setOverrideImpressionRecording(false);
done

2022-09-01 12:02 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    setOverrideImpressionRecording(false);
I refer to Pangle's code. It looks like his code is similar

2022-09-01 12:04 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    setOverrideImpressionRecording(false);
do you want me to delete setoverrideimpressionrecording (false);  ?

2022-09-01 12:07 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +            1.0));
I refer to Pangle's code. 
As long as it can meet your requirements, mintegral has no requirements for pictures

2022-09-01 12:11 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    setStore(campaign.getPackageName());
I will modify it

2022-09-01 12:11 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    boolean muted = MintegralUtils.shouldMuteAudio(adConfiguration.getMediationExtras());
done

2022-09-01 12:12 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    boolean muted = MintegralUtils.shouldMuteAudio(adConfiguration.getMediationExtras());
done

2022-09-01 12:12 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +   */
done

2022-09-01 12:18 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param coppa Whether the user is allowed to track user information, {@link RequestConfiguration#TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE } does not track, other is to track
Coppa will be set in the portal of mintegral

2022-09-01 12:18 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param coppa Whether the user is allowed to track user information, {@link RequestConfiguration#TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE } does not track, other is to track
CCPA

2022-09-01 12:21 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setCcpa(boolean ccpa) {
ok

2022-09-01 12:21 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
I will add doc

2022-09-01 12:23 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +  public static void addChannel() {
done

2022-09-01 12:35 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +      method.invoke(a, "Y+H6DFttYrPQYcIBicKwJQKQYrN=");
done

2022-09-01 12:38 UTC, Mintegral-official commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralExtras.java
> +}
done

2022-09-01 19:42 UTC, joshh-devrel commented
@junjunsong @Mintegral-official 
I saw you replied to my comments but I did see a new commit, can you double check on whether the new commit is pushed?

2022-09-02 02:00 UTC, junjunsong commented
> 



> @junjunsong @Mintegral-official I saw you replied to my comments but I didn't see a new commit, can you double check on whether the new commit is pushed?

I am sorry. I have just submitted a part, and another part will be processed today

2022-09-02 05:51 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +public class MintegralMediationAdapter extends RtbAdapter implements MediationAdapter {
done

2022-09-02 05:52 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +
I had removed it

2022-09-02 05:53 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  public void load() {
done

2022-09-02 05:54 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    mintegralRtbBannerAd.load();
done

2022-09-02 05:54 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
done

2022-09-02 05:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralUtils.java
> +}
done

2022-09-02 05:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  private static int dipToPixels(Context context, float dpValue) {
done

2022-09-02 05:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
done

2022-09-02 05:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    String unitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
done

2022-09-02 05:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
done

2022-09-02 05:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.setLayoutParams(params);
done

2022-09-02 05:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
done

2022-09-02 05:58 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +   */
done

2022-09-02 05:59 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
There is no best match, we support developers, set custom width and height

2022-09-02 06:01 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    params.width = dipToPixels(adConfiguration.getContext(), bannerSize.getWidth());
done

2022-09-02 06:03 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
There is no such check callback provided inside Mintegral SDK

2022-09-02 06:39 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    callFailureCallback(MintegralConstants.ERROR_SDK_INTER_ERROR, errorMessage);
done

2022-09-02 06:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    if (mbBannerView == null) {
done

2022-09-02 06:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    updateSupportBannerSize();
done

2022-09-02 06:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    initBannerAd();
done

2022-09-02 06:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  private BannerSize bannerSize;
done

2022-09-02 06:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +      bannerSize = new BannerSize(BannerSize.STANDARD_TYPE, 0, 0);
Mintegral SDK will process different types internally, there is no exception to this logic

2022-09-02 06:47 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
showFullScreen means mraid ad is expanded

2022-09-02 06:54 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
closeFullScreen  means mraid ad was collapsed

2022-09-02 06:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  public void onCloseBanner(MBridgeIds mBridgeIds) {
developer can set it in portal of Mintegral

2022-09-02 06:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +      callFailureCallback(MintegralConstants.ERROR_BANNER_SIZE_MISMATCH, "Failed to request banner ad from Mintegral. Invalid banner size.");
done

2022-09-02 06:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +  }
done

2022-09-02 07:30 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +
done

2022-09-02 07:31 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    }
AdSize is a custom object, how to use switch to achieve it, if it must be changed, can you give a simple example of the change

2022-09-03 07:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final int ERROR_SDK_INTER_ERROR = 100;
Can you revert back to below:
```
  /**
   * The Mintegral SDK returned a failure callback.
   */
  public static final int ERROR_MINTEGRAL_SDK = 100;
```

2022-09-03 07:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             value outside of -1, 0, or 1 will result in this method being a no-op.
Remove this:
```
{@code 0} means the user consents. {@code 1}
   *             means the user does not consent. {@code -1} means the user hasn't specified. Any
   *             value outside of -1, 0, or 1 will result in this method being a no-op.
```

The publisher should just refer to Mintegral documentation for what values may be provded.

2022-09-03 07:07 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setGdpr(int gdpr) {
Should match the method Mintegral SDK provides, which is `setConsentStatus` I believe?

2022-09-03 07:08 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      //call private static method "b"
What is `private static method "b"`? We don't need to include this detail here, but just a high level comment above.

2022-09-03 07:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             outside of -1, 0, or 1 will result in this method being a no-op.See <a
Remove the following:
```
{@code 0} means the user opts in. {@code 1}
   *             means the user opts out. {@code -1} means the user hasn't specified. Any value
   *             outside of -1, 0, or 1 will result in this method being a no-op.
```
The publisher should just refer to Mintegral documentation for what values may be provded.

2022-09-03 07:11 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setCcpa(int ccpa) {
Should match the method in Mintegral SDK, which is `setDoNotTrackStatus` I believe.

2022-09-03 07:13 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
The CCPA and GDPR values should match what are in the Mintegral SDKs, which are `boolean status` and `int status` (from MBridgeConstans) respectively.

2022-09-03 07:17 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +}
You already added `addChannel()` in `MintegralMediationAdapter`, this file shouldn't be needed anymore.

2022-09-03 07:27 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final String MINTEGRAL_SDK_ERROR_DOMAIN = "com.mintegral.ads";
Looking at the dependencies in `build.gradle`, shouldn't it be `com.mbridge.msdk`?

2022-09-03 07:27 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +                  ERROR_SDK_INTER_ERROR,
`ERROR_MINTEGRAL_SDK`

2022-09-03 07:32 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static int GDPRValue = -1;
The variable types should match what are in the Mintegral SDK, can update them to:
```
private static gdprConsentStatus
```
and
```
private static ccpaDoNotTrackStatus 
```

2022-09-03 08:07 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +
Nit, remove extra space.

2022-09-03 08:08 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +          callback;
Nit, can you rename this to `adLoadCallback`?

2022-09-03 08:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +      this.drawable = mDrawable;
This isn't used anywhere, can be removed?

2022-09-03 08:10 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  public void onAdLoadError(String s) {
Nit, rename `s` to `errorMessage`.

2022-09-03 08:12 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    super.trackViews(view, map, map1);
Is this still needed?

2022-09-03 08:12 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    super.untrackView(view);
Ditto, is this still needed?

2022-09-05 19:10 UTC, joshuajplagonera requested changes

2022-09-05 19:10 UTC, joshuajplagonera commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    String placementId = adConfiguration.getServerParameters().getString(MintegralConstants.PLACEMENT_ID);
If mintegral requires both of these parameters, we should add error handling in the case either of these are invalid.

2022-09-05 19:10 UTC, joshuajplagonera commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    adLoadCallback.onFailure(MintegralConstants.createSdkError(errorMessage));
nit: log the error message under warning

2022-09-06 02:24 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final int ERROR_SDK_INTER_ERROR = 100;
done

2022-09-06 02:53 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             value outside of -1, 0, or 1 will result in this method being a no-op.
I will modify it according to the requirements of mintegral SDK

2022-09-06 03:25 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setGdpr(int gdpr) {
ok

2022-09-06 03:54 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      //call private static method "b"
I will remove the comments

2022-09-06 05:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             outside of -1, 0, or 1 will result in this method being a no-op.See <a
In mintegral SDK
It is set using true or false. If it is set by the developer, I can't make clear the real intention of the developer during initialization. I will keep it

2022-09-06 06:07 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setCcpa(int ccpa) {
In mintegral SDK
It is set using true or false. If it is set by the developer, I can't make clear the real intention of the developer during initialization. I will keep it

2022-09-06 06:07 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
In mintegral SDK
It is set using true or false. If it is set by the developer, I can't make clear the real intention of the developer during initialization. I will keep it

2022-09-06 06:12 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/AdapterTools.java
> +}
done

2022-09-06 06:26 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +  public static final String MINTEGRAL_SDK_ERROR_DOMAIN = "com.mintegral.ads";
mbridge is our packagename ,but network name is mintegral.is it ok ?

2022-09-06 06:27 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +                  ERROR_SDK_INTER_ERROR,
done

2022-09-06 06:28 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static int GDPRValue = -1;
done

2022-09-06 06:29 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +
done

2022-09-06 06:30 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +          callback;
ok

2022-09-06 06:32 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +      this.drawable = mDrawable;
ok

2022-09-06 06:32 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +  public void onAdLoadError(String s) {
done

2022-09-06 06:43 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    super.trackViews(view, map, map1);
removed

2022-09-06 06:44 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +    super.untrackView(view);
removed

2022-09-06 06:53 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      public void onInitFail(String s) {
done

2022-09-06 08:05 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    adLoadCallback.onFailure(MintegralConstants.createSdkError(errorMessage));
done

2022-09-06 08:28 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +    String placementId = adConfiguration.getServerParameters().getString(MintegralConstants.PLACEMENT_ID);
Adunitid is required and placementid is optional

2022-09-06 22:11 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +
Do we need these? Can't we just get the constants from the Mintegral SDK?

2022-09-06 22:13 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             value outside of 0 or 1 will result in this method being a no-op.
Remove this, publishers should refer to Mintegral documentation about what values may be provided.

2022-09-06 22:15 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             outside of 0 or 1 will result in this method being a no-op.See <a
Remove this, publishers should refer to Mintegral documentation about what values may be provided. So it should become:

```
   * @param ccpa an {@code Integer} value that indicates whether the user opts in of the "sale" of
   *             the "personal information" under CCPA. See <a href="https://dev.mintegral.com/doc/index.html?file=sdk-m_sdk-android&lang=en">Mintegral's
   *             documentation</a> for more information about what values may be provided.
   */
```

Please format accordingly.

2022-09-06 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +package com.mintegral.mediation.rtb;
Should be in
```
package com.google.ads.mediation.mintegral.rtb;
```

2022-09-06 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +package com.mintegral.mediation.rtb;
Should be in
```
package com.google.ads.mediation.mintegral.rtb;
```

2022-09-06 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +package com.mintegral.mediation.rtb;
Should be in
```
package com.google.ads.mediation.mintegral.rtb;
```

2022-09-06 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +package com.mintegral.mediation.rtb;
Should be in
```
package com.google.ads.mediation.mintegral.rtb;
```

2022-09-06 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralExtrasBuilder.java
> +package com.mintegral.mediation;
Should be in
```
package com.google.ads.mediation.mintegral;
```

2022-09-06 22:36 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setGdpr(@MintegralConstants.MBridgeConstants int gdpr) {
Can remove `@MintegralConstants.MBridgeConstants`.

2022-09-06 22:36 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setGdpr(@MintegralConstants.MBridgeConstants int gdpr) {
Rename to `setConsentStatus` that matches the Mintegral SDK.

2022-09-06 22:42 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (gdpr != 0 && gdpr != 1) {
Update to:
```
    if (consentStatus != MBridgeConstans.IS_SWITCH_OFF && consentStatus != MBridgeConstans.IS_SWITCH_ON) {
```

2022-09-06 22:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setCcpa(@MintegralConstants.MBridgeConstants int ccpa) {
Update to below:
```
public static void setDoNotTrackStatus(boolean doNotTrackStatus)
```

2022-09-06 22:47 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param ccpa an {@code Integer} value that indicates whether the user opts in of the "sale" of
Shouldn't it be a boolean value?

2022-09-06 22:48 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static int ccpaDoNotTrackStatus = -1;
Should be `boolean`?

2022-09-06 22:49 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
Nit, prefer moving these lines to the end of the file before `addChannel`.

2022-09-06 23:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param gdpr an {@code Integer} value that indicates whether the user consents the use of
Should be `@param consentStatus`.

2022-09-06 23:08 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralExtrasBuilder.java
> +}
Sorry, can you update to below instead using the builder pattern?

```
public final class MintegralExtras {
 static class Keys {
    static final String MUTE_AUDIO = "mute_audio";
  }

  public static class Builder {
    private boolean muteAudio;

    @NonNull
    public Builder setMuteAudio(boolean muteAudio) {
      this.muteAudio = muteAudio;
      return this;
    }

    @NonNull
    public Bundle build() {
      Bundle extras = new Bundle();
      extras.putBoolean(MUTE_AUDIO, muteAudio);
      return extras;
    }
  }
}
```

2022-09-06 23:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
Update to `MintegralExtras.Keys.MUTE_AUDIO`.

2022-09-06 23:12 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
We should check if the extras is null and if it contains the key before we set it.

2022-09-06 23:12 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
We should check if the extras is null and if it contains the key before we set it.

2022-09-06 23:12 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
Update to `MintegralExtras.Keys.MUTE_AUDIO`.

2022-09-07 07:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
@junjunsong @Mintegral-official 

Actually do we need these two methods? According to [Mintegral documentation](https://dev.mintegral.com/doc/index.html?file=sdk-m_sdk-android&lang=en), publishers can just do the below:

```
// Set GDPR consent status before Mintegral SDK initializes.
MBridgeSDK sdk = MBridgeSDKFactory.getMBridgeSDK();
Map<String, String> map = sdk.getMBConfigurationMap("your appId", "your appKey");
sdk.setConsentStatus(MainApplication.this, MBridgeConstans.IS_SWITCH_ON);

// Set CCPA do not track status before Mintegral SDK initializes.
MBridgeSDK sdk = MBridgeSDKFactory.getMBridgeSDK();
Map<String, String> map = sdk.getMBConfigurationMap("your AppId", "your AppKey");
sdk.init(map, MainApplication.this);
sdk.setDoNotTrackStatus(false);
```

2022-09-07 07:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  /**
Does Mintegral SDK support COPPA?

2022-09-07 11:32 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +
I misunderstood what you said. I'll modify this code

2022-09-07 11:33 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             value outside of 0 or 1 will result in this method being a no-op.
done

2022-09-07 11:46 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   *             outside of 0 or 1 will result in this method being a no-op.See <a
done

2022-09-07 11:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbBannerAd.java
> +package com.mintegral.mediation.rtb;
done

2022-09-07 11:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +package com.mintegral.mediation.rtb;
done

2022-09-07 11:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbNativeAd.java
> +package com.mintegral.mediation.rtb;
done

2022-09-07 11:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +package com.mintegral.mediation.rtb;
done

2022-09-07 11:51 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/MintegralExtrasBuilder.java
> +package com.mintegral.mediation;
done

2022-09-07 11:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setGdpr(@MintegralConstants.MBridgeConstants int gdpr) {
done

2022-09-07 11:58 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setGdpr(@MintegralConstants.MBridgeConstants int gdpr) {
done

2022-09-07 12:00 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (gdpr != 0 && gdpr != 1) {
done

2022-09-07 12:00 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public static void setCcpa(@MintegralConstants.MBridgeConstants int ccpa) {
done

2022-09-07 12:00 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param ccpa an {@code Integer} value that indicates whether the user opts in of the "sale" of
I will modify it

2022-09-07 12:01 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static int ccpaDoNotTrackStatus = -1;
yes

2022-09-07 12:02 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  }
done

2022-09-07 12:02 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * @param gdpr an {@code Integer} value that indicates whether the user consents the use of
done

2022-09-07 12:34 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbInterstitialAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
ok

2022-09-07 12:34 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
ok

2022-09-07 12:34 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/mintegral/mediation/rtb/MintegralRtbRewardedAd.java
> +    boolean muted = adConfiguration.getMediationExtras().getBoolean(MintegralExtrasBuilder.MUTE_AUDIO);
ok

2022-09-07 12:35 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  /**
yes. developer can set it on portal of Mintegral

2022-09-12 18:18 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    }
In the iOS PR, Lee indicated that [the placement ID is required](https://github.com/googleads/googleads-mobile-ios-mediation/pull/371#discussion_r965712471), doesn't that apply to Android too?

2022-09-13 06:00 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    }
I had add the rule

2022-10-05 03:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    }
Question: if it's `onAdLoaded`, that means the ad is loaded successfully, is it possible that the `list` would be `null` or empty here?

2022-10-05 03:02 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    //SDK_VERSION string: MAL_16.2.11
Update this to:
```
    // Mintegral SDK returns the SDK version in @"MAL_x.y.z".
```

2022-10-05 03:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +              "Found multiple appKeys in %s. Using %s to initialize Mintegral SDK.", appKeys, appKey);
Update to:
```
"Found multiple App Keys in %s. Using %s to initialize Mintegral SDK."
```

2022-10-05 03:06 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean CCPAdoNotTrackStatus = false;
Rename this to: `ccpaDoNotTrackstatus`.

2022-10-05 03:08 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +   * Set the GDPR setting in Mintegral SDK.
`Set the GDPR consent status in Mintegral SDK.`

2022-10-05 03:14 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
Sorry, can you update all these to:
```
  // Google Mobile Ads SDK doesn't have a matching event.
```

2022-10-05 03:24 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    int keyCount = appKeys.size();
Rename this to: `appKeyCount`.

2022-10-05 03:25 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +
Nit, remove empty space.

2022-10-05 03:26 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    int keyCount = appKeys.size();
Rename this to: `appKeyCount`.

2022-10-05 03:29 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      mBridgeSDK.setConsentStatus(context, gdprConsentStatus);
If the `gdprConsentStatus` value isn't `MBridgeConstans.IS_SWITCH_OFF` or `MBridgeConstans.IS_SWITCH_ON`, shouldn't we do nothing?

I think this should be the below instead:
```
if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
```

2022-10-05 03:31 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +        initializationCompleteCallback.onInitializationFailed(initError.getMessage());
Add a logging:
```
Log.w(TAG, initError.toString());
```

2022-10-05 03:33 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    } catch (Throwable e) {
If it throws an error, does it mean it fails to initialize?

2022-10-05 03:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      Method method = c.getDeclaredMethod("b", String.class);
Would recommend renaming all these variables so we clearly understand what they do.

2022-10-05 03:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +      AdError error = MintegralConstants.createAdapterError(MintegralConstants.ERROR_INVALID_SERVER_PARAMETERS, "Failed to load interstitial ad from MIntegral. Missing or invalid adUnitId");
Nit, update the message to below:
```
"Failed to load interstitial ad from Mintegral. Missing or invalid ad unit ID."
```

The same applies to all the other places.

2022-10-05 04:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    }
We can actually move all these checks into a helper method in `MintegralUtils.java` so we can keep the code D.R.Y.

For example add this helper method:
```
  @Nullable
  public static AdError validateMintegralAdLoadParams(
      @Nullable String adUnitId,
      @Nullable String placementId,
      @Nullable String bidToken) {
    if (TextUtils.isEmpty(adUnitId)) {
      AdError parameterError =
MintegralConstants.createAdapterError(MintegralConstants.ERROR_INVALID_SERVER_PARAMETERS,
              "Missing or invalid ad unit ID configured for this ad source instance in the"
                  + " AdMob or Ad Manager UI.");
      Log.e(TAG, parameterError.toString());
      return parameterError;
    }
   // ...
   return null;
  }
```

Then in here we can do:
```
    String adUnitId = adConfiguration.getServerParameters().getString(MintegralConstants.AD_UNIT_ID);
    String placementId = adConfiguration.getServerParameters().getString(MintegralConstants.PLACEMENT_ID);
    String bidToken = adConfiguration.getBidResponse();
    AdError error =
        MintegralUtils.validateMintegralAdLoadParams(
            adUnitId, placementId, bidToken);
    if (error != null) {
      adLoadCallback.onFailure(error);
      return;
    }
```

2022-10-05 04:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +    if (rewardedAdCallback != null) {
We can just do:
```
if (rewardedAdCallback == null) {
  return;
}

rewardedAdCallback.onAdClosed();
// ...
```

So we don't need to do this null check for two times.

2022-10-05 04:11 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +    if (rewardInfo == null || !rewardInfo.isCompleteView()) {
If `rewardInfo == null || !rewardInfo.isCompleteView()`, does it mean the user won't get the reward? We should log a warning here and define an error constant.

2022-10-05 04:12 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +
Nit, remove extra line.

2022-10-05 04:13 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * Retrieves the bannerView pixels
I think this should be: `Converts dp to pixels for the banner view.`?

2022-10-05 04:15 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * @param dpValue the bannerView dip size
Update this to below:
```
   * @param dpValue the size of the banner view in dp unit 
```

2022-10-05 04:21 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * @return the Mintegral bannerView pixels
Update this to below:
```
   * @return an {@code Integer} value to represent px equivalent to dp value
```

2022-10-05 04:25 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    cleanLeakedBannerRes();
Seems like we can just do the below implementation here and remove the method. 

We should probably log an error here as well? And return a failure callback?

```
    if (mbBannerView == null) {
      // Should probably add an error here, log it and return a failure callback.
      return;
    }
    mbBannerView.release();
```

2022-10-05 04:28 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    if (bannerSize == null) {
I think we should return a failure callback instead, publisher shouldn't set the banner sizes other than the ones above.

2022-10-05 04:29 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +      Log.w(TAG, error.toString());
Update to: `log.e`, this is an implementation error (from publisher).

2022-10-05 04:34 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.setLayoutParams(layoutParams);
Does Mintegral banner view match parent? If it does, we should add a wrapper view, e.g.
```
  // A container view that holds Mintegral's MBBannerView.
  private FrameLayout wrappedAdView;
```

Then in this load ad method, do:
```
    wrappedAdView = new FrameLayout(context);
    wrappedAdView.setLayoutParams(
        new FrameLayout.LayoutParams(convertDpToPixels(adConfiguration.getContext(), bannerSize.getWidth()),
            convertDpToPixels(adConfiguration.getContext(), bannerSize.getHeight()));
    // Wrap Mintegral's MBBannerView to limit the dependency on its methods. For example, the method
    // that specifies the width and height for the ad view.
    wrappedAdView.addView(adView);
```

2022-10-05 04:37 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    }
Make the code D.R.Y, see this comment: https://github.com/googleads/googleads-mobile-android-mediation/pull/420/files#r987518809.

2022-10-06 04:53 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean CCPAdoNotTrackStatus = false;
Is the default value `false`?

2022-10-06 04:53 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static int gdprConsentStatus = -1;
Is the default value (without setting it) `-1`?

2022-10-06 04:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +        addChannel();
Can consider moving the implementation here instead.

2022-10-06 05:00 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      Log.w(TAG, "Invalid GDPR value. Mintegral SDK only accepts 0 or 1.");
Update to below:
```
      Log.w(TAG, "Invalid GDPR consent status value. Mintegral SDK only accepts integer value 0 or 1.");
```

2022-10-06 05:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +   * Retrieves whether or not to mute the ad that is about to be rendered.
Update to:
```
Determines whether the ad should be muted based on the provided network extras.
```

2022-10-06 05:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +    return networkExtras != null && networkExtras.getBoolean(MintegralExtras.Keys.MUTE_AUDIO);
We should also check if the value is `true`.

2022-10-06 05:09 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * @param context the context object.
Nit, remove "."

2022-10-06 05:16 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.release();
Is this needed? Each time a banner ad is requested, a new adapter instance will be created.
We also have a new banner instance every time:
```
    mbBannerView = new MBBannerView(adConfiguration.getContext());
```

2022-10-06 05:17 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +                                    MediationAdLoadCallback<MediationInterstitialAd, MediationInterstitialAdCallback> callback) {
Add `@NonNull` annotations for both input parameters.

2022-10-06 05:17 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    }
Applies to all the other ad formats.

2022-10-06 05:18 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +                                MediationAdLoadCallback<MediationRewardedAd, MediationRewardedAdCallback> adLoadCallback) {
Add `@NonNull` annotations for both input parameters.

2022-10-06 05:20 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +          e.printStackTrace();
Log a warning here.

2022-10-06 05:21 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    Map<String, Object> properties = MBBidNativeHandler.getNativeProperties(placementId, adUnitId);
Nit, rename to `nativeProperties`.

2022-10-06 05:22 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    properties.put(NATIVE_VIDEO_SUPPORT, true);
Should this always be `true`?

2022-10-06 05:22 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    properties.put(MBridgeConstans.PROPERTIES_AD_NUM, 1);
Can you add a comment about what does this property mean?

2022-10-06 05:25 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  }
There aren't [`setMediaView`](https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAdView#public-void-setmediaview-mediaview-view) and [`setAdChoicesView`](https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAdView#public-void-setadchoicesview-adchoicesview-adchoicesview)?

2022-10-06 05:43 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    if (null == view) {
Update to: `if (view == null) {`.

2022-10-06 05:48 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +          viewList.add(viewGroup.getChildAt(i));
Do we need to do additional check here, rather than adding it to the list directly?

2022-10-08 03:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    }
Yes, it will not be empty in theory after success. For safety reasons, it is recommended to do so

2022-10-08 03:37 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    //SDK_VERSION string: MAL_16.2.11
done

2022-10-08 03:38 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +              "Found multiple appKeys in %s. Using %s to initialize Mintegral SDK.", appKeys, appKey);
done

2022-10-08 03:39 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean CCPAdoNotTrackStatus = false;
done

2022-10-08 04:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
done

2022-10-08 04:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      // no-op
done

2022-10-08 04:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      Log.w(TAG, error.toString());
done

2022-10-08 04:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      Log.w(TAG, error.toString());
done

2022-10-08 04:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +
done

2022-10-08 04:17 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    int count = appIds.size();
done

2022-10-08 04:18 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    int keyCount = appKeys.size();
done

2022-10-08 04:20 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (consentStatus != 0 && consentStatus != 1) {
done

2022-10-08 04:21 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      mBridgeSDK.setConsentStatus(context, gdprConsentStatus);
done.

2022-10-08 04:22 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +        initializationCompleteCallback.onInitializationFailed(initError.getMessage());
done

2022-10-08 05:04 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    } catch (Throwable e) {
This tag only identifies the traffic channel and does not affect the request process of the advertisement

2022-10-08 05:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private void addChannel() {
renamed it。
all ad type can load in onInitSuccess

2022-10-08 05:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +      AdError error = MintegralConstants.createAdapterError(MintegralConstants.ERROR_INVALID_SERVER_PARAMETERS, "Failed to load interstitial ad from MIntegral. Missing or invalid adUnitId");
done

2022-10-08 05:51 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    }
done

2022-10-08 05:53 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +    if (rewardedAdCallback != null) {
done

2022-10-08 05:58 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +    if (rewardInfo == null || !rewardInfo.isCompleteView()) {
done

2022-10-08 05:58 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +
done

2022-10-09 05:39 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * Retrieves the bannerView pixels
done

2022-10-09 05:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * @param dpValue the bannerView dip size
done

2022-10-09 05:40 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * @return the Mintegral bannerView pixels
done

2022-10-09 05:44 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    cleanLeakedBannerRes();
This method is no longer used. We removed it

2022-10-09 05:45 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    if (bannerSize == null) {
mintegral sdk supports it internally, and developers can customize the display size function, because different application developers may need different sizes

2022-10-09 05:46 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +      Log.w(TAG, error.toString());
done

2022-10-09 05:51 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.setLayoutParams(layoutParams);
The user can set it, and we modified it

2022-10-09 05:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    }
done

2022-10-09 05:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static boolean CCPAdoNotTrackStatus = false;
yes

2022-10-09 05:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  private static int gdprConsentStatus = -1;
yes

2022-10-09 05:59 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +        addChannel();
done

2022-10-09 05:59 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      Log.w(TAG, "Invalid GDPR value. Mintegral SDK only accepts 0 or 1.");
done

2022-10-09 06:00 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +   * Retrieves whether or not to mute the ad that is about to be rendered.
done

2022-10-09 06:08 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +    return networkExtras != null && networkExtras.getBoolean(MintegralExtras.Keys.MUTE_AUDIO);
I didn't understand what you said

2022-10-09 06:08 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * @param context the context object.
done

2022-10-09 06:09 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.release();
we removed it

2022-10-09 06:10 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +                                    MediationAdLoadCallback<MediationInterstitialAd, MediationInterstitialAdCallback> callback) {
done

2022-10-09 06:10 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +                                MediationAdLoadCallback<MediationRewardedAd, MediationRewardedAdCallback> adLoadCallback) {
done

2022-10-09 06:11 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +          e.printStackTrace();
done

2022-10-09 06:12 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    Map<String, Object> properties = MBBidNativeHandler.getNativeProperties(placementId, adUnitId);
done

2022-10-09 06:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    properties.put(NATIVE_VIDEO_SUPPORT, true);
yes

2022-10-09 06:19 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    properties.put(MBridgeConstans.PROPERTIES_AD_NUM, 1);
done

2022-10-09 07:00 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    if (null == view) {
done

2022-10-09 07:08 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  private void mapNativeAd(Campaign ad) {
When calling this method, ad can no longer be null

2022-10-09 07:18 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +          viewList.add(viewGroup.getChildAt(i));
If it is a viewgroup, it needs to traverse all child views for setting. If it is not, we will set it directly

2022-10-09 07:47 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  }
We will add these methods

2022-10-09 11:42 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +    return networkExtras != null && networkExtras.getBoolean(MintegralExtras.Keys.MUTE_AUDIO);
This code refers to the implementation of applovin. I'm not sure which parameter status you want us to check

2022-10-09 17:49 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      mBridgeSDK.setConsentStatus(context, gdprConsentStatus);
Seems like you haven't updated the code here, can you confirm if it should be the below?
```
if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
```

2022-10-09 17:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +          e.printStackTrace();
If an error is thrown here, in the Mintegral SDK perspective should we still move forward and call `onInitializationSucceeded`?

2022-10-09 17:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    setOverrideImpressionRecording(true);
Should remove this.

2022-10-10 03:52 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +          e.printStackTrace();
The success or failure of this channel does not affect the advertising process, it is only for the convenience of server statistics

2022-10-10 03:56 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    setOverrideImpressionRecording(true);
done

2022-10-27 22:48 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +   * Mintegral sdk ad no fill
Nit, `Mintegral SDK returned a no fill error.`

2022-10-27 22:48 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +
Nit, remove extra line.

2022-10-27 22:49 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    // Mintegral SDK returns the SDK version in @"MAL_16.2.11".
Nit, update the comment to:
```
// Mintegral SDK returns the SDK version in @"MAL_x.y.z" format.
```

2022-10-27 22:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
Nit, can combine these two if-checks:
```
    if (appIdCount <= 0 || appKeyCount <= 0) {
      AdError error =
          MintegralConstants.createAdapterError(
              ERROR_INVALID_SERVER_PARAMETERS, "Missing or invalid App ID or App Key"
                  + " configured for this ad source instance in the AdMob or Ad Manager UI");
      Log.e(TAG, error.toString());
      initializationCompleteCallback.onInitializationFailed(error.toString());
      return;
    }
```

2022-10-27 22:54 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +              "Found multiple app IDs in %s. Using %s to initialize Mintegral SDK.", appIds, appId);
Nit, `App ID`?

2022-10-27 22:55 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      mBridgeSDK.setConsentStatus(context, gdprConsentStatus);
@junjunsong Gentle ping, shouldn't the if check should be like below?
```
if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
```

We should only set the GDPR consent value if it's equal to one of those valid values.

2022-10-27 22:56 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +          //set channel flag. "Y+H6DFttYrPQYcIBicKwJQKQYrN=" is used to mark the AdMob channel
Nit, update to:
```
          // Set the channel flag, where "Y+H6DFttYrPQYcIBicKwJQKQYrN=" indicates it's an AdMob channel.
```

2022-10-27 23:20 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      // no-op
Seems like `// no-op` is still here, can remove.

2022-10-27 23:21 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +    return networkExtras != null && networkExtras.getBoolean(MintegralExtras.Keys.MUTE_AUDIO);
Please ignore my previous comment, I missed the `getBoolean` part.

2022-10-27 23:22 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * Converts density independent pixels unit to equivalent pixels, depending on device density
Nit, missing period "." at the end.

2022-10-27 23:24 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +              "Failed to request banner ad from Mintegral. Invalid banner size.");
Update to below:
```
      AdError bannerSizeError = MintegralConstants.createAdapterError(
          ERROR_BANNER_SIZE_UNSUPPORTED, String.format(
              "The requested banner size: %s is not supported by Mintegral SDK.",
              adConfiguration.getAdSize()));
```

2022-10-27 23:28 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView = new MBBannerView(adConfiguration.getContext());
Does Mintegral banner view always match parent?

2022-10-27 23:28 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
`    // Google Mobile Ads SDK doesn't have a matching event.`

2022-10-27 23:29 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    //No-op, AdMob has no corresponding method
`    // Google Mobile Ads SDK doesn't have a matching event.`

2022-10-27 23:30 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    //No-op, AdMob has no corresponding method
`    // Google Mobile Ads SDK doesn't have a matching event.`
The same applies to below.

2022-10-27 23:31 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  private void mapNativeAd(Campaign ad) {
Then we should add `@NonNull` annotation.

2022-10-27 23:35 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    nativeProperties.put(MBridgeConstans.PROPERTIES_AD_NUM, 1);
```
    // Configure the properties of the Mintegral native ad, where video ad will be supported and
    // only one ad will be returned in each ad request.
    nativeProperties.put(NATIVE_VIDEO_SUPPORT, true);
    nativeProperties.put(MBridgeConstans.PROPERTIES_AD_NUM, 1);
```

2022-10-27 23:37 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    mbMediaView.setVideoSoundOnOff(false);
Do these settings apply in all scenarios? Can the publisher change that?

2022-10-27 23:38 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    //No-op, this method is deprecated
Just to confirm, is this callback deprecated in Mintegral SDK?

2022-10-27 23:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +    //No-op, AdMob has no corresponding method
`// Google Mobile Ads SDK doesn't have a matching event.`
The same applies below.

2022-10-27 23:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +      Log.w(TAG,"Mintegral reward video can't get reward, because rewardInfo is null or ad is not completed");
How about just `"Mintegral SDK failed to reward user."?

Also, can you clarify what will result in failing to reward the user?

2022-10-28 08:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +   * Mintegral sdk ad no fill
done

2022-10-28 08:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +
done

2022-10-28 08:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    // Mintegral SDK returns the SDK version in @"MAL_16.2.11".
done

2022-10-28 08:22 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    }
done

2022-10-28 08:27 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +              "Found multiple app IDs in %s. Using %s to initialize Mintegral SDK.", appIds, appId);
This is the app ID of mintegral. Is this not OK?

2022-10-28 08:28 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +          //set channel flag. "Y+H6DFttYrPQYcIBicKwJQKQYrN=" is used to mark the AdMob channel
done

2022-10-28 08:29 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +   * Converts density independent pixels unit to equivalent pixels, depending on device density
done

2022-10-28 08:32 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +              "Failed to request banner ad from Mintegral. Invalid banner size.");
done. and I rename ERROR_BANNER_SIZE_MISMATCH to ERROR_BANNER_SIZE_UNSUPPORTED

2022-10-28 09:09 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView = new MBBannerView(adConfiguration.getContext());
No, we set the width and height of the view with the value of bannersize in the following code
`mbBannerView = new MBBannerView(adConfiguration.getContext());
    mbBannerView.init(bannerSize, placementId, adUnitId);
    RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(convertDpToPixels(adConfiguration.getContext(), bannerSize.getWidth()), convertDpToPixels(adConfiguration.getContext(), bannerSize.getHeight()));
    mbBannerView.setLayoutParams(layoutParams);`

2022-10-28 09:10 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView = new MBBannerView(adConfiguration.getContext());
No, we set the width and height of the view with the value of bannersize in the following code
`
    mbBannerView = new MBBannerView(adConfiguration.getContext());
    mbBannerView.init(bannerSize, placementId, adUnitId);
    RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(convertDpToPixels(adConfiguration.getContext(), bannerSize.getWidth()), convertDpToPixels(adConfiguration.getContext(), bannerSize.getHeight()));
    mbBannerView.setLayoutParams(layoutParams);
`

2022-10-28 09:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView = new MBBannerView(adConfiguration.getContext());
No, we set the width and height of the view with the value of bannersize in the following code
```
    mbBannerView = new MBBannerView(adConfiguration.getContext());
    mbBannerView.init(bannerSize, placementId, adUnitId);
    RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(convertDpToPixels(adConfiguration.getContext(), bannerSize.getWidth()), convertDpToPixels(adConfiguration.getContext(), bannerSize.getHeight()));
    mbBannerView.setLayoutParams(layoutParams);
```

2022-10-28 09:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    //No-op, AdMob has no corresponding method
done

2022-10-28 09:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    //No-op, AdMob has no corresponding method
done

2022-10-28 09:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +    //No-op, AdMob has no corresponding method
done

2022-10-28 09:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    nativeProperties.put(MBridgeConstans.PROPERTIES_AD_NUM, 1);
done

2022-10-28 09:17 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    //No-op, this method is deprecated
yes

2022-10-28 09:19 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +    //No-op, AdMob has no corresponding method
done

2022-10-28 10:03 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +      Log.w(TAG,"Mintegral reward video can't get reward, because rewardInfo is null or ad is not completed");
If the developer does not set a reward, or the user does not complete the operation as required, the user will not be rewarded, usually because the video playback is not completed

2022-10-28 11:31 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    mbMediaView.setVideoSoundOnOff(false);
I will communicate with our product team and decide how to deal with it

2022-10-31 08:12 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    mbMediaView.setVideoSoundOnOff(false);
After discussion with the our product team, we decided that the publisher can set the mute state, and the other two use the mintegral sdk default

2022-11-08 19:49 UTC, joshuajplagonera commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    Map<String, String> configurationMap = mBridgeSDK.getMBConfigurationMap(appId, appKey);
Can the Mintegral SDK handle any combination of `appId`s and `appKey`s ?
If I have two `appID`s and `appKey`s from two different apps configured on the mediation config, as outlined below:
 * My App
   * AppID1
   * AppKey1
 * My Other App 
   * AppID2
   * AppKey2 

How would the Mintegral SDK handle initializing with `AppID1` with `AppKey2` or vice versa? Would init fail? Which between "My App" and "My Other App" would be initialized if it succeeds?

2022-11-08 19:54 UTC, joshuajplagonera commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +          e.printStackTrace();
Just to confirm, does this mean that Mintegral should still bid regardless if the SDK is initialized?

2022-11-08 20:35 UTC, joshuajplagonera commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  public void onAdLoaded(List<Campaign> list, int i) {
`int i` is a bit vague. Can you rename this parameter to what it is used for ?

2022-11-09 08:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public void loadRtbBannerAd(@NonNull MediationBannerAdConfiguration adConfiguration, @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
@junjunsong 

Question: For all ad formats, will Mintegral SDK return a failure callback when trying to load ads if it's not initialized yet?

2022-11-09 08:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      // no-op
Can remove?

2022-11-09 09:06 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    Map<String, String> configurationMap = mBridgeSDK.getMBConfigurationMap(appId, appKey);
If the appid and appkey do not match, the mtg can be initialized successfully, but the valid advertisement data cannot be loaded

2022-11-09 09:13 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  public void onAdLoaded(List<Campaign> list, int i) {
I have changed i to template. We won't use this parameter

2022-11-09 09:18 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public void loadRtbBannerAd(@NonNull MediationBannerAdConfiguration adConfiguration, @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
When the Mintegral sdk has not been initialized successfully, all ad types may be loaded successfully, but we recommend that you complete the initialization of the sdk before loading

2022-11-09 09:28 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      // no-op
I can remove it.but ,if I remove it ,developer will can't get warn log,is this ok ?

2022-11-09 09:38 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    gdprConsentStatus = consentStatus;
We should still keep the `if` check we had previously.

2022-11-09 09:38 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
This `if` check should be within the `setConsentStatus()` method instead.

2022-11-09 10:32 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    gdprConsentStatus = consentStatus;
ok

2022-11-09 10:35 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
This code is different from the following code. We need to ensure that the developer has no set value in the adapter, and the adapter cannot set a value for the mintegral sdk

2022-11-09 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    Map<String, String> configurationMap = mBridgeSDK.getMBConfigurationMap(appId, appKey);
Can you explain further what "valid advertisement data cannot be loaded" means? What would be the implications if this happens? Will it prevent Mintegral from bidding/loading/rendering ads?

2022-11-10 08:40 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/build.gradle
> +    implementation 'com.mbridge.msdk.oversea:newinterstitial:16.2.11'
Is this the latest Mintegral SDK version? We should update to the latest one.

2022-11-10 08:41 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    Map<String, String> configurationMap = mBridgeSDK.getMBConfigurationMap(appId, appKey);
Sorry, I communicated with our server colleagues again. In the header bidding mode, the appkey is not verified. That is, if the appid and the appkey do not match, there is no impact. We use the appid to deal with it

2022-11-10 08:42 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    Map<String, String> configurationMap = mBridgeSDK.getMBConfigurationMap(appId, appKey);
@junjunsong Gentle ping on this.

2022-11-10 08:45 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +          e.printStackTrace();
@junjunsong 

In other words, what will happen if we call`BidManager.getBuyerUid(rtbSignalData.getContext());` if Mintegral isn't initialized?

2022-11-10 08:49 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +      // no-op
I was referring to the `// no-op` comment, but I think we can just keep it.

2022-11-10 08:50 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
We already have the below check in `setConsentStatus()`, we can remove it here.

```
if (gdprConsentStatus != MBridgeConstans.IS_SWITCH_OFF && gdprConsentStatus != MBridgeConstans.IS_SWITCH_ON){
```

2022-11-10 08:51 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +  public void loadAd() {
Nit, add space above.

2022-11-10 08:57 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.setLayoutParams(layoutParams);
Actually do we really need the `convertDpToPixels()` method? In here we can just do:

```
    mbBannerView.setLayoutParams(
        new RelativeLayout.LayoutParams(closestSize.getWidthInPixels(adConfiguration.getContext()),
            closestSize.getHeightInPixels(adConfiguration.getContext())));
```

Also, can you clarify why we use `RelativeLayout` instead of `FrameLayout` here?

2022-11-10 08:57 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +
Nit, remove extra space.

2022-11-10 08:58 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  private void mapNativeAd(Campaign ad) {
Gentle ping on this.

2022-11-10 09:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +      AdError adError = MintegralConstants.createAdapterError(MintegralConstants.ERROR_CODE_NO_FILL, "response is empty");
Update the error message to: `Mintegral SDK failed to return a native ad.`

2022-11-10 09:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    //No-op, this method is deprecated
Nit, update comment to: `// No-op, this method is deprecated.`

2022-11-10 09:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    public Uri getUri() {
Add `NonNull` annotation.

2022-11-10 09:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +
Nit, remove empty space.

2022-11-10 09:05 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +
Nit, remove one extra empty line.

2022-11-11 09:14 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    //No-op, this method is deprecated
done

2022-11-11 09:15 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +      Log.w(TAG,"Mintegral reward video can't get reward, because rewardInfo is null or ad is not completed");
done

2022-11-11 09:23 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +    if (gdprConsentStatus == MBridgeConstans.IS_SWITCH_OFF || gdprConsentStatus == MBridgeConstans.IS_SWITCH_ON) {
ConsintStatus has three statuses: On, Off, and Default. If the developer has not set it, we should not set it in adapter. The sdk will adopt different default policies according to the user's region. Once the method provided by Mintegral SDK is called, it will only be in the open or closed state. Therefore, the developer has not set the state, but we set the state in adapter, which is not in line with expectations.

2022-11-11 09:24 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +  public void loadAd() {
done

2022-11-11 12:09 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
> +    mbBannerView.setLayoutParams(layoutParams);
1. I have removed convertDpToPixels().

2. There is no special reason to use RelativeLayout. I have modified it to FrameLayout

2022-11-11 12:10 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
> +
done

2022-11-11 12:11 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +      AdError adError = MintegralConstants.createAdapterError(MintegralConstants.ERROR_CODE_NO_FILL, "response is empty");
done

2022-11-11 12:12 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    @Override
done

2022-11-11 12:12 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    public Uri getUri() {
done

2022-11-11 12:16 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +
done

2022-11-11 12:20 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
> +
done

2022-11-11 13:54 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/build.gradle
> +    implementation 'com.mbridge.msdk.oversea:newinterstitial:16.2.11'
ok .Upgrade to 16.2.61

2022-11-13 22:45 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public void loadRtbBannerAd(@NonNull MediationBannerAdConfiguration adConfiguration, @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
Let's say at ad load time the Mintegral SDK hasn't been initialized, will Mintegral SDK tries to initialize first, followed by loading the ad?

2022-11-13 22:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +              "Found multiple app IDs in %s. Using %s to initialize Mintegral SDK.", appIds, appId);
Nit, can you update `app ID` to `App ID`? Prefer maintaining consistency in all places.

2022-11-13 22:46 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +   * Invalid server parameters (e.g. Missing app ID or placement ID).
Nit, "App ID or Placement ID".

2022-11-13 22:47 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +                      "Missing or invalid ad unit ID configured for this ad source instance in the"
Nit: Can you update ad unit ID` to `Ad Unit ID`?

2022-11-13 22:47 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +                      "Missing or invalid placement ID configured for this ad source instance in the"
Nit, can you update `placement ID` to `Placement ID`?

2022-11-13 22:52 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    @NonNull
Can you remove this annotation?

2022-11-13 22:58 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  private void mapNativeAd(Campaign ad) {
Can you add `NonNull` annotation?
`  private void mapNativeAd(@NonNull Campaign ad) {`

2022-11-13 23:04 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
>    }
@junjunsong 
In Mintegral iOS adapter, there isn't CCPA/GDPR method.

Can the publisher just do the below before initializing the Google Mobile Ads SDK (so the Mintegral SDK as well) to set the GDPR/ CCPA value?
```
// GDPR
MBridgeSDK sdk = MBridgeSDKFactory.getMBridgeSDK();
Map<String, String> map = sdk.getMBConfigurationMap("your appId", "your appKey");
sdk.setConsentStatus(MainApplication.this, MBridgeConstans.IS_SWITCH_ON);
sdk.init(map, MainApplication.this);
//or
sdk.setUserPrivateInfoType(MainApplication.this, MBridgeConstans.AUTHORITY_ALL_INFO, MBridgeConstans.IS_SWITCH_ON);
sdk.init(map, MainApplication.this);

// CCPA
MBridgeSDK sdk = MBridgeSDKFactory.getMBridgeSDK();
Map<String, String> map = sdk.getMBConfigurationMap("your AppId", "your AppKey");
sdk.init(map, MainApplication.this);
sdk.setDoNotTrackStatus(false);
```

2022-11-14 09:34 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralConstants.java
> +   * Invalid server parameters (e.g. Missing app ID or placement ID).
done

2022-11-14 09:35 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +                      "Missing or invalid ad unit ID configured for this ad source instance in the"
done

2022-11-14 09:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralUtils.java
> +                      "Missing or invalid placement ID configured for this ad source instance in the"
done

2022-11-14 09:37 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +    @NonNull
done

2022-11-14 09:37 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +  private void mapNativeAd(Campaign ad) {
done

2022-11-14 09:50 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
>    }
If the developer calls the mintegral sdk method before the initialization of the admob sdk, there are two problems:

1. Do admob tell developers in the document that if the mintegral is integrated, do they need to process the initialization of the mintegral sdk separately?

2. If the developer calls in this way, do we still need to initialize the sdk in adapter?

2022-11-14 09:55 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
> +  public void loadRtbBannerAd(@NonNull MediationBannerAdConfiguration adConfiguration, @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
No

The load will not wait for the sdk initialization to complete

2022-11-14 10:58 UTC, junjunsong commented
`new MBridgeNativeMappedImage(null, Uri.parse(campaign.getIconUrl())`

If I implement this in adapter, I find that objects cannot be obtained when directly used in the demo,
`((ImageView) adView.getIconView()).setImageDrawable( nativeAd.getIcon().getDrawable());`

I saw the `setReturnUrlsForImageAssets ()` method in [this](https://developers.google.cn/admob/android/native/options) place does not automatically download images and set Drawable. How can I make it reasonable?

2022-11-14 11:03 UTC, joshh-devrel commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
>    }
-- For (1) --
Yes, we will include the GDPR/CCPA instructions in our developer documentation, see [this example](https://developers.google.com/admob/android/mediation/applovin#optional_steps). 

-- For (2) --
Perhaps the publishers/developers can just do the below **in their app** before initializing the Google Mobile Ads (hence Mintegral SDK)?
```
MBridgeSDK sdk = MBridgeSDKFactory.getMBridgeSDK();

// GDPR
sdk.setConsentStatus(MainApplication.this, MBridgeConstans.IS_SWITCH_ON);

// CCPA
sdk.setDoNotTrackStatus(false);
```

Then in `MintegralMediationAdapter` we just make an `init()` call like below:
```
    mBridgeSDK = MBridgeSDKFactory.getMBridgeSDK();
    Map<String, String> configurationMap = mBridgeSDK.getMBConfigurationMap(appId, appKey);
    mBridgeSDK.init(configurationMap, ...);
``` 

@junjunsong Questions for you:
- Can you confirm if the GDPR and CCPA consent value can be set before the `init()` call?
- Does App ID or App Key matter when setting GDPR or CCPA consent?

I would assume `MBridgeSDKFactory.getMBridgeSDK();` will return a singleton.

2022-11-14 11:22 UTC, joshh-devrel commented
> `new MBridgeNativeMappedImage(null, Uri.parse(campaign.getIconUrl())`
> 
> If I implement this in adapter, I find that objects cannot be obtained when directly used in the demo, `((ImageView) adView.getIconView()).setImageDrawable( nativeAd.getIcon().getDrawable());`
> 
> I saw the `setReturnUrlsForImageAssets ()` method in [this](https://developers.google.cn/admob/android/native/options) place does not automatically download images and set Drawable. How can I make it reasonable?

@junjunsong Would you mean the icon can't be displayed in the app? Can you provide explanation and screenshots in our collaboration document?

2022-11-15 05:22 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
>    }
1、GDPR and CCPA can be set before the `init()`
2、GDPR and CCPA have no binding relationship with appid
so I will modify the adapter according to your suggestions

2022-11-15 06:36 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
>    }
1、the GDPR and CCPA consent value can be set before the init()
2、GDPR and CCPA have no binding relationship with appid
so I will modify the adapter according to your suggestions

2022-11-15 23:38 UTC, merged