Support for InMobi SDK to 10.0.9
googleads/googleads-mobile-android-mediation pull request #425
Opened 2022-10-07 11:02 UTC by venkinmobi

2022-10-07 19:54 UTC, joshuajplagonera requested changes
Initial review.

2022-10-07 19:54 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    InMobiBannerAd mInMobiBanner = new InMobiBannerAd(mediationBannerAdConfiguration, callback);
Instead of local vars, assign these to `private` instance vars on this class to retain their memory throughout the load process.

2022-10-07 19:54 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +    private final MediationBannerAdConfiguration mMediationBannerAdConfiguration;
Please avoid using any one letter prefix in any variables (e.g. `m` in this line).

2022-10-07 19:54 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +    private static Boolean sDisableHardwareFlag = false;
Is this flag set/used anywhere else other than  for calling `adView.disableHardwareAcceleration();` ? 
I think we can remove the need for this variable and just call `disableHardwareAcceleration()` every time. We can also add a comment as to why this is necessary.

2022-10-07 19:54 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            Log.w(TAG, errorMessage);
Can you update error log messages to use `AdError.getMessage()` ?

2022-10-07 20:53 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            Log.w(TAG, errorMessage);
Sorry, correction. Use `AdError.toString()`.

2022-10-11 22:19 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +  static final String TAG = InMobiAdapter.class.getSimpleName();
Remove, we should only use the `TAG` from `InMobiMediationAdapter` class, see [this line](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java#L31).

2022-10-11 22:20 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    mInMobiNativeAd.load();
All of these should move to `InMobiMediationAdapter` class.

2022-10-11 22:22 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +      InMobiSdk.setIsAgeRestricted(false);
It's possible that the publisher hasn't specified the value so it will be [`TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED`](https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration#public-static-final-int-tag_for_child_directed_treatment_true), should the InMobi SDK still set the value to `false`?

2022-10-11 22:23 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
>        map.put("coppa", "0");
Question: We have `updateAgeRestrictedUser()` method above to set the COPPA value in InMobi SDK, do we still need the COPPA mapping here?

2022-10-11 22:24 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +    private final MediationBannerAdConfiguration mMediationBannerAdConfiguration;
+1, remove all the `m` prefixes.

2022-10-11 22:24 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +    public void load() {
Rename to `loadAd()`.

2022-10-11 22:24 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +     */
Remove this comment.

2022-10-11 22:28 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +    }
We can consider putting this method in the utils class, and rename it to `findClosestBannerSize`.

2022-10-11 22:33 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +public final class InMobiAdapter extends InMobiMediationAdapter {
Would prefer creating an `InMobiConstants.java` file and move all the error code constant from `InMobiMediationAdapter` to there. See [this example](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/PangleConstants.java).

2022-10-11 22:35 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            Log.w(TAG, errorMessage);
Update to `Log.e`.

2022-10-11 22:35 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            Log.w(TAG, error.getMessage());
Update to `Log.e`.

2022-10-11 22:36 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            AdError error = new AdError(ERROR_BANNER_SIZE_MISMATCH, errorMessage, ERROR_DOMAIN);
Nit, can rename to `mismatchError`.

2022-10-11 22:37 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        }
We should do this check earlier, in the same place as the check for Account ID.

2022-10-11 22:52 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        }
Actually we can create a util method in `InMobiAdapterUtils.java` to check the two parameters. 

```
  @Nullable
  public static AdError validateInMobiAdLoadParams(
      @Nullable String accountID,
      @Nullable long placementID) {
    if (TextUtils.isEmpty(serverEncodedPricePoint) || placementId <= 0L) {
      AdError parameterError =
          InMobiConstants.createAdapterError(
              ERROR_INVALID_SERVER_PARAMETERS,
              "Missing or invalid account ID or placement ID configured for this ad source instance in the"
                  + " AdMob or Ad Manager UI.");
      Log.e(TAG, parameterError.toString());
      return parameterError;
    }
    return null;
    }
```

Then here we can do:
```
    AdError error =
        InMobiAdapterUtils.validateInMobiAdLoadParams(
            accountID, placementID);
    if (error != null) {
      adLoadCallback.onFailure(error);
      return;
    }
```

2022-10-11 22:54 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        adView.setEnableAutoRefresh(false);
Question: Is the default of automatic refresh `true`?

2022-10-11 22:54 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        adView.setAnimationType(InMobiBanner.AnimationType.ANIMATION_OFF);
Should it be off for all cases?

2022-10-11 22:55 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        if (sDisableHardwareFlag) {
Is this `if` check needed? Seems like publisher ha no control over it and we just do `disableHardwareAcceleration()` every time.

2022-10-11 23:27 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            }
We can have the `InMobiBannerAd` class implements `BannerAdEventListener` and do the below here:
```
        adView.setListener(InMobiBannerAd.this);
```

The same applies to all the other ad formats, see [this example](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/rtb/PangleRtbBannerAd.java).

2022-10-11 23:28 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +    public void load() {
Rename to `loadAd()`.

2022-10-11 23:28 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +public class InMobiInterstitialAd implements MediationInterstitialAd {
See comments from `InMobiBannerAd` class.

2022-10-11 23:30 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        }
We can have an `InMobiInitializer` class that keeps track of the status, see [this example](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/PangleInitializer.java).

2022-10-11 23:31 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +public class InMobiNativeAd {
See comments in `InMobiBannerAd` class that might apply here as well.

2022-10-11 23:31 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +    public void load() {
Rename to `loadAd()`.

2022-10-11 23:31 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +    private InMobiNative mAdNative;
Remove all `m` prefixes.

2022-10-11 23:33 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +                            // No op.
Should be:
```
  // Google Mobile Ads SDK doesn't have a matching event.
```

2022-10-11 23:33 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +                    // No op.
Should be:
```
  // Google Mobile Ads SDK doesn't have a matching event.
```

2022-10-11 23:33 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +                    // No op.
Should be:
```
  // Google Mobile Ads SDK doesn't have a matching event.
```

2022-10-11 23:44 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +public class InMobiBannerAd implements MediationBannerAd {
Referring to another comment in the adapter class, we should create a `InMobiConstants` class nad add two methods: `createAdapterError()` and `createSdkError()` (for error coming from InMobi SDK). Then use these methods in all the ad format classes to create an `AdError` object. 

See [this example](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/PangleConstants.java#L41-L50).

2022-10-24 07:46 UTC, joshh-devrel commented
@venkinmobi Would you have any update reviewing the comments provided? Thanks!

2022-11-02 20:57 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        }
This does not apply here. This is not to check whether InMobi SDK is initialized or not.
InMobi ad objects can throw an `SdkNotInitializedException` exception, which  we should try to catch. Removing this `try/catch` will cause an uncaught exception.

2022-11-07 07:59 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    mInMobiNativeAd.load();
@joshh-devrel Here is my comments,

Please check the attached screenshot,

1. About InmobiAdapter class which we got reply from google, 

<img width="1103" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/102140444/200252629-fb0177fb-5156-421d-9d9f-582342421762.png">

2. From Admob inmobi adapter implementation, publisher will add **InmobiAdapter** class as network bundle while initialising,

<img width="1015" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/102140444/200252993-4852a147-4aa8-4d61-bbe1-6fc883c553c5.png">

If we remove InmobiAdapter class then google backend has to make changes to target InmobiMediationAdapter class to load all the Ads.

2022-11-07 08:04 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +      InMobiSdk.setIsAgeRestricted(false);
@joshh-devrel  Yes, If publisher has not specified [TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE](https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration#public-static-final-int-tag_for_child_directed_treatment_unspecified) then setIsAgeRestricted will be false

2022-11-07 08:08 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        adView.setEnableAutoRefresh(false);
@joshh-devrel  Yes by default its true

2022-11-07 12:59 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    InMobiBannerAd mInMobiBanner = new InMobiBannerAd(mediationBannerAdConfiguration, callback);
Resolved, please check the latest commit

2022-11-07 13:00 UTC, venkinmobi commented
@joshh-devrel Resolved all your comments, please check the latest commit

2022-11-09 08:56 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
>   */
Add `@Keep` annotation.

2022-11-09 08:57 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    inMobiNativeAd.loadAd();
Move all these lines to `InMobiMediationAdapter`.

2022-11-09 09:04 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +                           MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> mediationAdLoadCallback){
Add `NonNull` annotations for both input parameters, do this for ALL ad formats.

2022-11-09 09:08 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +            Log.e(TAG, error.toString());
Update to `Log.w`.

2022-11-09 09:09 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        AdError error = InMobiConstants.createAdapterError(ERROR_AD_DISPLAY_FAILED, "InMobi ad failed to show.");
Update the error message to: `InMobi SDK failed to display an interstitial ad.`

2022-11-09 09:11 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +    Log.e(TAG, logMessage);
Revert to `Log.w`.

2022-11-09 09:11 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +    Log.e(TAG, logMessage);
Revert to `Log.w`.

2022-11-09 09:12 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +      Log.e(TAG, message);
Revert to `Log.w`.

2022-11-09 09:13 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +      AdError error = InMobiConstants.createAdapterError(ERROR_INVALID_SERVER_PARAMETERS, "Missing or Invalid Account ID.");
Update the error to:
```
      AdError error =
              InMobiConstants.createAdapterError(
                      ERROR_INVALID_SERVER_PARAMETERS, "Missing or invalid account ID"
                              + " configured for this ad source instance in the AdMob or Ad Manager UI");
```

2022-11-09 09:27 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +    public InMobiBannerAd (MediationBannerAdConfiguration mediationBannerAdConfiguration,
Nit, remove space between `InMobiBannerAd` and `(MediationBannerAdConfiguration ...`

2022-11-09 09:28 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +    private MediationRewardedAdConfiguration rewardedAdConfiguration;
Rename to `mediationRewardedAdConfiguration` to be consistent with the other places.

2022-11-09 09:29 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +  static void updateAgeRestrictedUser(MediationAdConfiguration config) {
Add `@NonNull` annotation for the input parameter, and rename `config` to `mediationAdConfiguration`.

2022-11-09 09:32 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +
Nit, remove extra line.

2022-11-09 09:34 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        Bundle extras = mediationInterstitialAdConfiguration.getMediationExtras();
Can rename to `mediationExtras`.

2022-11-09 09:35 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        Bundle extras = mediationInterstitialAdConfiguration.getMediationExtras();
We don't need an `extras` variable, can just do the following below:
```
        InMobiAdapterUtils.configureGlobalTargeting(mediationInterstitialAdConfiguration.getMediationExtras());
```

2022-11-09 09:35 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +        Bundle extras = rewardedAdConfiguration.getMediationExtras();
We don't need an `extras` variable, can just do the following below:
```
        InMobiAdapterUtils.configureGlobalTargeting(mediationInterstitialAdConfiguration.getMediationExtras());
```

2022-11-09 09:40 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +    public String getType() {
Add `@NonNull` annotation.

2022-11-09 09:40 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +    private int amount;
Why `final` was removed?

2022-11-09 09:41 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +    InMobiReward(String type, int amount) {
`type` should be `NonNull`.

2022-11-11 02:56 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +    public void onAdFetchSuccessful(@NonNull InMobiInterstitial inMobiInterstitial,
@joshh-devrel  onAdFetchSuccessful() indicates ad fetch success but its not loaded, onAdLoadSucceeded() callback says Ad is loaded successfully

2022-11-11 02:57 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +            Log.e(TAG, error.toString());
@joshh-devrel everywhere if we have AdError object we are using Log.e only, why do you want to change to Log.w ?

2022-11-11 02:58 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +public class InMobiBannerAd extends BannerAdEventListener implements MediationBannerAd {
@joshh-devrel BannerAdEventListener is abstract class not an interface, and BannerAdEventListener lagacy listener written as abstract class

2022-11-14 05:07 UTC, venkinmobi commented
@joshh-devrel resolved comments, please review the PR and merge it

2022-11-16 18:56 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +      InMobiSdk.setIsAgeRestricted(false);
For future reference, can you add a comment that this is expected behavior for InMobi? Same for coppa below on `createInMobiParameterMap()`

2022-11-16 18:58 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +
remove empty `try/catch()` block.

2022-11-16 19:08 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +    static final AtomicBoolean isSdkInitialized = new AtomicBoolean();
It seems that this can be removed in favor of just using `InMobiSdk.isSDKInitialized()` ?

2022-11-18 13:16 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +
Resolved.

2022-11-18 13:16 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +    static final AtomicBoolean isSdkInitialized = new AtomicBoolean();
Resolved.

2022-11-20 07:23 UTC, venkinmobi commented
@joshuajplagonera resolved comments, please review the PR and merge it

2022-11-22 12:53 UTC, venkinmobi commented
@joshuajplagonera resolved comments, please review the PR and merge it

2022-11-22 19:03 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    inMobiNativeAd.loadAd();
@venkinmobi I would still recommend moving these to the `InMobiMediationAdapter` class since it extends the `Adapter` class and it's the recommended practice.

2022-11-22 19:07 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +  */
Remove this and add the comment as indicated below.

Javadoc is to explain the intended meaning or purpose of the element it's attached to instead.

2022-11-22 19:09 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +      InMobiSdk.setIsAgeRestricted(false);
Add this comment:
```
// If the COPPA value isn't specified by the publisher, InMobi SDK expects the default value to be `false`.
```

2022-11-22 19:09 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +   */
Ditto, remove this and add the comment as indicated below.

Javadoc is to explain the intended meaning or purpose of the element it's attached to instead.

2022-11-22 19:11 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
>        map.put("coppa", "0");
Add this comment:
```
// If the COPPA value isn't specified by the publisher, InMobi SDK expects the default value to be `0`.
```

Note that there should be max. 100 chars per line.

2022-11-22 19:15 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +                      "Missing or invalid account ID or placement ID.");
Nit, `"Missing or invalid Account ID or Placement ID for this ad source instance in the AdMob or Ad Manager UI."`

Note: Number of chars shouldn't exceed > 100 per line.

2022-11-22 19:19 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        InMobiBanner adView;
We can just do `InMobiBanner adView = new InMobiBanner(context, placementId);` below so this line can be removed.

2022-11-22 19:20 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        }
We just did the initialization check on line 69, do we need to do it again here?

2022-11-22 19:25 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +  static void updateAgeRestrictedUser(MediationAdConfiguration mediationAdConfiguration) {
Add `@NonNull` annotation for the `mediationAdConfiguration` parameter.

Also I would rename this to `setIsAgeRestricted()`, what do you think?

2022-11-22 19:29 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
>        map.put("coppa", "0");
Question: We already have the `updateAgeRestrictedUser()` method above that set COPPA in InMobi SDK based on `mediationAdConfiguartion`, do we still need this then?

2022-11-22 19:31 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +                InMobiAdapterUtils.createInMobiParameterMap(mediationBannerAdConfiguration);
Question: Considering we have `updateAgeRestrictedUser()`, do we still need this to set the COPPA value?

2022-11-22 19:31 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        //Update Age Restricted User
Nit, can update the comment to: `// Set the COPPA value in InMobi SDK.`

2022-11-22 19:34 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        Log.d(TAG, "InMobi banner left application.");
Nit, can update the logging message to: `"InMobi banner ad has caused the user to leave the application."`

2022-11-22 19:37 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +    private void createAndLoadInterstitialAd(Context context, long placementId) {
The comments in `InMobiBannerAd` also apply here.

2022-11-22 19:38 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        Log.d(TAG, "InMobi interstitial left application.");
`"InMobi interstitial ad has caused the user to leave the application."`

2022-11-22 19:40 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        // Using onAdDisplayed to send the onAdOpened callback.
```
// No-op, `onAdDisplayed` will be used to forward the Google Mobile Ads SDK `onAdOpened` callback instead.
```

2022-11-22 19:41 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        Log.d(TAG, "InMobi interstitial ad fetched from server, "
Nit:
```
"InMobi SDK fetched the interstitial ad successfully, but the ad contents still need to be loaded."
```

2022-11-22 19:41 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +        Log.d(TAG, "InMobi interstitial has been shown.");
Nit, `"interstitial ad"`.

2022-11-22 19:43 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +            AdError error = InMobiConstants.createAdapterError(ERROR_INVALID_SERVER_PARAMETERS,
Nit nit, lower case "invalid".

2022-11-22 19:43 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +        inMobiRewarded = new InMobiRewardedAd(mediationRewardedAdConfiguration,
Nit, prefer renaming the variable to: `inMobiRewardedAd`.

2022-11-22 19:47 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +    private void createAndLoadNativeAd(Context context, long placementId) {
The comments in `InMobiBannerAd` class' `createAndLoadBannerAd()` method also apply here.

2022-11-22 19:47 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +        boolean mIsOnlyUrl = false;
Nit nit, remove `m` prefix.

2022-11-22 19:48 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +        Log.d(TAG, "InMobi native ad left application.");
`"InMobi native ad has caused the user to leave the application."`

2022-11-22 19:50 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +  public InMobiUnifiedNativeAdMapper(InMobiNative inMobiNative,
Can `inMobiNative` be `null`?

If not, can you add the `@NonNull` annotation? `@Nullable` otherwise.

2022-11-22 19:52 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +      Log.e(TAG, error.toString());
Should be `Log.w` instead, since this is not a pub's implementation error.

2022-11-22 19:52 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +        Log.e(TAG, "InMobi custom native ad content payload could not be parsed. "
`Log.w`.

2022-11-22 20:07 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +                          "Failed to download image assets.");
Nit: `"InMobi SDK failed to download image assets."`

2022-11-22 20:07 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +                            "Failed to download image assets.");
Nit: `"InMobi SDK failed to download image assets."`

2022-11-22 20:34 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +         */
I didn't see any values related to #1 and #2 are set in `createInMobiParameterMap()`. Is this still applicable?

2022-11-22 20:42 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +  private final InMobiNativeAd inMobiNativeAd;
There is the `inMobiNative` variable which makes it confusing. 

Would prefer renaming `inMobiNative` to something else, for example `imNative`.

2022-11-22 20:44 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +  public InMobiUnifiedNativeAdMapper(InMobiNative inMobiNative,
We actually don't need this extra class but we can just add a `mapNativeAd` method within `InMobiNativeAd` class, and do all the mappings there.

See  [this sample implementation](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/rtb/PangleRtbNativeAd.java#L119).

2022-11-24 09:44 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        }
@joshh-devrel We have certain checks on our end for SDK Initialisation for example the context check (i.e. If it becomes null at any point). So we wanted to double-sure If the SDK is initialised porperly before we create the adView.

2022-11-24 09:45 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
>        map.put("coppa", "0");
@joshh-devrel Both of them to handle different purpose, Age restriction is for google family policy and COPPA flag is for COPPA compliances

2022-11-24 09:45 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +                InMobiAdapterUtils.createInMobiParameterMap(mediationBannerAdConfiguration);
Yes @joshh-devrel as explained above
"Both of them to handle different purpose, Age restriction is for google family policy and COPPA flag is for COPPA compliances"

2022-11-24 09:57 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiUnifiedNativeAdMapper.java
> +  public InMobiUnifiedNativeAdMapper(InMobiNative inMobiNative,
@joshh-devrel  **InMobiNativeAd** is already extending **NativeAdEventListener** which is abstract listener class for ad lifecycle callbacks. For the mapNativeAd method to be inside **InMobiNativeAd** we'd have to extend Admob's **UnifiedNativeAdMapper** class as well, which is not possible. Hence the extra class.

2022-11-24 10:09 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +         */
@joshh-devrel 
wrt #1 we are explicitly setting mediation supply partner to Admob which is 
**map.put("tp", "c_admob");**
wrt #2 It was legacy code comment, removed it.

2022-11-29 04:34 UTC, joshh-devrel commented
@manishk97 @venkinmobi Would you have any update on resolving the latest comments? Thanks!

2022-11-30 07:03 UTC, manishk97 commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    inMobiNativeAd.loadAd();
@joshh-devrel As mentioned earlier as well, **InMobiAdapter** class is configured in Google's backend to be the one responsible for loading all ad formats. As you can check from the image below which is from an active mail thread that we are sharing with Admob team.
<img width="1103" alt="Screenshot 2022-11-07 at 1 06 27 PM" src="https://user-images.githubusercontent.com/102140353/204728031-ae05131e-382c-42c5-a124-d7437e7c21b6.png">

Further as mentioned on Admob support page we use InMobiAdapter class while forming AdRequest. This would need to change as well.
<img width="1015" alt="Screenshot 2022-11-07 at 1 06 13 PM" src="https://user-images.githubusercontent.com/102140353/204728412-9d7df09d-d771-4d6d-890e-f0210136e1e3.png">

2022-11-30 07:07 UTC, venkinmobi commented
@joshh-devrel resolved all your comments, please check and merge

2022-12-12 10:34 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapter.java
> +    inMobiNativeAd.loadAd();
@manishk97 

Thanks for the feedback, I was the one who sent that reply.

Since `InMobiAdapter` now extends `InMobiMediationAdapter`, it will still work and it's preferred to move all the `load<>Ad` classes there.

2022-12-12 10:35 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +    be `false`. */
Nit, can you update to use`//` instead?

2022-12-12 10:35 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiAdapterUtils.java
> +    /* If the COPPA value isn't specified by the publisher, InMobi SDK expects the default value to
Nit, can you update to use`//` instead?

2022-12-12 10:38 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +        Log.e(TAG, error.toString());
Nit, `Log.w()` since it comes from InMobi SDK.

2022-12-12 10:40 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +                Log.e(TAG, error.toString());
Should be `Log.d()` or `Log.w()` unless the error is caused by publisher's invalid parameter inputs.

2022-12-12 10:42 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiBannerAd.java
> +            AdError error = InMobiConstants.createAdapterError(ERROR_INMOBI_NOT_INITIALIZED, "Please initialize the SDK before creating InMobiBanner.");
Can you update the error message to:
`InMobi SDK failed to request a banner ad since it isn't initialized."

2022-12-12 10:42 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialAd.java
> +                    "Please initialize the SDK before creating InMobiInterstitial.");
Can you update the error message to:
`InMobi SDK failed to request an interstitial ad since it isn't initialized."

2022-12-12 10:43 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +            AdError error = InMobiConstants.createAdapterError(ERROR_INMOBI_NOT_INITIALIZED,
Can you update the error message to:
`InMobi SDK failed to request a native ad since it isn't initialized."

2022-12-12 10:45 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +                                               mMediationAdLoadCallback) {
Nit: Remove `m` prefix.

2022-12-12 10:45 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +                    "Please initialize the SDK before creating InMobiRewardedAd.");
Can you update the error message to:
`InMobi SDK failed to request a rewarded ad since it isn't initialized."

2022-12-12 10:47 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +    private MediationAdLoadCallback<MediationRewardedAd, MediationRewardedAdCallback>
Add `final`.

2022-12-12 10:48 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +                Log.e(TAG, error.toString());
`Log.w()`.

2022-12-12 10:48 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +                    "InMobi Rewarded ad is not yet ready to be shown.");
Nit, `rewarded ad`.

2022-12-12 10:48 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +            Log.e(TAG, error.toString());
`Log.w`.

2022-12-12 10:51 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
> +    private final String type;
@manishk97 @venkinmobi 

Can you confirm if you have applied the correct formatting here?

https://github.com/googleads/googleads-mobile-android-mediation/blob/main/CONTRIBUTING.md#best-practices

2022-12-12 10:54 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +        // Setting mediation key words to native ad object
Nit, missing period.

2022-12-12 10:56 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +        // This setting decides whether to download images or not.
Can remove. This is indicated in the Google Mobile Ads SDK reference doc: https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationNativeAdConfiguration#getNativeAdOptions().

2022-12-12 10:58 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNativeAd.java
> +         */
Can remove.

2022-12-12 11:01 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiRewardedAd.java
>  public class InMobiRewardedAd implements MediationRewardedAd {
Can extend the `InterstitialAdEventListener` here so we can move all the callbacks out from where we create the `inMobiRewardedAd` instance.

2022-12-14 06:32 UTC, venkinmobi commented
@joshh-devrel resolved all your comments, please check and merge

2022-12-21 12:34 UTC, joshh-devrel commented
Thanks @venkinmobi, we are currently reviewing the pull request and will merge it if there isn't any blocking issue.

2022-12-27 20:13 UTC, merged