Release/iron source banner
googleads/googleads-mobile-android-mediation pull request #427
Opened 2022-10-14 05:56 UTC by alon357

Add Support for IronSource Banner and update SDK to 7.2.5

2022-10-17 23:51 UTC, joshuajplagonera requested changes

2022-10-17 23:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +        Log.e(TAG, errorMessage);
Use a warning log.
Also log `loadError.toString()`

2022-10-17 23:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +                    "adSize",
is this `"adsize"` supposed to be part of the error message? I think it can be removed.

2022-10-17 23:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
>    /**
Please put this under line 84 so the error codes are in chronological order.

2022-10-17 23:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +  private MediationRewardedAdCallback mMediationRewardedAdCallback;
Remove any `m` prefix.

2022-10-18 15:19 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    private String mInstanceID;
Removed

2022-10-18 15:20 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +        Log.e(TAG, errorMessage);
Fixed

2022-10-18 15:20 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +                    "adSize",
Removed it

2022-11-01 22:07 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +public class IronSourceAdapter implements MediationInterstitialAdapter, MediationBannerAdapter, IronSourceAdapterListener {
We should load the banner ad through [`loadBannerAd`](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/Adapter#loadBannerAd(com.google.android.gms.ads.mediation.MediationBannerAdConfiguration,%20com.google.android.gms.ads.mediation.MediationAdLoadCallback%3Ccom.google.android.gms.ads.mediation.MediationBannerAd,%20com.google.android.gms.ads.mediation.MediationBannerAdCallback%3E)) method in [`IronSouceMediationAdapter`](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java#L33) since it uses the new [`Adapter`](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/Adapter) API. See [this example](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/pangle/pangle/src/main/java/com/google/ads/mediation/pangle/PangleMediationAdapter.java#L168-L169).

Then we can:
- Have `IronSourceAdapter` class extends `IronSouceMediationAdapter`.
- Create a new `IronSourceBannerAd` class that implements [`MediationBannerAd`](https://developers.google.com/android/reference/com/google/android/gms/ads/mediation/MediationBannerAd) and `ISDemandOnlyBannerListener`.


Also, we should update interstitial to use the new API as well.

2022-11-01 22:08 UTC, joshh-devrel commented
@alon357 I have added a new comment to use the new mediation `Adapter` API. Also, can you resolve the conflict?

2022-11-21 06:27 UTC, joshh-devrel commented
@alon357 Would you have any update on resolving the conflicts and updating the banner code to use the new mediation `Adapter` API? Thanks!

2022-12-19 13:28 UTC, closed without merging