Add New Banner and Interstitial implementation
googleads/googleads-mobile-android-mediation pull request #446
Opened 2023-02-09 13:21 UTC by alon357

New Adapter For IronSource.
Includes new Banner and new API for Interstitial

2023-02-14 20:00 UTC, joshuajplagonera requested changes
Initial review.

2023-02-14 20:00 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +                            bannerAdCallback.onAdOpened();
`onAdOpened()` should be forwarded when the banner ad is clicked or tapped.
I think this should be forwarded on `onBannerAdClicked()` instead?

Additionally, can you confirm that IronSource does not have a callback for `onAdClosed()` ?

2023-02-20 16:12 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +        if (ironSourceBannerAd!=null) {
The way we support loading multiple banner ads using the same instance is that if the banner instance is already loaded, we destroy it first and only then load the instance. 
So we practically support loading the same instance by reloading it.

2023-02-21 20:38 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +        if (ironSourceBannerAd!=null) {
Thank you for explaining.
However, I think this will cause the issue if 2 simultaneous banner ads are loaded, then IronSource will destroy the other one while both are loaded.

To illustrate:
```
bannerAd1 = new AdView();
bannerAd1.load();

bannerAd2 = new AdView();
bannerAd2.load(); // IronSource will destroy bannerAd1 without reloading it.
```

That said, I believe a check should be added if the instance is loading/already loaded and fail the ad request if it is.

2023-03-02 12:02 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +        IronSource.initISDemandOnly(context, appKey, IronSource.AD_UNIT.INTERSTITIAL,
IronSource required an activity context either from the init API or the Load API

2023-03-02 12:03 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +        if (ironSourceBannerAd!=null) {
We have fixed this issue in the new push

2023-03-15 21:59 UTC, joshuajplagonera requested changes
Second round of review.
Please remove any 2 consecutive empty lines.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    // endregion
Remove.
This is already in `IronSourceMediationAdapter`. We can use those to avoid multiple declarations.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +public class IronSourceBannerAd extends IronSourceMediationAdapter implements MediationBannerAd, ISDemandOnlyBannerListener {
This does not need to extend `IronSourceMediationAdapter`. Remove.

It just need to implement `MediationBannerAd`.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +            ironSourceBannerAd.onAdFailedToLoad(contextError);
This will crash. 
`ironSourceBannerAd` has no value yet since it is being sent below on line 166.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +    public void loadBanner(@NonNull MediationBannerAdConfiguration MediationBannerAdConfiguration,
Similar to how Rewarded and Interstitial are implemented, we should pass an adapter instance here and save that instance to check for multiple instances.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +            adLoadCallback.onFailure( sizeError);
Log the error here:
`Log.e(TAG, sizeError.toString());`

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +                        Log.d(TAG,
We should load the banner ad inside this block.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +                            ironSourceAdView.addView(ironSourceBannerLayout);
This line is unrelated to the value of `adLoadCallback`. Remove from the `if()` block.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +        String errorMessage = String
We can just log `loadError.toString()` as a warning.

2023-03-15 21:59 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +                Log.d(TAG, String.format("IronSource banner ad is already Loading or Showing"));
Is this necessary? we are already logging the message in `onBannerAdLoadFailed()`

2023-03-19 09:19 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +            adLoadCallback.onFailure( sizeError);
Done

2023-03-19 09:19 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +                        Log.d(TAG,
Done

2023-03-19 09:19 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +        String errorMessage = String
Done

2023-03-19 09:19 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +                            ironSourceAdView.addView(ironSourceBannerLayout);
Done

2023-03-19 09:21 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +                Log.d(TAG, String.format("IronSource banner ad is already Loading or Showing"));
We need it for the reload flow of the banner

2023-03-19 09:21 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +            ironSourceBannerAd.onAdFailedToLoad(contextError);
Done

2023-03-19 09:21 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +public class IronSourceBannerAd extends IronSourceMediationAdapter implements MediationBannerAd, ISDemandOnlyBannerListener {
Done

2023-03-19 09:22 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +    public void loadBanner(@NonNull MediationBannerAdConfiguration MediationBannerAdConfiguration,
We do inline 152

2023-04-25 17:11 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +public class IronSourceAdapter extends IronSourceMediationAdapter implements  MediationInterstitialAd,IronSourceAdapterListener {
We should have another class `IronSourceInterstitialAd` specifically for interstitial ad format, like what we did for banner.

2023-04-25 17:12 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    public void initialize(@NonNull Context context,
Remove. You already implement `initialize()` in `IronSourceMediationAdapter` and this class extends it, so we don't need to do it again.

2023-04-25 17:13 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +        Log.e(TAG, errorMessage);
`Log.w` as this isn't an error caused by publisher's implementation.

2023-04-25 17:14 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +                new Runnable() {
Can you remind me if it's a requirement in IronSource SDK to do `Runnable()` for the ad events?

2023-04-25 17:14 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +        Log.e(TAG, errorMessage);
`Log.w` as this isn't a pub implementation issue.

2023-04-25 17:15 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    }
This should be in `IronSourceMediationAdapter` class.

2023-04-25 17:16 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +    }
Are these IronSource banner ad listeners? We should have these in `IronSourceBannerAd` class instead.

2023-04-25 17:16 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  static final String ADAPTER_VERSION_NAME = "400";
How is the `400` determined?

2023-04-25 17:17 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +     * This is the id of the banner instance requested.
Update to:
```
* IronSource banner instance ID.
```

2023-04-25 17:18 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +     * The view for the banner instance.
Nit, can update to:
```
* IronSource banner instance view.
```

2023-04-25 17:22 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +public class IronSourceManager implements ISDemandOnlyRewardedVideoListener, ISDemandOnlyInterstitialListener, ISDemandOnlyBannerListener {
Can you revert the indentation changes in this file? That will make us easier to review what have been changed.

2023-04-25 17:24 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +public class IronSourceManager implements ISDemandOnlyRewardedVideoListener, ISDemandOnlyInterstitialListener, ISDemandOnlyBannerListener {
Can you remind me again why we need `IronSourceManager`? We can just do `IronSourceBanner implements ISDemandOnlyBannerListener`.

2023-04-25 17:25 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +    private boolean canLoadRewardedVideoInstance(@NonNull String instanceId) {
All the rewarded video ad listeners should be implemented in another class, i.e. `IronSourceRewardedAd`.

2023-04-25 17:25 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +
Nit, remove extra lines.

2023-04-25 17:27 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    public void onRewardedVideoAdLoadSuccess(String instanceId) {
Please create a new `IronSourceRewardedAd` class and move all rewarded video ad implementations there.

2023-04-25 17:29 UTC, joshh-devrel commented
@alon357 Can you rebase this PR and resolve the latest comments? Thanks!

2023-05-24 14:55 UTC, closed without merging