Update IronSource SDK to 7.3.0.
googleads/googleads-mobile-android-mediation pull request #452
Opened 2023-03-23 06:45 UTC by alon357

Update IronSource Imports

2023-03-23 18:53 UTC, LTPhantom requested changes

2023-03-23 18:53 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +import com.ironsource.mediationsdk.demandOnly.ISDemandOnlyRewardedVideoListener;
I believe extra amending should be done for line 103 and 123 since both methods are deprecated as well, right?

```
public static void loadISDemandOnlyInterstitial(String instanceId)
public static void loadISDemandOnlyRewardedVideo(String instanceId)
```

2023-03-23 20:40 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +import com.ironsource.mediationsdk.demandOnly.ISDemandOnlyRewardedVideoListener;
+1, @alon357 can you make sure all the [deprecated classes](https://developers.is.com/ironsource-mobile/android/7-3-0-integration-and-api-changes/#step-2) are addressed in this PR?

2023-03-26 06:53 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +import com.ironsource.mediationsdk.demandOnly.ISDemandOnlyRewardedVideoListener;
Thanks @joshh-devrel 
I have fixed the deprecated APIs

2023-03-28 08:25 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
> +            IronSourceManager.getInstance().loadInterstitial(context,instanceID, IronSourceAdapter.this);
Nit, add space after `context,` and there should be < 100 chars per line.

2023-03-28 08:28 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +      AdError contextError = new AdError(ERROR_REQUIRES_ACTIVITY_CONTEXT, errorMessage, ERROR_DOMAIN);
Ditto, nit: Max. 100 chars per line.

2023-03-28 08:31 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/build.gradle
>      implementation 'com.google.android.gms:play-services-ads:21.4.0'
Can you update the Google Mobile Ads SDK version to `21.5.0`?

2023-03-29 07:15 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> -
@joshh-devrel 
IronSource required context of Activity ether from the init or the load.
It want fail if the init is with context as long as the load is type of Activity

2023-03-29 07:28 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> +              .format(ERROR_REQUIRES_ACTIVITY_CONTEXT + "IronSource requires an Activity context to load ads.");
@joshh-devrel  IronSource still requires a context of activity either from the init or the load.
I removed the  check from the init and moved it to the load

2023-03-29 07:29 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/build.gradle
>      implementation 'com.google.android.gms:play-services-ads:21.4.0'
Done

2023-03-29 21:25 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> -
If ironSource SDK requires the passed in `context` to be an `Activity` when initialize, we should keep the above check.

2023-03-30 06:08 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> -
IronSource requires a context of activity either from the init or the load.
If the context in the init will be not a type of Activity, but in the load function it will be a type of Activity then it will work.

2023-03-30 06:52 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
> -
Thanks for confirming!

2023-03-30 06:57 UTC, merged