Added support for IAB US privacy String
googleads/googleads-mobile-android-mediation pull request #472
Opened 2023-07-05 01:44 UTC by venkinmobi

2023-07-05 13:34 UTC, ericleich commented
@venkinmobi Does InMobi SDK already read the IAB US privacy String from Shared preferences? Instead of providing an alternative way to set through extras, or having the adapter also read it and pass it to InMobi SDK, I'd prefer we just ask publishers to set the value through shared preferences and InMobi SDK will read it directly. Then no adapter code is required.

2023-07-06 07:19 UTC, venkinmobi commented
> @venkinmobi Does InMobi SDK already read the IAB US privacy String from Shared preferences? Instead of providing an alternative way to set through extras, or having the adapter also read it and pass it to InMobi SDK, I'd prefer we just ask publishers to set the value through shared preferences and InMobi SDK will read it directly. Then no adapter code is required.

Hi @ericleich ,

InMobi SDK accepts the US Privacy String via an API. Setting the US privacy String via shared preferences is not a standard that all publishers/mediations follow. So, we are reading it in the adapter for Admob and passing onto the InMobi SDK.

Please review the PR.

2023-07-24 16:10 UTC, joshh-devrel commented
@venkinmobi Can you rebase this pull request?

2023-07-24 16:12 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiExtrasBuilder.java
> +      }
Fix format in these lines according to Google Style: https://github.com/googleads/googleads-mobile-android-mediation/blob/main/CONTRIBUTING.md#best-practices

2023-07-24 16:13 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/test/kotlin/com/google/ads/mediation/inmobi/InMobiExtrasBuilderTest.kt
> +  private val context = ApplicationProvider.getApplicationContext<Context>()
Move this to above `mediationExtras`.

2023-07-24 16:14 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/test/kotlin/com/google/ads/mediation/inmobi/InMobiExtrasBuilderTest.kt
> +    val inMobiExtras = InMobiExtrasBuilder.build(context,mapToBundle(mediationExtras), protocol)
Nit, there should be space after comma in `context,mapToBundle(mediationExtras)`. Apply this change to all the lines below.

2023-07-24 16:15 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiMediationAdapter.java
> +                rtbSignalData.getContext(),
Fix format according to Google Style: https://github.com/googleads/googleads-mobile-android-mediation/blob/main/CONTRIBUTING.md#best-practices

2023-07-24 16:18 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiNetworkKeys.java
> +  String IAB_US_STRING = "IABUSPrivacy_String";
Prefer renaming it to `IAB_US_PRIVACY_STRING`.

2023-07-24 16:24 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiExtrasBuilder.java
> +    //US privacy string from SharedPreferences
```
// Forward U.S. Privacy consent value set in SharedPreferences to InMobi SDK.
```

2023-07-24 16:32 UTC, joshh-devrel commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiExtrasBuilder.java
> +      String iabUSPPrivacyStringFromPreferences = sharedPref.getString(InMobiNetworkKeys.IAB_US_STRING, null);
Typo in the variable name, also can rename it according to below:
```
String iabUSPrivacyString = sharedPreferences.getString(InMobiNetworkKeys.IAB_US_PRIVACY_STRING, null);
```

We shouldn't need the `FromPreferences` in the variable name since the code already indicates how we get the value.

2023-07-26 06:48 UTC, joshh-devrel commented
@venkinmobi  Would you have any update on resolving the comments? Also there shouldn't be 26 commits, please rebase your branch.

2023-07-26 06:50 UTC, venkinmobi commented
@joshh-devrel resolved all comments please check the PR

2023-07-29 00:09 UTC, LTPhantom requested changes
**On `InMobiMediationAdapterTest.kt`**:
- Move line `private val context = ApplicationProvider.getApplicationContext<Context>()` to before `rtbSignalData` declaration.
- Modify `private val rtbSignalData = mock<RtbSignalData>()` to:
```
private val rtbSignalData = mock<RtbSignalData>{
    on { context } doReturn context
  }
```
and import `doReturn` from `org.mockito.kotlin`

**On `InMobiRtbInterstitialAdTest.kt`**:
- Modify `private val interstitialAdConfiguration = mock<MediationInterstitialAdConfiguration>()` to:
```
private val interstitialAdConfiguration = mock<MediationInterstitialAdConfiguration>{
    on { context } doReturn context
  }
```
- Move `private val context = ApplicationProvider.getApplicationContext<Context>()` above `interstitialAdConfiguration` declaration

**On `InMobiRtbRewardedAdTest.kt`**:
- Modify `private val rewardedAdConfiguration = mock<MediationRewardedAdConfiguration>()` to:
```
private val rewardedAdConfiguration = mock<MediationRewardedAdConfiguration>{
    on { context } doReturn context
  }
```
- Move `private val context = ApplicationProvider.getApplicationContext<Context>()` above `rewardedAdConfiguration` declaration

**On `InMobiWaterfallInterstitialAdTest.kt`**:
- Modify `private val interstitialAdConfiguration = mock<MediationInterstitialAdConfiguration>()` to:
```
private val interstitialAdConfiguration = mock<MediationInterstitialAdConfiguration>{
    on { context } doReturn context
  }
```
and import `doReturn` from `org.mockito.kotlin`.
- Move `private val context = ApplicationProvider.getApplicationContext<Context>()` above `interstitialAdConfiguration` declaration

**On `InMobiWaterfallRewardedAdTest.kt`**:
- Modify `private val rewardedAdConfiguration = mock<MediationRewardedAdConfiguration>()` to:
```
private val rewardedAdConfiguration = mock<MediationRewardedAdConfiguration>{
    on { context } doReturn context
  }
```
and import `doReturn` from `org.mockito.kotlin`.
- Move `private val context = ApplicationProvider.getApplicationContext<Context>()` above `rewardedAdConfiguration` declaration

2023-08-01 06:42 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiExtrasBuilder.java
> +import android.preference.PreferenceManager;
Resolved

2023-08-01 06:42 UTC, venkinmobi commented on ThirdPartyAdapters/inmobi/inmobi/src/test/kotlin/com/google/ads/mediation/inmobi/InMobiExtrasBuilderTest.kt
> +private val context = ApplicationProvider.getApplicationContext<Context>()
Resolved

2023-08-01 06:44 UTC, venkinmobi commented
@LTPhantom @joshh-devrel please check the PR all comments are resolved

2023-08-04 17:19 UTC, thanvirm commented
Would you be able to add a unit test to [InMobiExtrasBuilderTest.kt](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/inmobi/inmobi/src/test/kotlin/com/google/ads/mediation/inmobi/InMobiExtrasBuilderTest.kt) to verify that InMobiExtrasBuilder.build() correctly sets the IAP US Privacy string on the InMobi SDK?

2023-08-04 20:09 UTC, merged