Update IronSource Adapter to the new architecture and added Banner
googleads/googleads-mobile-android-mediation pull request #483
Opened 2023-08-13 07:54 UTC by alon357

hi @joshuajplagonera
I wanted to share the latest PR
we have decided to refactor the adapter according to the notes you have shared. We even took extra measures to clean up and fix legacy issues.

Overall, the adapter architecture is as follows:
IronSourceAdapter and IronSourceRewardedAdapter extend IronSourceMediationAdapter.
IronSourceMediationAdapter extends Adapter and is in charge of SDK Initialization and the different load functions.
We have created new classes for each ad format: IronSourceBannerAd, IronSourceInterstitialAd, and IronSourceRewardedAd. Each class contains the ad format-specific functionality.
Each of the above classes contains a static instance of either IronSourceBannerAdListener, IronSourceInterstitialAdListener or IronSourceRewardedAdListener. These handle the SDK callbacks for the respective ad format.
We decided to remove the use of WeakAdapters as it caused GC issues in the new design.
We have removed the IronSourceManager class and split its functionality between the different ad format classes.
We have created a new IronSourceRewardItem class, which is used by the IronSourceRewardedAd class on the reward callback.

I think this integration is much clearer and more organized.
Included here is a [UML overview](https://drive.google.com/file/d/1-5iONzEHMQmodSVFu2emcrSxjIM5Nh4Y/view?usp=sharing) that displays the architecture.

2023-08-14 20:34 UTC, joshuajplagonera requested changes

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  }
Change tabs to spaces.

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +	return new ISBannerSize(closestSize.getWidth(), closestSize.getHeight());
We might want to add a comment here why we are creating a custom `ISBannerSize` instead of returning a preset size.

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  public static AdError validateIronSourceAdLoadParams(Context context, String instanceID) {
Add `nullability` everywhere,

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +      Log.e(TAG, errorMessage);
Should be a warning log, or remove since were already logging in `onAdFailedToLoad()`

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +  public void setBannerAdCallback(MediationBannerAdCallback adCallback) {
Is there a reason these setters are `public` and not "package private" ? Seems it should be package private at least since publishers can set their own `MediationBannerAdCallback` object , which breaks the adapter. This applies to the other Getters/Setters below and in other classes.

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +    Log.w(TAG, loadError.getMessage());
Log `toString()` for logging `AdError` objects.
Apply to other classes where applicable.

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +  }
Can be cleaned up:
```
if (ironSourceBannerAd == null) {
  // Log warning if applicable.
  return;
}

if (ironSourceBannerAd.getIronSourceAdView() != null) {
  //...
}

if (ironSourceBannerAd.getAdLoadCallback() != null) {
  //..
}
```

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +    Log.w(TAG, errorMessage);
Log `loadError` `AdError` objects and not the error message.

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceConstants.java
> +  // endregion
Is there a reason why these were removed from the `@AdapterError` interface from `IronSourceMediationAdapter` class ?
For reference, other adapters have error codes using said interface in the main adapter class.

2023-08-14 20:34 UTC, joshuajplagonera commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
We are checking `isInitialized()` before loading ads. But if it is not initialized, then we do nothing, which I believe will cause an adapter timeout with 0 feedback to the publisher.

We should attempt to initialize the IronSource SDK, if not already initialized, at load time, on each respective class' `loadAd()` method.

2023-08-16 07:35 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  }
Done

2023-08-16 07:36 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +	return new ISBannerSize(closestSize.getWidth(), closestSize.getHeight());
Added Comment.

2023-08-16 07:36 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +  public static AdError validateIronSourceAdLoadParams(Context context, String instanceID) {
Added nullability in all relevant places.

2023-08-16 07:36 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +      Log.e(TAG, errorMessage);
Done.

2023-08-16 07:37 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +  public void setBannerAdCallback(MediationBannerAdCallback adCallback) {
Getters and Setters have been made package private.

2023-08-16 07:37 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +    Log.w(TAG, loadError.getMessage());
Done.

2023-08-16 07:37 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +  }
Updated accordingly.

2023-08-16 07:38 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceConstants.java
> +  // endregion
Reverted the error codes back to IronSourceMediationAdapter

2023-08-16 07:38 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +    Log.w(TAG, errorMessage);
Done.

2023-08-16 07:40 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
We have added a logic to return load fail in case of loading when the SDK is not initialized.

2023-08-24 11:09 UTC, Ophir-IS commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
Hey @joshh-devrel (Ophir here, from Alon's team), thanks for the question. We find that having a possible call to our SDK initialization on every ad load can lead to some issues. We currently prefer keeping the current implementation where we initialize our SDK in a single place, and an init failure on our side means we will not take part in the current session. The same applies to all ad units.

2023-08-29 22:07 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    initializationCompleteCallback.onInitializationSucceeded();
@alon357 @Ophir-IS 
===BLOCKIN===
Shouldn't we check if it's initialized before setting it to true and call initialization succeeded callback?

Also I don't see initialization failure callback anywhere.

2023-08-29 22:08 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +        IronSourceRewardedAd.getIronSourceRewardedListener());
Why don't we set these in `IronSourceInterstitialAd` or `IronSourceRewardedAd` instead?

2023-08-29 22:08 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
Thanks @Ophir-IS. A follow-up, since we did `isInitialized.set(true);` above, will this statement `if (isInitialized.get())` always be true?

2023-08-30 13:36 UTC, Ophir-IS commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
Assuming `initialize()` is always called before `loadRewardedAd()` (or any other ad unit load function), then yes this is correct.

2023-08-30 13:38 UTC, Ophir-IS commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +        IronSourceRewardedAd.getIronSourceRewardedListener());
The `IronSourceInterstitialAd`/`IronSourceRewardedAd` classes contain instance specific logic, so while we could set the listeners from a static block in these classes, we prefer setting the listeners in proximity to the init for clarity.

2023-09-02 00:13 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +import static com.ironsource.mediationsdk.logger.IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS;
@alon357 @Ophir-IS 
Our internal system failed to build the adapter since these two error codes can't be found in IronSource version SDK 7.5.0. Can you take a look on your end and see what error codes should be used instead?

2023-09-03 07:34 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +import static com.ironsource.mediationsdk.logger.IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS;
Hi @joshh-devrel 
There were no changes in the path or the class.
Those error codes are in the same place as in the SDK before.
![Screenshot 2023-09-03 at 10 31 32](https://github.com/googleads/googleads-mobile-android-mediation/assets/2397822/08a76131-63cf-4405-a82f-d7b41d585744)

2023-09-03 18:13 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +import static com.ironsource.mediationsdk.logger.IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS;
@alon357 @Ophir-IS 

Sorry I should only highlight `ERROR_DO_BN_LOAD_ALREADY_IN_PROGRESS`.
`ERROR_DO_BN_LOAD_ALREADY_IN_PROGRESS` couldn't be found, but `ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS` could be found.

<img width="1063" alt="Screenshot 2023-09-03 at 11 12 00 AM" src="https://github.com/googleads/googleads-mobile-android-mediation/assets/86074166/223026eb-0a61-4435-9951-a719eada359d">

2023-09-05 17:13 UTC, joshh-devrel commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +import static com.ironsource.mediationsdk.logger.IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS;
@alon357 @Ophir-IS Would you have an update on this?

2023-09-06 08:56 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +import static com.ironsource.mediationsdk.logger.IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS;
Hi @joshh-devrel 
We have found the issue and are working on a hotfix.
Once it is released we will update the PR
Thanks

2023-09-06 17:46 UTC, LTPhantom requested changes

2023-09-06 17:46 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +    if (ironSourceBannerAd != null) {
Only if we are keeping this class.
nit: For easier readability, isolate this validation and take the rest of the code out of the if.
```suggestion
    if (ironSourceBannerAd == null) {
      return;
    }
```

2023-09-06 17:46 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
I feel that this class should be removed and the `ISDemandOnlyBannerListener` interface should be implemented by the `IronSourceBannerAd`.

That way we avoid constantly calling `getFromAvailableInstances()` (possibly even delete it), validating if the response is null and all the getters and setters could be deleted.

2023-09-06 17:46 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceInterstitialAd.java
> +  public MediationAdLoadCallback<MediationInterstitialAd, MediationInterstitialAdCallback>
Make this field `private` and `final`?

2023-09-06 17:46 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceInterstitialAdListener.java
Same as `IronSourceBannerAdListener.java`. Would be better to implement on `IronSourceInterstitialAd.java`.

2023-09-06 17:46 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
If we are keeping this validation, may I suggest removing the if-else statement and simplify it at the start of each load method for easier readability like so:
```suggestion
    if (!isInitialized.get()) {
      AdError adError = ... ;
      mediationAdLoadCallback.onFailure(adError);
      return;
    }
```

2023-09-06 17:46 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRewardedAdListener.java
Same as the other AdListeners.

2023-09-07 15:19 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +    if (isInitialized.get()) {
Done

2023-09-07 15:20 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +import static com.ironsource.mediationsdk.logger.IronSourceError.ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS;
Update to 7.5.1 that solve this issue

2023-09-07 15:20 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
As discussed in previous reviews, the ironSource SDK currently accepts only a single listener per ad unit type, through which it delivers callbacks for all ad units of that type. This means we cannot implement the listener interfaces as part of the ad unit classes (e.g. `IronSourceBannerAd`) as these classes are not static and multiple instances of them could exist simultaneously.

2023-09-07 15:21 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceInterstitialAd.java
> +  public MediationAdLoadCallback<MediationInterstitialAd, MediationInterstitialAdCallback>
done

2023-09-07 15:21 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRewardedAdListener.java
Done

2023-09-07 15:23 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java
> +        IronSourceAdapterUtils.getISBannerSizeFromGoogleAdSize(context, adSize);
Done - we have made ironSource's bannerSize an instance field.

2023-09-07 15:24 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +    if (ironSourceBannerAd != null) {
Done

2023-09-07 15:24 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceInterstitialAdListener.java
See our comment above

2023-09-12 07:42 UTC, alon357 commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAdListener.java
> +    if (ironSourceBannerAd.getAdLoadCallback() != null) {
Thanks @LTPhantom We have fixed it

2023-09-12 17:08 UTC, LTPhantom approved these changes

2023-09-13 16:37 UTC, merged