Added support for adding Watermark
googleads/googleads-mobile-android-mediation pull request #490
Opened 2023-09-14 07:18 UTC by venkinmobi

2023-09-27 17:26 UTC, joshh-devrel commented
@venkinmobi Can you update the changlog to include the below?
```
#### Next version
- Added watermark support for bidding banner, interstitial and rewarded ad formats.
```
Thanks!

2023-09-27 19:51 UTC, joshuajplagonera commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/renderers/InMobiBannerAd.java
> +      inMobiBannerWrapper.setWatermarkData(new WatermarkData(watermark, WATERMARK_ALPHA));
Is an empty (`""`) `watermark` data valid for InMobi? If not, maybe using `TextUtils.isEmpty(watermark) != null` is more applicable?

2023-09-28 06:33 UTC, joshh-devrel commented
@venkinmobi Gentle bump, can you take a look at the comments? Thanks!

2023-10-04 17:42 UTC, joshh-devrel commented
@venkinmobi Would you have an update on resolving the comments?

2023-10-10 20:18 UTC, LTPhantom commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/InMobiInterstitialWrapper.java
> +
nit: remove space

2023-10-10 20:18 UTC, LTPhantom commented on ThirdPartyAdapters/inmobi/inmobi/src/main/java/com/google/ads/mediation/inmobi/renderers/InMobiBannerAd.java
> +      inMobiBannerWrapper.setWatermarkData(new WatermarkData(watermark, WATERMARK_ALPHA));
If using `TextUtils.isEmpty` as suggested, also apply for other formats.

2023-10-20 16:12 UTC, joshh-devrel commented
@venkinmobi Gentle bump, can you resolve conflicts and the comments in the pull request?

2023-11-29 04:05 UTC, LTPhantom requested changes
Gentle bump to address the comments. Thanks.

2024-01-04 03:33 UTC, LTPhantom commented
Closing this Pull Request since the watermark support has been already added and will be available in next adapter release.

2024-01-04 03:33 UTC, closed without merging