support mediaview of native view clickable
googleads/googleads-mobile-android-mediation pull request #512
Opened 2024-02-29 07:13 UTC by junjunsong

2024-03-06 18:26 UTC, LTPhantom commented
Could you please add a description to the Pull Request to get a better understanding of the goal of it?

2024-03-07 17:20 UTC, LTPhantom requested changes

2024-03-07 17:20 UTC, LTPhantom commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralNativeAd.java
> -    if (nativeCallback != null) {
It seems that `nativeCallback` is now never used. Can you delete field?

2024-03-08 08:32 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralNativeAd.java
> -    if (nativeCallback != null) {
Sorry. Let me explain the situation of this PR.

In previous versions, due to our failure to handle a series of callbacks related to MBMediaView, events could not be given to the admob sdk through the adapter when interacting with users and MBMediaView.

We have set up listening for MBMediaView this time and also addressed the issue of whether nativeCallback can only have value after the load is completed

2024-03-12 18:41 UTC, LTPhantom commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralNativeAd.java
> -    if (nativeCallback != null) {
Sounds good. Could you add the description to the Pull Request?

Also, it seems to me that this change means that the `nativeCallback` in line 45 is no longer needed. Could you delete it?

2024-03-14 02:11 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralNativeAd.java
> -    if (nativeCallback != null) {
I have deleted the relevant code

2024-03-14 16:33 UTC, LTPhantom reviewed
Thanks for the changes, there is only one last comment.

2024-03-14 16:33 UTC, LTPhantom commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +            ((MBMediaView)childView).setOnMediaViewListener(this);
Can there be more than one `MBMediaView`? Once we've found it and set the listener, can we `break` out of the for loops?

Same with the for loop in `MintegralWaterfallNativeAd`

2024-03-15 08:07 UTC, junjunsong commented on ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
> +            ((MBMediaView)childView).setOnMediaViewListener(this);
done

2024-03-20 16:21 UTC, LTPhantom approved these changes

2024-03-25 21:48 UTC, merged