Vungle adapter 7.3.0.0 release
googleads/googleads-mobile-android-mediation pull request #514
Opened 2024-03-26 23:57 UTC by HuFangshuai

- Verified compatibility with Vungle SDK 7.3.0.

Built and tested with:
- Google Mobile Ads SDK version 22.3.0.
- Vungle SDK version 7.3.0.

2024-04-23 19:20 UTC, thanvirm requested changes

2024-04-23 19:20 UTC, thanvirm commented on ThirdPartyAdapters/liftoffmonetize/CHANGELOG.md
> +#### Version 7.3.1.0
Could you revert the version update changes from this PR since we have already released 7.3.1.0? Sorry for the delay in reviewing this PR. We will pick up these changes for the next release.

2024-05-07 07:59 UTC, closed without merging

2024-05-07 08:00 UTC, HuFangshuai commented on ThirdPartyAdapters/liftoffmonetize/CHANGELOG.md
> +#### Version 7.3.1.0
Thanks, closed this pr since already released the latest version.

2024-05-07 18:48 UTC, thanvirm commented on ThirdPartyAdapters/liftoffmonetize/CHANGELOG.md
> +#### Version 7.3.1.0
You can still create a PR with just the unit tests for VungleInterstitialAdapter. We are happy to review that. Thanks!