Release/iron source mao rtb
googleads/googleads-mobile-android-mediation pull request #527
Opened 2024-08-25 11:24 UTC by jbsrc

2024-09-09 07:28 UTC, jbsrc commented on ThirdPartyAdapters/adaptertestkit/build.gradle
> +  testImplementation "org.powermock:powermock-api-mockito2:2.0.9"
Deleted

2024-09-09 07:28 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
> +
Deleted

2024-09-09 07:29 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +              "Failed to load IronSource rewarded ad since IronSource SDK is not " + "initialized.",
done

2024-09-09 07:29 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
> +              "Failed to load IronSource banner ad since IronSource SDK is not " + "initialized.",
done

2024-09-09 07:29 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +// Copyright 2023 Google LLC
done

2024-09-09 07:29 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +      this.mediationAdLoadCallback.onFailure(loadError);
Done

2024-09-09 07:30 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +    if (this.mediationAdLoadCallback != null) {
Done

2024-09-09 07:31 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +            IronSourceAdapterUtils.buildAdError(
Done

2024-09-09 07:31 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +    if (this.mediationAdLoadCallback != null) {
Done

2024-09-09 07:31 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +    }
Removed

2024-09-09 07:38 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +            IronSourceAdapterUtils.buildAdError(
Done

2024-09-09 07:40 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +      this.interstitialAdCallback.onAdFailedToShow(contextError);
Thanks! fixed.

2024-09-09 07:40 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAd.java
> +    }
Fixed

2024-09-09 07:40 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRtbRewardedAd.java
> +// Copyright 2023 Google LLC
Done

2024-09-09 07:41 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +    private lateinit var initializationCompleteCallback: InitializationCompleteCallback
Done

2024-09-09 07:43 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +    @Before
From what I understand, these settings are local. I changed the settings, but they are only applied for me. You can try changing them as well in the file changes tab --> settings

2024-09-09 07:44 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        assertEquals("com.google.ads.mediation.ironsource", capturedError.domain)
Done

2024-09-09 07:44 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +    @Mock
Done

2024-09-16 22:24 UTC, LTPhantom requested changes

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        MockitoAnnotations.openMocks(this)
Unnecessary line since there should be no Annotations for mocking.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        context = mock(Context::class.java)
Prefer to use `ApplicationProvider.getApplicationContext<Context>()` instead of mocking since Android classes shouldn't be mocked. Also, initialize above.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        initializationCompleteCallback = mock(InitializationCompleteCallback::class.java)
Most of these should be initialized as mocks above. That would mean:
* They can be `private val` instead of `private lateinit var`
* The names of the mocks should start with the mock word (i.e. mockInterstitialAdConfig)

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        val bundleMock = mock(Bundle::class.java)
Unnecessary to mock this, the Bundle class can be used as is. Plus android classes shouldn't be mocked.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        whenever(bundleMock.getString("instanceId", "")).thenReturn("mockInstanceId")
Instead of mocking the bundle, populate it with the necessary values when needed.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        )
Safe boilerplate code by adding the return using the `on` reserved word when initializing the mock. See [this](https://github.com/googleads/googleads-mobile-android-mediation/blob/d5cf8ada20447f756bcb463e0b84f17db3304921/ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt#L77) line for a quick example.

Also, prefer to use the declared TEST constants from the `AdapterTestKitConstants` class like in the `IronSourceMediationAdapterTest`.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        mediationConfigurations = listOf(mockMediationConfiguration)
Initialized twice? If moved to the top it is not necessary to reinitialize them.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        val mockBundle = mock(Bundle::class.java)
Same comments as the other bundle val.

2024-09-16 22:24 UTC, LTPhantom commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        whenever(interstitialAdConfig.context).thenReturn(mock(Activity::class.java))
Prefer `doReturn` instead of `thenReturn`. Same comment for all other uses.

Also, Activity class should not be mocked, use `Robolectric.buildActivity(Activity::class.java).get()` like in the `IronSourceMediationAdapterTest`.

2024-09-18 07:54 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +    private val bannerAdLoadCallback =
Updated

2024-09-18 07:54 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +    private val interstitialAdLoadCallback =
Updated

2024-09-18 07:54 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +    private val rewardedAdLoadCallback =
Updated

2024-09-18 07:54 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +        Mockito.mockStatic(IronSourceAds::class.java).use { mockedStatic ->
Removed

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
> +            mockedStatic.`when`<Unit> {
Done

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        MockitoAnnotations.openMocks(this)
Done

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        context = mock(Context::class.java)
Updated

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        initializationCompleteCallback = mock(InitializationCompleteCallback::class.java)
Updated

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        val bundleMock = mock(Bundle::class.java)
Done

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        whenever(bundleMock.getString("instanceId", "")).thenReturn("mockInstanceId")
Updated

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        )
Updated

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        val mockBundle = mock(Bundle::class.java)
Updated

2024-09-18 07:55 UTC, jbsrc commented on ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRtbInterstitialAdTest.kt
> +        whenever(interstitialAdConfig.context).thenReturn(mock(Activity::class.java))
Updated

2024-10-02 22:41 UTC, merged